---
title: "Run all models MERF LongituRF"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r, include = FALSE, message=F}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = F,
  warning = F,
  message = F
)

```

```{r}

library(dplyr)
library(stringr)
library(tidyr)
library(readr)
library(patchwork)
library(ggcorrplot)

theme_set(theme_bw())

# library(sjmisc)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")


```


```{r}

source('R/scripts_functions/functions_tools.R')

data_all_diff <-  read_rds( "data/data_all_diff_with_imputations.rds")

data_BE_CE_SE <- read_rds("data/data_BE_CE_SE_LER.rds")%>% shorten_exp_id()


data_diff_wt_fababean <- data_all_diff%>%
  left_join(data.intercrop::index %>% distinct(experiment_id, management, species_mix)) %>%
  filter(species_mix== "wheat_turgidum_fababean") %>%
  shorten_exp_id()

data_diff_wt_pea <- data_all_diff%>%
  left_join(data.intercrop::index %>% distinct(experiment_id, management, species_mix)) %>%
  filter(species_mix== "wheat_turgidum_pea") %>%
  shorten_exp_id()


index <- data.intercrop::index %>% 
  shorten_exp_id()%>%
  inner_join(data_diff_wt_fababean %>% distinct(experiment_id, management) ) 


yield_cereal_wt_fababean <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "cereal") %>%
  inner_join(data_diff_wt_fababean %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_cereal = value)

yield_legume_wt_fababean <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "legume") %>%
  inner_join(data_diff_wt_fababean %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_legume = value)

N_seed_cereal_wt_fababean <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "nitrogen_seed", plant_family == "cereal") %>%
  inner_join(data_diff_wt_fababean %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, N_seed_cereal = value)



data_performance_wt_fababean <- data_BE_CE_SE %>%
  inner_join(yield_cereal_wt_fababean) %>% 
  inner_join(yield_legume_wt_fababean) %>% 
  inner_join(N_seed_cereal_wt_fababean) %>% 
  filter(!is.na(N_seed_cereal)) %>% 
  select(contains("PLER"), contains("yield"), N_seed_cereal)%>% 
  rename_with(cols = everything(), .fn = ~str_replace_all(.x,c("PLER_" ="pLER ", "yield_" = "Rdt ", "cereal" = "blé", "legume" = "féverole", "N_seed_" = "%N ")))



yield_cereal_wt_pea <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "cereal") %>%
  inner_join(data_diff_wt_pea %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_cereal = value)

yield_legume_wt_pea <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "legume") %>%
  inner_join(data_diff_wt_pea %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_legume = value)

N_seed_cereal_wt_pea <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "nitrogen_seed", plant_family == "cereal") %>%
  inner_join(data_diff_wt_pea %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, N_seed_cereal = value)


data_performance_wt_pea <- data_BE_CE_SE %>%
  inner_join(yield_cereal_wt_pea) %>% 
  inner_join(yield_legume_wt_pea) %>%
  inner_join(N_seed_cereal_wt_pea) %>%
  filter(!is.na(N_seed_cereal)) %>% 
  select(contains("PLER"), contains("yield"), N_seed_cereal) %>% 
  rename_with(cols = everything(), .fn = ~str_replace_all(.x,c("PLER_" ="pLER ", "yield_" = "Rdt ", "cereal" = "blé", "legume" = "pois", "N_seed_" = "%N ")))

```


```{r}

corr_wt_pea <- cor(data_performance_wt_pea)

corr_wt_fababean <- cor(data_performance_wt_fababean)



corrplot_wt_fababean <- ggcorrplot(corr_wt_fababean, 
           # hc.order = TRUE, 
           type = "upper",
           show.legend = FALSE,
           # method ="circle",
           tl.cex = 9,
           lab = TRUE)

# diag(corr_wt_pea) = 0
corrplot_wt_pea <- ggcorrplot(corr_wt_pea, 
           # hc.order = TRUE,
           type = "upper",
           show.legend = FALSE,
           # show.diag = TRUE,
           tl.cex = 9,
           lab = TRUE)


(plot_combined <- (corrplot_wt_fababean | corrplot_wt_pea) + patchwork::plot_annotation(tag_levels = "A"))


ggsave("figures/plot_correlations_performance.png", plot =plot_combined, width  = 15, height = 8, unit = "cm")


file.copy("figures/plot_correlations_performance.png", to  ="C:/Users/rmahmoud/Dropbox/Applications/Overleaf/Manuscrit thèse/chap4_modeling_IC/figures/plot_correlations_performance.png", overwrite = TRUE)
```
