---
title: "Exploration performance metrics"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r, include = FALSE, message=F}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = F,
  warning = F,
  message = F
)

```

```{r}

library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)



theme_set(theme_bw())

# library(sjmisc)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")


```


```{r functions}
# Read all functions
list_functions <- list.files("R/scripts_functions", full.names = TRUE)
invisible(lapply(list_functions, source))

#wrapper around gmerf

```


```{r}
data_all_diff <-  read_rds( "data/data_all_diff_with_imputations.rds")

data_BE_CE_SE <- read_rds("data/data_BE_CE_SE_LER.rds")%>% 
  shorten_exp_id()



experiment_id_management <- data_all_diff%>%
  left_join(data.intercrop::index %>% distinct(experiment_id, management, species_mix)) %>%
  shorten_exp_id() %>% 
  distinct(experiment_id, species_mix, management)


index <- data.intercrop::index %>% 
  shorten_exp_id()



yield_cereal <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "cereal") %>%
  inner_join(experiment_id_management) %>% 
  distinct(experiment_id, management, species_mix,  yield_cereal = value)

yield_legume <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "legume") %>%
  inner_join(experiment_id_management) %>% 
  group_by(experiment_id, management, species_mix) %>% 
  summarise(value = max(value),.groups = "drop") %>% 
  distinct(experiment_id, management, species_mix,  yield_legume = value)


data_performance <- data_BE_CE_SE %>%
  left_join(yield_cereal) %>%
  left_join(yield_legume) %>%
  mutate(yield_total = yield_legume + yield_cereal) %>% 
  relocate(species_mix, .after = management)

```


```{r}

library(latex2exp)

(plot_performance <- data_performance%>% 
  pivot_longer(-c(experiment_id, management, species_mix)) %>% 
  # drop_na(value) %>% 
  mutate(type = case_when(
    str_detect(name, "LER") ~ "LER",
    str_detect(name, "yield") ~ "Yield",
    TRUE ~ "Decomposition BE"
  )) %>% 
  mutate(name = forcats::fct_relevel(name, c("CE", "SE", "BE", "PLER_cereal", "PLER_legume", "LER"))) %>%
  ggplot(aes(x = name, y = value, fill = species_mix)) +
  geom_boxplot(outlier.size =0) +
  facet_wrap(type~., scales ="free", ncol =3) +
  geom_abline(intercept = 0, linetype = "dashed", slope = 0) + 
  geom_point(pch = 21, position = position_jitterdodge(jitter.width = .01)) +
  ggthemes::theme_solarized()+ 
   theme(title = element_text(color = "black", size = 16), 
         legend.text = element_text(color = "black"), 
         strip.text = element_text(size = 14),
         axis.text = element_text(color = "black", size = 14))+ 
  theme(legend.position =  "bottom", legend.title = element_blank()) + 
   scale_x_discrete(labels = c("yield_cereal" = parse(text = TeX("$Y_C$")),
                               "yield_legume" = parse(text = TeX("$Y_L$")),
                               "yield_total" = parse(text = TeX("$Y_T$")),
                               "PLER_cereal" = parse(text = TeX("$PLER_C$")),
                               "PLER_legume" = parse(text = TeX("$PLER_L$")))) + 
  labs(x = NULL, y = NULL))

ggsave("figures/plot_performance_metrics.png", plot = plot_performance, width = 18, height = 16, unit ="cm", dpi = "retina")
```

```{r}

library(GGally)


data_performance %>% select(species_mix:yield_total) %>% ggpairs(aes(color = species_mix))


mod.pca <- FactoMineR::PCA(data_performance %>% select(species_mix:yield_total) , scale.unit = TRUE, quali.sup = 1)

(biplot_pca_performance_metrics <- factoextra::fviz_pca_biplot(mod.pca, habillage = "species_mix", label = "var",labelsize = 5) +
  ggthemes::theme_solarized() +
  theme(legend.position = "bottom", legend.background = element_rect(fill = "#fdf6e3"),
        text = element_text(color = "black"),
        title = element_text(color = "black"), plot.title = element_blank()))

ggsave("figures/biplot_pca_performance_metrics.png", plot = biplot_pca_performance_metrics, width = 18, height = 16, unit ="cm", dpi = "retina")

# mod.pca$ind$coord %>% 
#   as_tibble %>%
#   bind_cols(data_performance %>% select(experiment_id, species_mix)) %>% 
#   ggplot(aes(x = Dim.1,  y= Dim.2)) + 
#   geom_point(aes(color = species_mix)) +
#   ggthemes::theme_solarized()+ 
#   theme(title = element_text(color = "black", size = 16), 
#         legend.text = element_text(color = "black"), 
#         strip.text = element_text(size = 14),
#         axis.text = element_text(color = "black", size = 14), 
#         legend.position = "bottom")


data_performance %>% 
  ggplot(aes(x = PLER_cereal, y = yield_cereal)) + 
  geom_point(aes(color = species_mix))





(biplot_pca_performance_metrics_1_3 <- factoextra::fviz_pca_biplot(mod.pca, habillage = "species_mix", label = "var",labelsize = 5,  axes = c(1, 3)) +
  ggthemes::theme_solarized() +
  theme(legend.position = "bottom", legend.background = element_rect(fill = "#fdf6e3"),
        text = element_text(color = "black"),
        title = element_text(color = "black"), plot.title = element_blank()))


(biplot_pca_performance_metrics_2_3 <- factoextra::fviz_pca_biplot(mod.pca, habillage = "species_mix", label = "var",labelsize = 5,  axes = c(2, 3)) +
  ggthemes::theme_solarized() +
  theme(legend.position = "bottom", legend.background = element_rect(fill = "#fdf6e3"),
        text = element_text(color = "black"),
        title = element_text(color = "black"), plot.title = element_blank()))



```



```{r copy to presentation folder}

folder_modeling <- "C:/Users/rmahmoud/Documents/INRA/These/R_projects_phD/paper_modeling_intercrop/figures"
folder_presentations <- "C:/Users/rmahmoud/Documents/INRA/These/Presentations/meeting_22_11_2022/presentation_figures"
list_of_files <- list.files(folder_modeling, ".*plot_.*performance.*.png$",recursive = TRUE, full.names = TRUE) 

file.copy(file.path(list_of_files), folder_presentations, overwrite = TRUE)
```
 
