---
title: "Caracterize environmental conditions of the considered experiments"
output: rmarkdown::pdf_document

---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE
)
```

```{r setup}



library(data.intercrop)
library(dplyr)
library(ggplot2)
library(knitr)
library(tidyr)
library(stringr)

# devtools::install_github("RemiMahmoud/functions.helper")
library(functions.helper)

theme_set(theme_bw())

# Set wd to project source
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```




# Set data of all experiments

```{r}

traits <- data.intercrop::traits$plot

traits_crop <- data.intercrop::traits$crop



experiments_paper <- data.intercrop::index %>% filter(species_mix %in% c("wheat_turgidum_pea", "wheat_turgidum_fababean"),  experiment_id %in% c("Auzeville_SGs_2007", "Auzeville_TE_2006", "Auzeville_TO_2013",  "Auzeville_cochard_2010", "Auzeville_PP_2011", "Auzeville_ZN_2012")) %>% distinct(experiment_id, species_mix)

index <- data.intercrop::index %>% inner_join(experiments_paper)


environment <- data.intercrop::environment %>% inner_join(experiments_paper) %>% filter(crop_type == "IC")%>% distinct(experiment_id, species_mix,TM, SRR) %>% 
  group_by(experiment_id, species_mix) %>% 
  summarise(across(where(is.numeric), mean), .groups = "drop") %>% 
  relocate(species_mix, 1) %>% 
  relocate(TM, .before = SRR)
```

# Environmental conditions


```{r}


n_obs <- index %>% inner_join(experiments_paper) %>% filter(crop_type == "IC") %>% distinct(experiment_id, management, species_mix) %>% count(experiment_id, species_mix)

table_environment <- environment %>%
  inner_join(experiments_paper) %>%
  left_join(index %>% distinct(experiment_id, year, sowing_date, harvest_date, species_mix,  N_amount)) %>% 
  group_by(experiment_id, species_mix,year, sowing_date, harvest_date, TM, SRR) %>% 
  summarise(N_fertilisation = paste0(sort(unique(N_amount)), collapse = "-"), .groups = "drop") %>% 
  # filter(crop_type == "IC") %>% 
  mutate(TM = round(TM, digits = 1), SRR = round(SRR, digits = 1))%>%
  left_join(n_obs) %>% 
  mutate(species_mix = str_replace_all(species_mix, c("wheat_turgidum_pea" = "Durum wheat / Pea", 
                                                      "wheat_turgidum_fababean" = "Durum wheat / Faba bean"))) %>% 
  mutate(experiment_id = str_replace_all(experiment_id, c("Auzeville" = "Auz", "_cochard" =""))) %>% 
  arrange(species_mix, year) %>% 
  distinct("Species mixture" = species_mix,"Experiment"= experiment_id,  "Sum of precipitations (mm)" = SRR, "Mean temperature (°C)" = TM, "N fertilization (kg/ha)" = N_fertilisation, "Sowing date" = sowing_date, "Harvest date" = harvest_date, "Nb. of observations"= n) 



# Write table in a TeX format

library(kableExtra)


sink("doc/table_environment.tex")
kable(table_environment, booktabs = TRUE,  escape = TRUE, format = "latex", longtable = T, label = "table_environement", caption = "Environmental conditions and caracteristics of the experiments") %>% 
  # add_header_above(c(" ", "colLabel1"=2, "colLabel2"=2)) %>% 
  kable_styling(latex_options = "HOLD_position") %>%
  column_spec(2:4, width = "1.5cm") %>%
  column_spec(c(6:7), width = "2cm") %>%
  column_spec(c(1,5), width = "1.5cm") %>%
  column_spec(c(8), width = "1cm") %>%
  collapse_rows(columns = c(1 ))
sink()


# file.copy( from = "doc/table_environment.tex", to  ="C:/Users/rmahmoud/Dropbox/Applications/Overleaf/Manuscrit thèse/chap4_modeling_IC/tables/table_environment.tex", overwrite = TRUE)

# file.copy( from = "doc/table_environment.tex", to  ="C:/Users/rmahmoud/Dropbox/Applications/Overleaf/Paper modeling intercrops/tables/table_environment.tex", overwrite = TRUE)

```



```{r tab FR}
data_N_residual <- tibble(experiment_id = c("Auzeville_cochard_2010", "Auzeville_PP_2011", "Auzeville_SGs_2007","Auzeville_TE_2006", "Auzeville_TO_2013", "Auzeville_ZN_2012"), N_resid = c(35,53,39,45,41,36))


n_obs <- index %>% inner_join(experiments_paper) %>% filter(crop_type == "IC") %>% distinct(experiment_id, management, species_mix) %>% count(experiment_id, species_mix)

table_environment <- environment %>%
  inner_join(experiments_paper) %>%
  left_join(data_N_residual) %>% 
  left_join(index %>% distinct(experiment_id, year, sowing_date, harvest_date, species_mix,  N_amount)) %>% 
  group_by(experiment_id, species_mix,year, N_resid, sowing_date, harvest_date, TM, SRR) %>% 
  summarise(N_fertilisation = paste0(sort(unique(N_amount)), collapse = "-"), .groups = "drop") %>% 
  # filter(crop_type == "IC") %>% 
  mutate(TM = round(TM, digits = 1), SRR = round(SRR, digits = 1))%>%
  left_join(n_obs) %>% 
  mutate(species_mix = str_replace_all(species_mix, c("wheat_turgidum_pea" = "Blé dur / Pois", 
                                                      "wheat_turgidum_fababean" = "Blé dur / Féverole"))) %>% 
  mutate(experiment_id = str_replace_all(experiment_id, c("Auzeville" = "Auz", "_cochard" =""))) %>% 
  arrange(species_mix, year) %>% 
  distinct("Mélange d'espèces" = species_mix,"Année"= year,  "Somme des précipitations (mm)" = SRR, "Température moyenne (°C)" = TM, "Reliquat N (kg/ha)" = N_resid, "Fertilisation N (kg/ha)" = N_fertilisation, "Date de semis" = sowing_date, "Date de récolte" = harvest_date, "Nb. d'observations"= n) 



# Write table in a TeX format

library(kableExtra)


sink("doc/table_environment.tex")
kable(table_environment, booktabs = TRUE,  escape = TRUE, format = "latex", longtable = T, label = "table_environement_chap_modeling", caption = "Conditions environnementales et caractéristiques des expérimentations (toutes conduites à Auzeville)") %>% 
  # add_header_above(c(" ", "colLabel1"=2, "colLabel2"=2)) %>% 
  kable_styling(latex_options = "hold_position", font_size = 9) %>%
  column_spec(1, width = "1.3cm") %>%
  column_spec(2, width = "1cm") %>%
  column_spec(4:5, width = "1.3cm") %>%
  column_spec(3, width = "1.5cm") %>%
  column_spec(c(7), width = "1cm") %>%
  column_spec(c(6), width = "1.5cm") %>%
  column_spec(c(1,5), width = "1.5cm") %>%
  column_spec(c(8:9), width = "1cm") %>%
  collapse_rows(columns = c(1 ))
sink()



# file.copy( from = "doc/table_environment.tex", to  ="C:/Users/rmahmoud/Dropbox/Applications/Overleaf/Manuscrit thèse/chap4_modeling_IC/tables/table_environment.tex", overwrite = TRUE)

# file.copy( from = "doc/table_environment.tex", to  ="C:/Users/rmahmoud/Dropbox/Applications/Overleaf/Paper modeling intercrops/tables/table_environment.tex", overwrite = TRUE)

```

