---
title: "Summary models LongituRF"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r, include = FALSE, message=F}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = F,
  warning = F,
  message = F
)

```

```{r}

library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)
library(forcats)

library(LongituRF)


library(patchwork)
library(latex2exp)

# Modeling
library(nlme)


library(latex2exp)

theme_set(theme_bw()+ 
   theme(axis.title = element_text(size = 16),
         legend.title = element_text(size = 6),
         axis.text = element_text(size=  14),
         # legend.key.size = 6,
         legend.text = element_text(size=  6 ),
         strip.text = element_text(size= 12),
         legend.position = "bottom"))


conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")


```


```{r functions}
# Read all functions
list_functions <- list.files("R/scripts_functions", full.names = TRUE)

# "R/scripts_functions/function_gmerf_modified.R",
list_functions <- c("R/scripts_functions/functions_analysis_models_MERF.R", "R/scripts_functions/functions_evaluate_errors.R",
                    "R/scripts_functions/functions_LongituRF_modified.R", "R/scripts_functions/functions_tools.R")

invisible(lapply(list_functions, source))


```




```{r}
format_importance <- function(data_models, name_model = NULL){
  
  n_models <- length(unique(data_models$.imp))
  
  
  if(is.null(name_model)){name_model <-deparse(substitute(data_models))}
  
  data_output <-  get_importance(data_models) %>% 
    filter(n >= n_models) %>% 
    arrange(desc(mean_importance)) %>% 
    mutate(rank = 1:n(), model = name_model) %>% 
    distinct(variable, mean_importance, sd_importance, rank, sign_cor, model )  

  return(data_output)
}
```


```{r function to make the tile plots of the variabels}

all_predictors <- c(read_rds("data/data_all_diff_with_imputations.rds") %>% select(matches("diff|cover|cult|NNI")) %>% colnames,
                    "NNI_legume", "NNI_cereal", "cult_C", "cult_L", "legume")

all_predictors <- c("diff_IC_SC_asymp_biomass_cereal", "diff_IC_SC_asymp_height_cereal","diff_IC_SC_lambda_biomass_cereal", "diff_IC_SC_lambda_height_cereal", 
"diff_IC_SC_slope_biomass_cereal", "diff_IC_SC_slope_height_cereal", "diff_IC_SC_asymp_biomass_legume", "diff_IC_SC_asymp_height_legume", 
"diff_IC_SC_lambda_biomass_legume", "diff_IC_SC_lambda_height_legume","diff_IC_SC_slope_biomass_legume", "diff_IC_SC_slope_height_legume", "diff_IC_SC_max_sla_GLT_cereal", "diff_IC_SC_max_LAI_legume", "diff_IC_SC_max_sla_GLT_legume","diff_IC_SC_max_LAI_cereal", 
"diff_asymp_biomass", "diff_asymp_height", "diff_lambda_biomass", "diff_lambda_height", "diff_max_LAI", "diff_max_sla_GLT", "diff_slope_biomass", 
"diff_slope_height",  
"cover_before_800_normalized_tt", "cover_before_800_normalized_tt_SC_cereal", "cover_before_800_normalized_tt_SC_legume", "NNI_legume", "NNI_cereal", 
"cult_C", "cult_L", "legume")




plot_importance_all_models <- function(list_models, vec_predictors = all_predictors, remove_unused_predictors = FALSE, add_species_mix = FALSE, size_label = 3){
  
  # get all the importances in a tibble
  data_importance <- tibble()
  for(model in list_models){
    
    print(model)
    name_model <- model
    
    model <- get(model, envir = .GlobalEnv)
    
    # name_model = paste(name_model, nrow(model), sep = " - ")
    
    data_importance <- bind_rows(data_importance, format_importance(model, name_model = name_model))
    
    
  }
  
  
  # order variables and factor in a good way, rename perforamnce variable
  data_all_predictors <-   tibble(variable = as.factor(vec_predictors)) %>% 
  # as_tibble() %>%
    mutate(variable = stringr::str_replace(variable, "_cereal" , "_C")) %>%  
    mutate(variable = stringr::str_replace(variable, "_legume" , "_L"))%>% 
    full_join(data_importance, x = .) %>% 
    filter(variable != "diff_asymp_biomass") %>% 
    mutate(variable = as.factor(variable)) %>% 
    mutate(sign_cor = fct_recode(sign_cor, "+" = "POS","-" = "NEG")) %>% 
    mutate(label_cor = paste( rank, sign_cor,sep = " ; ")) %>% 
    mutate(type = str_extract(variable, "NNI|height|LAI|sla|biom|cover|cult")) %>% 
    arrange(type, variable) %>% 
    mutate(variable = fct_inorder(variable))%>% 
    filter(!is.na(model)) %>% 
    mutate(model = fct_relevel(model, list_models)) %>% 
    mutate(leg_id = str_extract(model, "pea|fababean")) %>% 
    mutate(model_formatted = str_replace_all(model, c("_"=" ", "PLER cereal" = "pLER blé", "PLER legume" = "pLER lég\n", "yield"= "Rendement\n", "cereal"= "blé", "legume" = "lég", "all species" = "")) ) %>% 
    rowwise %>% 
    mutate(model_formatted = if_else(str_detect(model, "all_species"), 
                                     str_remove(model_formatted, "\n"),
                                     str_replace_all(model_formatted, c("lég\n" = leg_id,  "lég" = leg_id, "pea" = "pois", "fababean" = "féverole")))) %>% 
    ungroup
  
  # %>% 
  
  if(add_species_mix){data_all_predictors$model_formatted <- str_replace_all(data_all_predictors$model_formatted, c("wt pea" = " (blé / pois)", "wt fababean"=  " (blé / féverole)", "all species" = "toutes espèces"))} else {data_all_predictors$model_formatted <- str_replace_all(data_all_predictors$model_formatted, c( "wt pois" = "", "wt féverole"=  "", "all species" = ""))}
  
  
  vec_predictors_for_ordering <- str_replace_all(vec_predictors, c("_cereal" = "_C", "_legume" = "_L"))
  vec_predictors_for_ordering <- vec_predictors_for_ordering[which(vec_predictors_for_ordering %in% data_all_predictors$variable)]
  
  
  plot_output <- data_all_predictors %>% 
    arrange(model) %>% 
    mutate(model_formatted = fct_inorder(model_formatted)) %>% #order columns
    mutate(variable = forcats::fct_relevel(variable, rev(vec_predictors_for_ordering))) %>% #order lines 
    ggplot(aes(x = model_formatted, y = variable)) + 
    geom_tile(aes(fill = rank), color = "black", alpha = .8) + 
    geom_label(aes(label = label_cor), size= size_label) +
    my_scale_y(drop_val = remove_unused_predictors) +
    scale_fill_distiller(palette = "YlOrRd", direction = -1) + 
    scale_alpha_continuous(range = c(0.1,0.8)) + 
    scale_x_discrete(position = "top") +
    theme(axis.text.x = element_text(angle = 90), 
          panel.grid.major.x =  element_blank(),
          axis.text = element_text(size = 8),
          axis.text.y = element_text(size = 10),
          legend.background = element_rect(fill = as.character(theme_get()$panel.background$fill))) + 
    labs(x=NULL, y = NULL, fill = "Rang")
  
    return(plot_output)

}


```





```{r read models}


add_data_to_mod.MERF <- function(mod.MERF, data){
  mod.MERF$data = data
  return(mod.MERF)
}

read_and_assign <- function(path, name_to_assign_suffix = NULL, filter_iterations = TRUE) {
  model <- read_rds(path)  %>% 
    mutate(n_iterations = map_dbl(mod.MERF, ~length(.x$vraisemblance))) %>% 
    mutate(mod.MERF = map2(mod.MERF, data, add_data_to_mod.MERF))
  

  name_to_assign <- unlist(stringr::str_split(path, "\\."))[1]
  name_to_assign <- stringr::str_remove(name_to_assign, "models/MERF/wt_pea/|models/MERF/wt_fababean/|models/MERF/all_species/" )
  
  
  
  if(filter_iterations){
    
    # model <- model
    
    any_not_converged <- max(model$n_iterations) %in% c(1000,3000)
    
      print(paste(name_to_assign, "max iterations" , max(model$n_iterations)))
      model <- model %>%
        mutate(any_not_converged = any_not_converged) %>% 
        filter( (n_iterations < max(n_iterations) & any_not_converged) | (!any_not_converged)) %>% 
        select(-any_not_converged)

  }
  
  
  if(!is.null(name_to_assign_suffix)){name_to_assign = paste(name_to_assign, name_to_assign_suffix, sep = "_")}
  if(nrow(model)>0){assign(x = name_to_assign,  value = model, envir = .GlobalEnv)}
}



function_read_all_model <- function(list_paths = list_models){
  
  invisible(lapply(list_paths, read_and_assign))
} 





list_models <-  grep(list.files("models/MERF", recursive = TRUE, full.names = TRUE), pattern='models_train', invert=TRUE, value=TRUE)
function_read_all_model(list_paths = list_models)


# 
list_models_environment <- str_remove_all(list_models, "models/MERF/wt_pea/|models/MERF/all_species/|models/MERF/wt_fababean/|.rds")
# list_models_environment <- ls()[ls()%in% list_models_environment]
```




```{r, eval = FALSE}



# c("BE_all_species", "BE_wt_fababean", "BE_wt_pea", "CE_all_species", "CE_wt_fababean", "CE_wt_pea", "LER_all_species", "LER_wt_fababean", "LER_wt_pea", "PLER_cereal_all_species", "PLER_cereal_wt_fababean", 
# "PLER_cereal_wt_pea", "PLER_legume_all_species", "PLER_legume_wt_fababean", "PLER_legume_wt_pea", "SE_all_species", "SE_wt_fababean", "SE_wt_pea", "yield_cereal_all_species", "yield_cereal_wt_fababean", "yield_cereal_wt_pea", "yield_legume_all_species", "yield_legume_wt_fababean", "yield_legume_wt_pea", "yield_total_all_species", "yield_total_wt_fababean", "yield_total_wt_pea")


summary_yield_cereal_legume_wt_pea <- c("yield_cereal_wt_pea", "yield_legume_wt_pea", "yield_total_wt_pea")
summary_yield_cereal_legume_wt_fababean <- c("yield_cereal_wt_fababean", "yield_legume_wt_fababean", "yield_total_wt_fababean")

summary_BE_cereal_legume_wt_pea <- c("BE_wt_pea", "BE_wt_fababean", "BE_all_species")
summary_CE_cereal_legume_wt_pea <- c("CE_wt_pea", "CE_wt_fababean", "CE_all_species")
summary_SE_cereal_legume_wt_pea <- c("SE_wt_pea", "SE_wt_fababean", "SE_all_species")

summary_PLER_cereal_legume_wt_pea <- c("PLER_cereal_wt_pea", "PLER_legume_wt_pea", "LER_wt_pea")
summary_PLER_cereal_legume_wt_fababean <- c("PLER_cereal_wt_fababean", "PLER_legume_wt_fababean", "LER_wt_fababean")



summary_yield_cereal_legume_wt_fababean <- c("yield_cereal_wt_fababean", "yield_cereal_wt_pea", "yield_cereal_all_species")
plot_yield_cereal_wt_fababean_wt_pea_all_species <- plot_importance_all_models(summary_yield_cereal_legume_wt_fababean, remove_unused_predictors = TRUE, add_species_mix = TRUE)

ggsave("figures/MERF/figures_summaries_models/plot_yield_cereal_wt_fababean_wt_pea_all_species.png", plot =plot_yield_cereal_wt_fababean_wt_pea_all_species, height = 12, width = 17, unit = "cm")


plot_importance_all_models(list_models_environment, remove_unused_predictors = TRUE)


# figures_summaries_models
invisible(lapply(list_models_environment, fun_save_plot_marginals_models))
```


```{r figures manuscript}

# , "yield_total_wt_pea", "LER_wt_pea"

summary_wt_pea <- c("yield_cereal_wt_pea",  "PLER_cereal_wt_pea","yield_legume_wt_pea", "PLER_legume_wt_pea")

plot_summary_wt_pea <- plot_importance_all_models(summary_wt_pea, remove_unused_predictors = TRUE)
ggsave("figures/MERF/figures_summaries_models/plot_summary_wt_pea.png", plot =plot_summary_wt_pea, height = 12, width = 17, unit = "cm")


file.copy("figures/MERF/figures_summaries_models/plot_summary_wt_pea.png", to  ="C:/Users/rmahmoud/Dropbox/Applications/Overleaf/Manuscrit thèse/chap4_modeling_IC/figures/plot_summary_wt_pea.png", overwrite = TRUE)

# , "yield_total_wt_fababean", "LER_wt_fababean"
summary_wt_fababean <- c("yield_cereal_wt_fababean",  "PLER_cereal_wt_fababean","yield_legume_wt_fababean", "PLER_legume_wt_fababean")
plot_summary_wt_fababean <- plot_importance_all_models(summary_wt_fababean, remove_unused_predictors = TRUE)
ggsave("figures/MERF/figures_summaries_models/plot_summary_wt_fababean.png", plot =plot_summary_wt_fababean, height = 12, width = 17, unit = "cm")


file.copy("figures/MERF/figures_summaries_models/plot_summary_wt_fababean.png", to  ="C:/Users/rmahmoud/Dropbox/Applications/Overleaf/Manuscrit thèse/chap4_modeling_IC/figures/plot_summary_wt_fababean.png", overwrite = TRUE)

# , "yield_total_all_species", "LER_all_species"
summary_all_species <- c("yield_cereal_all_species",  "PLER_cereal_all_species","yield_legume_all_species", "PLER_legume_all_species")
plot_summary_all_species <- plot_importance_all_models(summary_all_species, remove_unused_predictors = TRUE)
ggsave("figures/MERF/figures_summaries_models/plot_summary_all_species.png", plot =plot_summary_all_species, height = 12, width = 17, unit = "cm")


file.copy("figures/MERF/figures_summaries_models/plot_summary_all_species.png", to  ="C:/Users/rmahmoud/Dropbox/Applications/Overleaf/Manuscrit thèse/chap4_modeling_IC/figures/plot_summary_all_species.png", overwrite = TRUE)
```



```{r figure summary soutenance}

summary_yield_wt_pea <- c("yield_cereal_wt_pea",  "yield_legume_wt_pea")

plot_summary_yield_wt_pea <- plot_importance_all_models(summary_yield_wt_pea, remove_unused_predictors = TRUE, size_label = 5) + theme(
          axis.text = element_text(size = 14),
          axis.text.x = element_text(angle = 0), 
          axis.text.y = element_text(size = 16), legend.title = element_text(size=  11), legend.text =element_text(size= 10))
ggsave("C:/Users/rmahmoud/Documents/INRA/These/Soutenance thèse/figures_soutenance/plot_summary_yield_wt_pea.png", plot =plot_summary_yield_wt_pea, height = 14, width = 13, unit = "cm")


summary_yield_wt_fababean <- c("yield_cereal_wt_fababean","yield_legume_wt_fababean")

plot_summary_yield_wt_fababean <- plot_importance_all_models(summary_yield_wt_fababean, remove_unused_predictors = TRUE, size_label = 5) + theme(
          axis.text = element_text(size = 14),
          axis.text.x = element_text(angle = 0), 
          axis.text.y = element_text(size = 16), legend.title = element_text(size=  11), legend.text =element_text(size= 10))
ggsave("C:/Users/rmahmoud/Documents/INRA/These/Soutenance thèse/figures_soutenance/plot_summary_yield_wt_fababean.png", plot =plot_summary_yield_wt_fababean, height = 13, width = 14, unit = "cm")

```


```{r plot bar importance of all models}
get_importance_all_models <- function(list_models){
  
  data_importance <- tibble()
  for(model in list_models){
    
    print(model)
    y_model <- str_extract(model, "N_seed_cereal|yield_cereal|yield_legume|yield_total|PLER_cereal|PLER_legume|LER|BE|CE|SE")
    species_mix <- str_extract(model, "wt_fababean|wt_pea|all_species") 
    
    name_model <- model
    
    model <- get(model, envir = .GlobalEnv)
    
    # name_model = paste(name_model, nrow(model), sep = " - ")
    
    data_importance <- bind_rows(data_importance, format_importance(model, name_model = name_model) %>%
                                   mutate(y = y_model, species_mix = species_mix))
    
    
  }
  return(data_importance)
}



list_models_plot_importance <- c( "LER_all_species", "LER_wt_fababean", "LER_wt_pea", "PLER_cereal_all_species", "PLER_cereal_wt_fababean",
"PLER_cereal_wt_pea", "PLER_legume_all_species", "PLER_legume_wt_fababean", "PLER_legume_wt_pea",  "yield_cereal_all_species", "yield_cereal_wt_fababean", "yield_cereal_wt_pea", "yield_legume_all_species", "yield_legume_wt_fababean", "yield_legume_wt_pea", "yield_total_all_species", "yield_total_wt_fababean", "yield_total_wt_pea")
  
data_importance <- get_importance_all_models(list_models_plot_importance)%>% 
    mutate(species_mix = str_replace_all(species_mix, c("wt_fababean" = "Blé dur / Féverole", "wt_pea" = "Blé dur / Pois", "all_species" = "Toutes espèces"))) %>% 
    mutate(y = str_replace_all(y, c("legume" = "lég", "cereal" = "céréale", "yield" = "Rdt", "_" = " "))) 







size_text <- 10

# tricky way to rename the axes --> no better solution found
set_scale_x_reorder <- function(x, sep = "___"){
  reg <- paste0(sep, ".+$")
  x <- gsub(reg,"", x)
  
  x <- case_when(
    x == 'diff_slope_biomass' ~ parse(text = TeX('$\\Delta \\mu_{biom}$')),
    x == 'NNI_C' ~ parse(text = TeX("$_{NNI}_C$")),
    x == 'NNI_L' ~ parse(text = TeX("$_{NNI}_L$")),
    x == 'cult_C' ~ parse(text = TeX("$_{cult}_C$")),
    x == 'cult_L' ~ parse(text = TeX("$_{cult}_L$")),
    x == "diff_IC_SC_asymp_height_C" ~ parse(text = TeX("$\\Delta_{IC-SC, height, C}$")),
    x == "diff_IC_SC_asymp_height_L" ~ parse(text = TeX("$\\Delta_{IC-SC, height, L}$")),
    x == "diff_IC_SC_max_LAI_C" ~ parse(text = TeX("$\\Delta_{IC-SC, LAI, C}$")),
    x == "diff_IC_SC_max_sla_GLT_C" ~ parse(text = TeX("$\\Delta_{IC-SC, SLA, C}$")),
    x == "diff_IC_SC_max_sla_GLT_L" ~ parse(text = TeX("$\\Delta_{IC-SC, SLA, L}$")),
    x == "diff_IC_SC_max_LAI_L" ~ parse(text = TeX("$\\Delta_{IC-SC, LAI, L}$")),
    x == 'diff_lambda_height' ~  parse(text = TeX('$\\Delta \\lambda_{height}$')),
    x == 'diff_lambda_biomass' ~  parse(text = TeX('$\\Delta \\lambda_{biom}$')),
    x == 'diff_max_LAI' ~ parse(text = TeX('$\\Delta_{max, LAI}$')),
    x == 'diff_max_sla_GLT' ~ parse(text = TeX('$\\Delta_{max, SLA}$')),
    x == 'diff_slope_height' ~ parse(text = TeX('$\\Delta_{\\mu, height}$')),
    x == 'diff_asymp_height' ~ parse(text = TeX('$\\Delta_{max, height}$')),
    x == "diff_IC_SC_slope_height_L" ~ parse(text = TeX("$\\Delta_{IC-SC, \\mu, height, L}$")),
    x == "diff_IC_SC_slope_height_C" ~ parse(text = TeX("$\\Delta_{IC-SC, \\mu, height, C}$")),
    x == "diff_IC_SC_slope_biomass_L" ~ parse(text = TeX("$\\Delta_{IC-SC,\\mu, biom, L}$")),
    x == "diff_IC_SC_slope_biomass_C" ~ parse(text = TeX("$\\Delta_{IC-SC, biom, \\mu, C}$")),
    x == "diff_IC_SC_lambda_height_L" ~ parse(text = TeX("$\\Delta_{IC-SC, \\lambda, height, L}$")),
    x == "diff_IC_SC_lambda_height_C" ~ parse(text = TeX("$\\Delta_{IC-SC, \\lambda, height, C}$")),
    x == "diff_IC_SC_lambda_biomass_L" ~ parse(text = TeX("$\\Delta_{IC-SC, \\lambda, biom, L}$")),
    x == "diff_IC_SC_lambda_biomass_C" ~ parse(text = TeX("$\\Delta_{IC-SC, \\lambda, biom, C}$")),
    x == "density_factor" ~ parse(text = "density"),
    x == 'cover_before_800_normalized_tt'  ~ parse(text = 'cover'),
    x == 'cover_before_800_normalized_tt_SC_C' ~ parse(text = TeX("$\\Delta_{IC-SC, C, cover}$")),
    x == 'cover_before_800_normalized_tt_SC_L' ~ parse(text = TeX("$\\Delta_{IC-SC, L, cover}$")),
    TRUE ~ parse(text = x)
    )
  # diff_asymp_height___Toutes espèces___PLER lég
  
  
  return(x)
}


data_plot <- data_importance %>%
    mutate(variable = tidytext::reorder_within(variable, within = list(species_mix, y ), by = mean_importance ))# Reorder variables within each facet
    # arrange( desc(variable), species_mix, y) %>%

(plot_importance_all_models <- data_plot %>%  
    filter(!str_detect(model, "yield_total|^LER")) %>% 
    mutate(species_mix = str_replace_all(species_mix, c("Toutes espèces" = "Blé dur / légumineuses", "Pois" = "pois", "Féverole" = "féverole"))) %>% 
    mutate(species_mix = fct_relevel(species_mix, "Blé dur / légumineuses", after= Inf)) %>% 
    mutate(y = str_replace(y, "PLER", "pLER")) %>% 
    ggplot(aes(x=variable, mean_importance)) +
    geom_bar(stat = "identity", alpha = .4, aes(fill = sign_cor)) +
    geom_errorbar(aes(ymin = mean_importance -  sd_importance, ymax = mean_importance + sd_importance), width = .5 ) + 
    ylab(TeX("Importance ($\\Delta$ MSE après permutation de la variable)")) +
    xlab(NULL) +
    labs(fill = TeX('Sign $\\tau$ Kendall'), title = NULL) +
    my_scale_fill_correlations() +
    # scale_x_discrete(labels =lapply(data_plot$variable, set_scale_x_reorder)) + 
    scale_x_discrete(labels =function(x) set_scale_x_reorder(x)) + 
    ggh4x::facet_grid2(y ~species_mix, independent = "all", scales = "free") + 
    theme(legend.position = "bottom",
          axis.text.y = element_text(angle = 60, hjust = 0.5,size = size_text),
          title = element_text(size = size_text),
          legend.text = element_text(size = size_text ),
          legend.title = element_text(size = size_text ),
          axis.title = element_text(size = size_text),
          strip.text = element_text(size = size_text - 1),
          axis.text.x = element_text(size = size_text - 4)) +
    coord_flip() )


ggsave(filename = "figures/MERF/plot_importance_all_models.png", plot =plot_importance_all_models, height = 21, width = 20, unit = "cm")

file.copy("figures/MERF/plot_importance_all_models.png", to  ="C:/Users/rmahmoud/Dropbox/Applications/Overleaf/Manuscrit thèse/chap4_modeling_IC/figures/plot_importance_all_models.png", overwrite = TRUE)

```



# Importance models N_seed


```{r}
read_and_assign <- function(path, name_to_assign_suffix = NULL, filter_iterations = TRUE) {
  model <- read_rds(path)  %>% 
    mutate(n_iterations = map_dbl(mod.MERF, ~length(.x$vraisemblance))) %>% 
    mutate(mod.MERF = map2(mod.MERF, data, add_data_to_mod.MERF))
  

  name_to_assign <- unlist(stringr::str_split(path, "\\."))[1]
  name_to_assign <- stringr::str_remove(name_to_assign, "models/N_seed/wt_pea/|models/N_seed/wt_fababean/|models/N_seed/all_species/" )
  
  
  
  if(filter_iterations){
    
    # model <- model
    
    any_not_converged <- max(model$n_iterations) %in% c(1000,3000)
    
      print(paste(name_to_assign, "max iterations" , max(model$n_iterations)))
      model <- model %>%
        mutate(any_not_converged = any_not_converged) %>% 
        filter( (n_iterations < max(n_iterations) & any_not_converged) | (!any_not_converged)) %>% 
        select(-any_not_converged)

  }
  
  
  if(!is.null(name_to_assign_suffix)){name_to_assign = paste(name_to_assign, name_to_assign_suffix, sep = "_")}
  if(nrow(model)>0){assign(x = name_to_assign,  value = model, envir = .GlobalEnv)}
}



list_models <-  grep(list.files("models/N_seed", recursive = TRUE, full.names = TRUE), pattern='models_train', invert=TRUE, value=TRUE)
function_read_all_model(list_paths = list_models)


# 
list_models_environment <- str_remove_all(list_models, "models/N_seed/wt_pea/|models/N_seed/all_species/|models/N_seed/wt_fababean/|.rds")


data_importance <- get_importance_all_models(list_models_environment)%>% 
    mutate(species_mix = str_replace_all(species_mix, c("wt_fababean" = "Blé dur / féverole", "wt_pea" = "Blé dur / pois", "all_species" = "Blé dur / légumineuses")))  %>% 
    mutate(species_mix = fct_relevel(species_mix, "Blé dur / légumineuses", after= Inf)) %>% 
    mutate(y = str_replace_all(y, c("legume" = "lég", "cereal" = "blé dur", "yield" = "Rdt", "_" = " "))) 



data_plot <- data_importance %>%
    mutate(variable = tidytext::reorder_within(variable, within = list(species_mix, y ), by = mean_importance ))# Reorder variables within each facet
    # arrange( desc(variable), species_mix, y) %>%

size_text <- 11
(plot_importance_all_models <- data_plot %>%  # Turn again into vartiable factor
    ggplot(aes(x=variable, mean_importance)) +
    geom_bar(stat = "identity", alpha = .4, aes(fill = sign_cor)) +
    geom_errorbar(aes(ymin = mean_importance -  sd_importance, ymax = mean_importance + sd_importance), width = .5 ) + 
    ylab(TeX("Importance ($\\Delta$ MSE après permutation de la variable)")) +
    xlab(NULL) +
    labs(fill = TeX('Sign $\\tau$ Kendall'), title = NULL) +
    my_scale_fill_correlations() +
    # scale_x_discrete(labels =lapply(data_plot$variable, set_scale_x_reorder)) + 
    scale_x_discrete(labels =function(x) set_scale_x_reorder(x)) + 
    ggh4x::facet_grid2( ~species_mix, independent = "all", scales = "free") + 
    theme(legend.position = "bottom",
          axis.text.y = element_text(angle = 60, hjust = 0.5,size = size_text +1),
          title = element_text(size = size_text),
          legend.text = element_text(size = size_text ),
          legend.title = element_text(size = size_text ),
          axis.title = element_text(size = size_text),
          strip.text = element_text(size = 12),
          axis.text.x = element_text(size = size_text - 3)) +
    coord_flip() )



ggsave(filename = "figures/N_seed/plot_importance_all_models_N_seed.png", plot =plot_importance_all_models, height = 8, width = 20, unit = "cm")

file.copy("figures/N_seed/plot_importance_all_models_N_seed.png", to  ="C:/Users/rmahmoud/Dropbox/Applications/Overleaf/Manuscrit thèse/chap4_modeling_IC/figures/plot_importance_all_models_N_seed.png", overwrite = TRUE)

```



# Transfer plots



```{r}
# 
# folder_modeling <- "C:/Users/rmahmoud/Documents/INRA/These/R_projects_phD/paper_modeling_intercrop/figures"
# folder_presentations <- "C:/Users/rmahmoud/Documents/INRA/These/Presentations/meeting_22_11_2022/presentation_figures"
# list_of_files <- list.files(folder_modeling, "(.*)marginal(.*).png$",recursive = TRUE, full.names = TRUE) 
# 
# file.copy(file.path(list_of_files), folder_presentations, overwrite = TRUE)
```

