---
title: "Run models wheat turgidum pea"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r, include = FALSE, message=F}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = F,
  warning = F,
  message = F
)

```

```{r}

library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)


# Modeling
library(nlme)
library(randomForest)
library(Boruta)

theme_set(theme_bw())

# library(sjmisc)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")


```


```{r functions}
# Read all functions
list_functions <- list.files("R/scripts_functions", full.names = TRUE)
invisible(lapply(list_functions, source))

#wrapper around gmerf

fun_call_gmerf_modified <- function(data, y = "yield_cereal", group = "experiment_id", max_iterations = 200, toll_param = 0.02, verbose_param = FALSE){
  return(gmerf_modified(y = data[[y]],  cov = data %>% select(-any_of(y), -any_of(group)), group = as.factor(data[[group]]), family = "gaussian", itmax = max_iterations, weights = varIdent(form = ~1|group), control_lme = list(msMaxIter = 1000, msMaxEval = 1000, opt = "optim"), toll = toll_param,verbose = verbose_param)) 
}

fun_fitted_gmerf_modified <- function(gm, data, y="yield_cereal"){
  
  fitted_values <- gm %>% fitted.gmerf(type = "mu")
  data_gmerf_fit_vs_obs <- tibble(observed = data[[y]], fitted = fitted_values)

  return(data_gmerf_fit_vs_obs)
}

```


```{r}
data_all_diff <-  read_rds( "data/data_all_diff_with_imputations.rds")


data_NNI <- read_rds("data/data_NNI.rds") %>%
  inner_join(data_all_diff %>% distinct(experiment_id, management)) %>%
  left_join(data.intercrop::index %>% distinct(experiment_id, management, harvest_date)) %>% 
  filter(date== harvest_date) %>% 
  select(experiment_id, management, plant_family, NNI = NNI_bedou) %>% 
  pivot_wider(values_from = NNI, names_from = plant_family, names_prefix = "NNI_") %>% 
  shorten_exp_id()

data_diff_wt_pea <- data_all_diff%>%
  left_join(data.intercrop::index %>% distinct(experiment_id, management, species_mix)) %>%
  filter(species_mix== "wheat_turgidum_pea") %>%
  shorten_exp_id()


index <- data.intercrop::index %>% 
  shorten_exp_id()%>%
  inner_join(data_diff_wt_pea %>% distinct(experiment_id, management) ) 


yield_cereal_wt_pea <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "cereal") %>%
  inner_join(data_diff_wt_pea %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_cereal = value)

```

```{r tests imputation NNI}

# data_NNI %>% left_join(data.intercrop::index %>% shorten_exp_id %>% distinct(management, experiment_id, species_mix))%>% 
#   ggplot(aes(x = NNI_legume, y = NNI_cereal))  + geom_point(aes(shape = species_mix)) + naniar::geom_miss_point() + facet_wrap(species_mix~., scales= "free")

data_impute_NNI <- data_NNI %>% left_join(data.intercrop::index %>% shorten_exp_id %>% distinct(management, experiment_id, species_mix)) %>% mutate(species_mix = as.factor(species_mix))


# mod.jointAI <- JointAI::lm_imp(NNI_cereal~NNI_legume + species_mix, data = as.data.frame(data_impute_NNI), n.iter = 2000, monitor_params = c(imps = TRUE))
# 
# library(JointAI)
# traceplot(mod.jointAI)
# summary(mod.jointAI)
# 
# get_MIdat(mod.jointAI, m = 10, include = FALSE) %>% 
#   as_tibble() %>% 
#   rename(.imp = Imputation_) %>%
#   left_join(data_NNI %>% rename(NNI_cereal_raw = NNI_cereal)) %>% 
#   mutate(imputed= is.na(NNI_cereal_raw)) %>% 
#   left_join(data.intercrop::index %>% shorten_exp_id %>% distinct(management, experiment_id, species_mix))%>% 
#   ggplot(aes(x = NNI_legume, y = NNI_cereal))  + geom_point(aes(shape = species_mix, color = imputed)) +  facet_wrap(species_mix~., scales= "free")

library(mice)

pred <- make.predictorMatrix(data_impute_NNI)
pred[, c("experiment_id", "management")] <- 0


# mids <- mice(data = data_impute_NNI, predictorMatrix = pred, method = "pmm", m = 10, printFlag = FALSE, donors = 2L)
mids <- mice(data = data_impute_NNI, predictorMatrix = pred, method = "norm", m = 10, printFlag = FALSE)


 # mids%>% complete(action = "long") %>% as_tibble() %>%
 #  left_join(data_NNI %>% rename(NNI_cereal_raw = NNI_cereal)) %>% 
 #  mutate(imputed= is.na(NNI_cereal_raw)) %>% 
 #  # left_join(data.intercrop::index %>% shorten_exp_id %>% distinct(management, experiment_id, species_mix))%>% 
 #  ggplot(aes(x = NNI_legume, y = NNI_cereal))  + geom_point(aes(shape = species_mix, color = imputed)) +  facet_wrap(species_mix~., scales= "free")

 
data_NNI_imputed <-mids%>% complete(action = "long") %>% as_tibble() %>% select(-.id) %>% inner_join(data_diff_wt_pea %>% distinct(.imp, experiment_id, management) )
```

# Model yield cereal


```{r}

itk_wt_pea <- index %>% distinct(experiment_id, management, cultivar_mix, N_amount, mixing_pattern, mixture_design,  density_factor ) %>% 
  separate(cultivar_mix, into = c("cult_cereal", "cult_legume"), sep = "_") %>% 
  mutate(N_fertilisation= ifelse(N_amount == 0, "Yes", "No"),
         N_level = case_when(N_amount ==0 ~ "Unfertilized",
                             between(N_amount, 60,100) ~ "Medium",
                             TRUE~"High"))

```


```{r}


# Relevant features

covariates <- c( "diff_IC_SC_asymp_height_cereal", "diff_IC_SC_lambda_biomass_cereal", "diff_IC_SC_lambda_height_cereal", "diff_IC_SC_slope_biomass_cereal", "diff_IC_SC_slope_height_cereal",  "diff_asymp_height","diff_lambda_biomass", "diff_lambda_height", "diff_max_LAI", "diff_max_sla_GLT", "diff_slope_biomass", "diff_slope_height", "diff_IC_SC_max_LAI_cereal", "diff_IC_SC_max_sla_GLT_cereal", "cover_before_800_normalized_tt", "cover_before_800_normalized_tt_SC_cereal", "NNI_cereal",  "yield_cereal")

itk_covariates <- c("cult_cereal", "cult_legume")

data_wt_pea <- data_diff_wt_pea %>% 
  left_join(yield_cereal_wt_pea) %>% 
  left_join(itk_wt_pea) %>% 
  left_join(data_NNI_imputed) %>% 
  select(.imp, experiment_id, management, any_of(covariates), any_of(itk_covariates))

data_wt_pea_nested <- data_wt_pea %>% 
  group_by(.imp) %>% 
  nest() %>% 
  ungroup

```



```{r}
models_yield_cereal_wt_pea <- data_wt_pea_nested %>% 
  filter(.imp == 1) %>% 
  mutate(mod.gmerf = map(data, fun_call_gmerf_modified, verbose_param = TRUE)) 

# fun_fitted_gmerf_modified(models_yield_cereal_wt_pea$mod.gmerf[[1]], data = data_wt_pea_nested$data[[1]]) %>% 
#   ggplot(aes(x = observed, y = fitted)) + 
#   geom_point() + 
#   geom_y_x()
# 
# models_yield_cereal_wt_pea$mod.gmerf[[1]]$n.iteration

```


```{r}




```

