---
title: "Run all models MERF LongituRF"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r, include = FALSE, message=F}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = F,
  warning = F,
  message = F
)

```

```{r}

library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)


# Modeling
library(nlme)
library(randomForest)
library(Boruta)

theme_set(theme_bw())

# library(sjmisc)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")


```


```{r functions}
# Read all functions
list_functions <- list.files("R/scripts_functions", full.names = TRUE)

list_functions <- c("R/scripts_functions/functions_tools.R")
invisible(lapply(list_functions, source))

#wrapper around gmerf

# fun_call_MERF_modified <- function(data, y = "yield_cereal", group = "experiment_id", max_iterations = 200, toll_param = 0.02, verbose_param = FALSE, list_control_lme = list(msMaxIter = 1000, msMaxEval = 1000, opt = "optim"), weights_lme = varIdent(form = ~1|group) ){
#   return(gmerf_modified(y = data[[y]],  cov = data %>% select(-any_of(y), - management, -any_of(group)), group = as.factor(data[[group]]), family = "gaussian", itmax = max_iterations, weights = weights_lme, control_lme = list_control_lme, toll = toll_param,verbose = verbose_param)) 
# }
# 
# 
# fun_call_MERF_modified <- function(data, y = "yield_cereal", group = "experiment_id", max_iterations = 200, toll_param = 0.0001, verbose_param = FALSE ){
#   
#    return(MERF_modified(X =  as.data.frame(data %>% select(-any_of(y), - management, -any_of(group))), Y =  data[[y]], id = data[[group]], Z = as.matrix(rep(1, nrow(data))), time = rep(1,nrow(data)),  iter = max_iterations, verbose = verbose_param, delta= toll_param))
# }


nest_data_by_imp <- function(data){return(data %>% group_by(.imp) %>% nest() %>% ungroup)}

```


```{r}
data_all_diff <-  read_rds( "data/data_all_diff_with_imputations.rds") %>% filter(experiment_id %in% c("Auzeville_TO_2013", "Auzeville_ZN_2012"))

data_BE_CE_SE <- read_rds("data/data_BE_CE_SE_LER.rds") %>% filter(experiment_id %in% c("Auzeville_TO_2013", "Auzeville_ZN_2012"))

data_NNI <- read_rds("data/data_NNI.rds") %>%
  inner_join(data_all_diff %>% distinct(experiment_id, management)) %>% 
  shorten_exp_id()

data_diff_wt_fababean <- data_all_diff%>%
  left_join(data.intercrop::index %>% distinct(experiment_id, management, species_mix)) %>%
  filter(species_mix== "wheat_turgidum_fababean") %>%
  shorten_exp_id()


index <- data.intercrop::index %>% 
  shorten_exp_id()%>%
  inner_join(data_diff_wt_fababean %>% distinct(experiment_id, management) ) 


```


# Set data all species



```{r}

set.seed(2022)


data_diff_all_species <- data_all_diff%>%
  left_join(data.intercrop::index %>% distinct(experiment_id, management, species_mix)) %>%
  shorten_exp_id()



subset_train_all_species <- data_diff_all_species %>%
  distinct(experiment_id, management) %>%
  group_by(experiment_id) %>%
  slice_sample(prop = 3/4 ) %>%
  ungroup


index_all_species <- data.intercrop::index %>% 
  shorten_exp_id()%>%
  inner_join(data_diff_all_species %>% distinct(experiment_id, management) ) 

itk_all_species <- index_all_species %>% distinct(experiment_id, management, species_mix, cultivar_mix, N_amount, mixing_pattern, mixture_design,  density_factor ) %>% 
  separate(cultivar_mix, into = c("cult_cereal", "cult_legume"), sep = "_") %>% 
  mutate(legume = str_extract(species_mix, "pea|fababean")) %>% 
  select(-species_mix)



```


# Model yield cereal all species

## Yield



```{r}

# Relevant features

yield_cereal_all_species <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "cereal") %>%
  inner_join(data_diff_all_species %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_cereal = value)


covariates_cereal <- c( "diff_IC_SC_asymp_height_cereal", "diff_IC_SC_lambda_biomass_cereal", "diff_IC_SC_lambda_height_cereal", "diff_IC_SC_slope_biomass_cereal", "diff_IC_SC_slope_height_cereal",  "diff_asymp_height","diff_lambda_biomass", "diff_lambda_height", "diff_max_LAI", "diff_max_sla_GLT", "diff_slope_biomass", "diff_slope_height", "diff_IC_SC_max_LAI_cereal", "diff_IC_SC_max_sla_GLT_cereal", "NNI_cereal",  "yield_cereal")

itk_covariates <- c("cult_cereal", "cult_legume", "legume")

data_all_species <- data_diff_all_species %>% 
  left_join(yield_cereal_all_species) %>% 
  left_join(itk_all_species) %>% 
  left_join(data_NNI)%>% 
  inner_join(subset_train_all_species) %>%
  select(.imp, experiment_id, management, any_of(covariates_cereal), any_of(itk_covariates))

data_test_all_species <- data_diff_all_species %>% 
  left_join(yield_cereal_all_species) %>% 
  left_join(itk_all_species) %>% 
  left_join(data_NNI) %>% 
  anti_join(subset_train_all_species) %>%
  select(.imp, experiment_id, management, any_of(covariates_cereal), any_of(itk_covariates)) %>% 
  nest_data_by_imp() %>%
  rename(data_test = data)

data_all_species_nested <- data_all_species %>% nest_data_by_imp  %>% left_join(data_test_all_species) 



```

```{r}
# 
# mod.Boruta <- Boruta(x =data_all_species_nested$data[[1]][,c(covariates_cereal[-length(covariates_cereal)], itk_covariates, "experiment_id")], y=  data_all_species_nested$data[[1]]$yield_cereal)
# 
# attributes_boruta <- mod.Boruta %>% getSelectedAttributes()
# 
# mod.rf <- randomForest(x =data_all_species_nested$data[[1]][,c(attributes_boruta)], y=  data_all_species_nested$data[[1]]$yield_cereal)
# 
# mod.rf$importance

fun_boruta_rf <- function(data, y = "yield_cereal", group = "experiment_id" ){
    
  
  data_X = as.data.frame(data %>% select(-any_of(y), - management))
  data_Y = data[[y]]
  
  mod.boruta <- Boruta(x =data_X, y=  data_Y)
  
  mod.rf <- randomForest(x =as.data.frame(data %>% select(getSelectedAttributes(mod.boruta))), y=  data_Y)
  # if(length(getSelectedAttributes(mod.boruta)))

   return(mod.rf)
}



fun_boruta_rf(data_all_species_nested$data[[1]])


```


```{r, eval = FALSE}
models_yield_cereal_all_species <- data_all_species_nested %>% 
  mutate(mod.MERF =  map(data, fun_boruta_rf)) 

```

```{r, eval = FALSE}

write_rds(models_yield_cereal_all_species, "models/Auz_2012_2013/yield_cereal_all_species.rds")


```

## PLER


```{r}

# Relevant features

PLER_cereal_all_species <- data_BE_CE_SE %>%
  shorten_exp_id() %>% 
  inner_join(data_diff_all_species %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, PLER_cereal) 


covariates_cereal <- c( "diff_IC_SC_asymp_height_cereal", "diff_IC_SC_lambda_biomass_cereal", "diff_IC_SC_lambda_height_cereal", "diff_IC_SC_slope_biomass_cereal", "diff_IC_SC_slope_height_cereal",  "diff_asymp_height","diff_lambda_biomass", "diff_lambda_height", "diff_max_LAI", "diff_max_sla_GLT", "diff_slope_biomass", "diff_slope_height", "diff_IC_SC_max_LAI_cereal", "diff_IC_SC_max_sla_GLT_cereal", "NNI_cereal",  "PLER_cereal")

itk_covariates <- c("cult_cereal", "cult_legume", "legume")

data_all_species <- data_diff_all_species %>% 
  left_join(PLER_cereal_all_species) %>% 
  left_join(itk_all_species) %>% 
  left_join(data_NNI)%>% 
  inner_join(subset_train_all_species) %>%
  select(.imp, experiment_id, management, any_of(covariates_cereal), any_of(itk_covariates))

data_test_all_species <- data_diff_all_species %>% 
  left_join(PLER_cereal_all_species) %>% 
  left_join(itk_all_species) %>% 
  left_join(data_NNI) %>% 
  anti_join(subset_train_all_species) %>%
  select(.imp, experiment_id, management, any_of(covariates_cereal), any_of(itk_covariates)) %>% 
  nest_data_by_imp() %>%
  rename(data_test = data)

data_all_species_nested <- data_all_species %>% nest_data_by_imp  %>% left_join(data_test_all_species) 




```



```{r, eval = FALSE}
models_PLER_cereal_all_species <- data_all_species_nested %>% 
  mutate(mod.MERF =  map(data, fun_boruta_rf, y = "PLER_cereal")) 

```

```{r, eval = FALSE}

write_rds(models_PLER_cereal_all_species, "models/Auz_2012_2013/PLER_cereal_all_species.rds")


```



# Model yield legume all species


## Yield

```{r}

# Relevant features

yield_legume_all_species <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "legume") %>%
  inner_join(data_diff_all_species %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_legume = value)


covariates_legume <- c( "diff_IC_SC_asymp_height_legume", "diff_IC_SC_lambda_biomass_legume", "diff_IC_SC_lambda_height_legume", "diff_IC_SC_slope_biomass_legume", "diff_IC_SC_slope_height_legume",  "diff_asymp_height","diff_lambda_biomass", "diff_lambda_height", "diff_max_LAI", "diff_max_sla_GLT", "diff_slope_biomass", "diff_slope_height", "diff_IC_SC_max_LAI_legume", "diff_IC_SC_max_sla_GLT_legume", "NNI_legume",  "yield_legume")

itk_covariates <- c("cult_legume", "cult_legume", "legume")

data_all_species <- data_diff_all_species %>% 
  left_join(yield_legume_all_species) %>% 
  left_join(itk_all_species) %>% 
  left_join(data_NNI)%>% 
  inner_join(subset_train_all_species) %>%
  select(.imp, experiment_id, management, any_of(covariates_legume), any_of(itk_covariates))

data_test_all_species <- data_diff_all_species %>% 
  left_join(yield_legume_all_species) %>% 
  left_join(itk_all_species) %>% 
  left_join(data_NNI) %>% 
  anti_join(subset_train_all_species) %>%
  select(.imp, experiment_id, management, any_of(covariates_legume), any_of(itk_covariates)) %>% 
  nest_data_by_imp() %>%
  rename(data_test = data)

data_all_species_nested <- data_all_species %>% nest_data_by_imp  %>% left_join(data_test_all_species) 



```



```{r, eval = FALSE}
models_yield_legume_all_species <- data_all_species_nested %>% 
  mutate(mod.MERF =  map(data, fun_boruta_rf, y = "yield_legume")) 

```

```{r, eval = FALSE}

write_rds(models_yield_legume_all_species, "models/Auz_2012_2013/yield_legume_all_species.rds")


```


## PLER


```{r}

# Relevant features

PLER_legume_all_species <- data_BE_CE_SE %>%
  shorten_exp_id() %>% 
  inner_join(data_diff_all_species %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, PLER_legume) 


covariates_legume <- c( "diff_IC_SC_asymp_height_legume", "diff_IC_SC_lambda_biomass_legume", "diff_IC_SC_lambda_height_legume", "diff_IC_SC_slope_biomass_legume", "diff_IC_SC_slope_height_legume",  "diff_asymp_height","diff_lambda_biomass", "diff_lambda_height", "diff_max_LAI", "diff_max_sla_GLT", "diff_slope_biomass", "diff_slope_height", "diff_IC_SC_max_LAI_legume", "diff_IC_SC_max_sla_GLT_legume", "NNI_legume",  "PLER_legume")

itk_covariates <- c("cult_legume", "cult_legume", "legume")

data_all_species <- data_diff_all_species %>% 
  left_join(PLER_legume_all_species) %>% 
  left_join(itk_all_species) %>% 
  left_join(data_NNI)%>% 
  inner_join(subset_train_all_species) %>%
  select(.imp, experiment_id, management, any_of(covariates_legume), any_of(itk_covariates))

data_test_all_species <- data_diff_all_species %>% 
  left_join(PLER_legume_all_species) %>% 
  left_join(itk_all_species) %>% 
  left_join(data_NNI) %>% 
  anti_join(subset_train_all_species) %>%
  select(.imp, experiment_id, management, any_of(covariates_legume), any_of(itk_covariates)) %>% 
  nest_data_by_imp() %>%
  rename(data_test = data)

data_all_species_nested <- data_all_species %>% nest_data_by_imp  %>% left_join(data_test_all_species) 




```



```{r, eval = FALSE}
models_PLER_legume_all_species <- data_all_species_nested %>% 
  mutate(mod.MERF =  map(data, fun_boruta_rf, y = "PLER_legume")) 

```

```{r, eval = FALSE}

write_rds(models_PLER_legume_all_species, "models/Auz_2012_2013/PLER_legume_all_species.rds")


```

# Model yield total all species

## Yield

```{r}

# Relevant features


yield_cereal_all_species <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "cereal") %>%
  inner_join(data_diff_all_species %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_cereal = value)

yield_legume_all_species <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "legume") %>%
  group_by(experiment_id, management) %>% 
  summarise(value = max(value), .groups = "drop") %>%  #get maximal value of the yield for management M36 as it is measured twice
  inner_join(data_diff_all_species %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_legume = value)


yield_total_all_species <- yield_legume_all_species %>%
  left_join(yield_cereal_all_species) %>% 
  mutate(yield_total = yield_legume + yield_cereal) %>%
  distinct(experiment_id, management, yield_total) 



covariates_cereal <- c( "diff_IC_SC_asymp_height_cereal", "diff_IC_SC_lambda_biomass_cereal", "diff_IC_SC_lambda_height_cereal", "diff_IC_SC_slope_biomass_cereal", "diff_IC_SC_slope_height_cereal",  "diff_asymp_height","diff_lambda_biomass", "diff_lambda_height", "diff_max_LAI", "diff_max_sla_GLT", "diff_slope_biomass", "diff_slope_height", "diff_IC_SC_max_LAI_cereal", "diff_IC_SC_max_sla_GLT_cereal", "NNI_cereal",  "yield_cereal")


covariates_legume <- c( "diff_IC_SC_asymp_height_legume", "diff_IC_SC_lambda_biomass_legume", "diff_IC_SC_lambda_height_legume", "diff_IC_SC_slope_biomass_legume", "diff_IC_SC_slope_height_legume",  "diff_asymp_height","diff_lambda_biomass", "diff_lambda_height", "diff_max_LAI", "diff_max_sla_GLT", "diff_slope_biomass", "diff_slope_height", "diff_IC_SC_max_LAI_legume", "diff_IC_SC_max_sla_GLT_legume", "NNI_legume",  "yield_legume")


covariates_total <- unique(c( covariates_legume[!grepl("yield_legume|cover_before_800_normalized_tt_SC_legume", covariates_legume)], covariates_cereal[!grepl("yield_cereal|cover_before_800_normalized_tt_SC_cereal", covariates_cereal)],  "yield_total")) 

itk_covariates <- c("cult_cereal", "cult_legume", "legume")

data_all_species <- data_diff_all_species %>% 
  left_join(yield_total_all_species) %>% 
  left_join(itk_all_species) %>% 
  left_join(data_NNI) %>% 
  mutate(across(matches("experiment_id|cult"), as.factor)) %>% 
  select(.imp, experiment_id, management, any_of(covariates_total), any_of(itk_covariates))

data_all_species_nested <- data_all_species %>% nest_data_by_imp

```



```{r, eval = FALSE}
models_yield_total_all_species <- data_all_species_nested %>% 
  mutate(mod.MERF =  map(data, fun_call_MERF_modified, verbose_param = TRUE, y = "yield_total", max_iterations=  3000)) 

```



```{r, eval = FALSE}

write_rds(models_yield_total_all_species, "models/MERF/all_species/yield_total_all_species.rds")


```

## LER



```{r}

# Relevant features


LER_all_species <-  data_BE_CE_SE %>%
  shorten_exp_id() %>% 
  inner_join(data_diff_all_species %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, LER) 

covariates_total <- unique(c( covariates_legume[!grepl("yield_legume", covariates_legume)], covariates_cereal[!grepl("yield_cereal", covariates_cereal)],  "LER")) 

itk_covariates <- c("cult_cereal", "cult_legume", "legume")

data_all_species <- data_diff_all_species %>% 
  left_join(LER_all_species) %>% 
  left_join(itk_all_species) %>% 
  left_join(data_NNI) %>% 
  mutate(across(matches("experiment_id|cult"), as.factor)) %>% 
  select(.imp, experiment_id, management, any_of(covariates_total), any_of(itk_covariates))

data_all_species_nested <- data_all_species %>% nest_data_by_imp

```



```{r, eval = FALSE}
models_LER_all_species <- data_all_species_nested %>% 
  mutate(mod.MERF =  map(data, fun_call_MERF_modified, verbose_param = TRUE, y = "LER", max_iterations=  1000)) 

```



```{r, eval = FALSE}

write_rds(models_LER_all_species, "models/MERF/all_species/LER_all_species.rds")


```



## Biodiversity effects all species


### BE

```{r}

# Relevant features


BE_all_species <- data_BE_CE_SE %>%
  shorten_exp_id() %>% 
  inner_join(data_diff_all_species %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, BE) 

covariates_total <- unique(c( covariates_legume[!grepl("yield_legume", covariates_legume)], covariates_cereal[!grepl("yield_cereal", covariates_cereal)],  "BE")) 

itk_covariates <- c("cult_cereal", "cult_legume", "legume")

data_all_species <- data_diff_all_species %>% 
  left_join(BE_all_species) %>% 
  left_join(itk_all_species) %>% 
  left_join(data_NNI) %>% 
  mutate(across(matches("experiment_id|cult"), as.factor)) %>% 
  select(.imp, experiment_id, management, any_of(covariates_total), any_of(itk_covariates))

data_all_species_nested <- data_all_species %>% nest_data_by_imp

```



```{r, eval = FALSE}
models_BE_all_species <- data_all_species_nested %>% 
  mutate(mod.MERF =  map(data, fun_call_MERF_modified, verbose_param = TRUE, y = "BE", max_iterations = 3000)) 

```



```{r, eval = FALSE}

write_rds(models_BE_all_species, "models/MERF/all_species/BE_all_species.rds")


```


### CE


```{r}

# Relevant features


CE_all_species <- data_BE_CE_SE %>%
  shorten_exp_id() %>% 
  inner_join(data_diff_all_species %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, CE) 

covariates_total <- unique(c( covariates_legume[!grepl("yield_legume", covariates_legume)], covariates_cereal[!grepl("yield_cereal", covariates_cereal)],  "CE")) 

itk_covariates <- c("cult_cereal", "cult_legume", "legume")

data_all_species <- data_diff_all_species %>% 
  left_join(CE_all_species) %>% 
  left_join(itk_all_species) %>% 
  left_join(data_NNI) %>% 
  mutate(across(matches("experiment_id|cult"), as.factor)) %>% 
  select(.imp, experiment_id, management, any_of(covariates_total), any_of(itk_covariates))

data_all_species_nested <- data_all_species %>% nest_data_by_imp

```



```{r, eval = FALSE}
models_CE_all_species <- data_all_species_nested %>% 
  mutate(mod.MERF =  map(data, fun_call_MERF_modified, verbose_param = TRUE, y = "CE", max_iterations = 1000)) 

```


```{r, eval = FALSE}

write_rds(models_CE_all_species, "models/MERF/all_species/CE_all_species.rds")


```




### SE


```{r}

# Relevant features


SE_all_species <- data_BE_CE_SE %>%
  shorten_exp_id() %>% 
  inner_join(data_diff_all_species %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, SE) 

covariates_total <- unique(c( covariates_legume[!grepl("yield_legume", covariates_legume)], covariates_cereal[!grepl("yield_cereal", covariates_cereal)],  "SE")) 

itk_covariates <- c("cult_cereal", "cult_legume", "legume")

data_all_species <- data_diff_all_species %>% 
  left_join(SE_all_species) %>% 
  left_join(itk_all_species) %>% 
  left_join(data_NNI) %>% 
  mutate(across(matches("experiment_id|cult"), as.factor)) %>% 
  select(.imp, experiment_id, management, any_of(covariates_total), any_of(itk_covariates))

data_all_species_nested <- data_all_species %>% nest_data_by_imp

```


```{r, eval = FALSE}
models_SE_all_species <- data_all_species_nested %>% 
  mutate(mod.MERF =  map(data, fun_call_MERF_modified, verbose_param = TRUE, y = "SE", max_iterations = 1000))  


write_rds(models_SE_all_species, "models/MERF/all_species/SE_all_species.rds")


```























