---
title: "Plot models LongituRF"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r, include = FALSE, message=F}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = F,
  warning = F,
  message = F
)

```

```{r}

library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)
library(forcats)

library(LongituRF)


library(patchwork)
library(latex2exp)

# Modeling
library(nlme)


library(latex2exp)

# theme_set(theme_bw())

# theme_set(ggthemes::theme_solarized() + theme(title = element_text(color = "black"), legend.text = element_text(color = "black"), axis.text = element_text(color = "black")))



theme_set(theme_bw()+ 
   theme(axis.title = element_text(size = 16),
         legend.title = element_text(size = 12),
         axis.text = element_text(size=  14),
         legend.text = element_text(size=  12 ),
         strip.text = element_text(size= 12),
         legend.position = "bottom"))
# ggthemr::ggthemr(palette = "dust")
# ggthemr::swatch()

# library(sjmisc)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")


```


```{r functions}
# Read all functions
list_functions <- list.files("R/scripts_functions", full.names = TRUE)

list_functions <- c("R/scripts_functions/function_gmerf_modified.R", "R/scripts_functions/functions_analysis_models_MERF.R", "R/scripts_functions/functions_evaluate_errors.R",
                    "R/scripts_functions/functions_LongituRF_modified.R", "R/scripts_functions/functions_tools.R")

invisible(lapply(list_functions, source))


```




```{r}
format_importance <- function(data_models, name_model = NULL){
  
  n_models <- length(unique(data_models$.imp))
  
  
  if(is.null(name_model)){name_model <-deparse(substitute(data_models))}
  
  data_output <-  get_importance(data_models) %>% 
    filter(n >= n_models) %>% 
    arrange(desc(mean_importance)) %>% 
    mutate(rank = 1:n(), model = name_model) %>% 
    distinct(variable, mean_importance, rank, sign_cor, model )  

  return(data_output)
}
```



```{r}
my_scale_y <- function(drop_val = FALSE){return(scale_y_discrete(labels=c('diff_slope_biomass'=parse(text = TeX('$\\Delta \\mu_{biom}$')),
                                   "diff_IC_SC_asymp_height_C" = parse(text = TeX("$\\Delta_{IC-SC, C, height}$")),
                                   "diff_IC_SC_asymp_height_L" = parse(text = TeX("$\\Delta_{IC-SC, L, height}$")),
                                   "diff_IC_SC_asymp_biomass_C" = parse(text = TeX("$\\Delta_{IC-SC, C, biomass}$")),
                                   "diff_IC_SC_asymp_biomass_L" = parse(text = TeX("$\\Delta_{IC-SC, L, biomass}$")),
                                   "diff_IC_SC_max_LAI_C" = parse(text = TeX("$\\Delta_{IC-SC, C, LAI}$")),
                                   "diff_IC_SC_max_LAI_L" = parse(text = TeX("$\\Delta_{IC-SC, L, LAI}$")),
                                   "diff_IC_SC_max_sla_GLT_C" = parse(text = TeX("$\\Delta_{IC-SC, C, SLA}$")),
                                   "diff_IC_SC_max_sla_GLT_L" = parse(text = TeX("$\\Delta_{IC-SC, L, SLA}$")),
                                   'diff_lambda_height'=parse(text = TeX('$\\Delta_{\\lambda, height}$')),
                                   'diff_lambda_biomass'=parse(text = TeX('$\\Delta_{\\lambda, biom}$')),
                                   'diff_max_LAI' = parse(text = TeX('$\\Delta_{max, LAI}$')), 
                                   'diff_max_sla_GLT' = parse(text = TeX('$\\Delta_{max, SLA}$')), 
                                   'diff_slope_height'=parse(text = TeX('$\\Delta_{\\mu, height}$')),
                                   'diff_asymp_height'=parse(text = TeX('$\\Delta_{max, height}$')),
                                   "diff_IC_SC_slope_height_L" = parse(text = TeX("$\\Delta_{IC-SC, \\mu, height, L}$")),
                                   "diff_IC_SC_slope_height_C" = parse(text = TeX("$\\Delta_{IC-SC, \\mu, height, C}$")),
                                   "diff_IC_SC_slope_biomass_L" = parse(text = TeX("$\\Delta_{IC-SC,\\mu, biom, L}$")),
                                   "diff_IC_SC_slope_biomass_C" = parse(text = TeX("$\\Delta_{IC-SC, biom, \\mu,  C}$")),
                                   "diff_IC_SC_lambda_height_L" = parse(text = TeX("$\\Delta_{IC-SC, L, \\lambda, height}$")),
                                   "diff_IC_SC_lambda_height_C" = parse(text = TeX("$\\Delta_{IC-SC, C, \\lambda, height}$")),
                                   "diff_IC_SC_lambda_biomass_L" = parse(text = TeX("$\\Delta_{IC-SC, L, \\lambda, biom}$")),
                                   "diff_IC_SC_lambda_biomass_C" = parse(text = TeX("$\\Delta_{IC-SC, C, \\lambda, biom}$")),
                                   'cover_before_800_normalized_tt' =  'cover',
                                   'cover_before_800_normalized_tt_SC_C' = parse(text = TeX("$\\Delta_{IC-SC, C, cover}$")),   
                                   'cover_before_800_normalized_tt_SC_L' = parse(text = TeX("$\\Delta_{IC-SC, L, cover}$")),      
                                   "density_factor" = "density"), drop = drop_val))}
```


```{r}


add_data_to_mod.MERF <- function(mod.MERF, data){
  mod.MERF$data = data
  return(mod.MERF)
}

read_and_assign <- function(path, name_to_assign_suffix = NULL, filter_iterations = TRUE) {
  model <- read_rds(path)  %>% 
    mutate(n_iterations = map_dbl(mod.MERF, ~length(.x$vraisemblance))) %>% 
    mutate(mod.MERF = map2(mod.MERF, data, add_data_to_mod.MERF))
  

  name_to_assign <- unlist(stringr::str_split(path, "\\."))[1]
  name_to_assign <- stringr::str_remove(name_to_assign, "models/MERF/wt_pea/|models/MERF/wt_fababean/|models/MERF/all_species/" )
  
  
  
  if(filter_iterations){
    
    # model <- model
    
    any_not_converged <- max(model$n_iterations) %in% c(1000,3000)
    
      print(paste(name_to_assign, "max iterations" , max(model$n_iterations)))
      model <- model %>%
        mutate(any_not_converged = any_not_converged) %>% 
        filter( (n_iterations < max(n_iterations) & any_not_converged) | (!any_not_converged)) %>% 
        select(-any_not_converged)

  }
  
  
  if(!is.null(name_to_assign_suffix)){name_to_assign = paste(name_to_assign, name_to_assign_suffix, sep = "_")}
  if(nrow(model)>0){assign(x = name_to_assign,  value = model, envir = .GlobalEnv)}
}



function_read_all_model <- function(list_paths = list_models){
  
  invisible(lapply(list_paths, read_and_assign))
} 





list_models <-  grep(list.files("models/MERF", recursive = TRUE, full.names = TRUE), pattern='models_train', invert=TRUE, value=TRUE)
function_read_all_model(list_paths = list_models)



list_models_environment <- str_remove_all(list_models, "models/MERF/wt_pea/|models/MERF/all_species/|models/MERF/wt_fababean/|.rds")
list_models_environment <- ls()[ls()%in% list_models_environment]
# 
# # lapply(list_models_environment, function(x) { print(x) ; print(nrow(get(x, envir = .GlobalEnv)))})
# 
# sapply(list_models_environment, function(x) tibble(model = x, n_models = nrow(get(x, envir = .GlobalEnv)))) %>% t %>% as_tibble %>% unnest(c(model, n_models)) %>% arrange(n_models) %>% print(n = length(list_models_environment))
# 
# 
# sapply(list_models_environment, function(x) tibble(model = x, n_models = colnames(get(x, envir = .GlobalEnv))[3])) %>% t %>% as_tibble %>% unnest(c(model, n_models)) %>% arrange(n_models) %>% print(n = length(list_models_environment))
```



```{r}

function_plot_save_model <- function(model){
  
  print(model)
  mod <- get(model, envir = .GlobalEnv)
  
  y_model = str_extract(model, "yield_cereal|yield_legume|yield_total|PLER_cereal|PLER_legume|LER|BE|CE|SE")
  
  fitted_observed <- fun_get_fitted_observed(mod, y= y_model)

  summary_fitted_observed <- fitted_observed %>%
    group_by(id_obs) %>% 
    summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")
  
  if(str_detect(model, "yield|BE|CE|SE")){
    my_lab_x =  TeX("Observed ($t.ha^{-1}$)")
    my_lab_y =  TeX("Fitted ($t.ha^{-1}$)")
  }else{
    my_lab_x = "Observed"
    my_lab_y = "Fitted"}
  
  if(str_detect(model, "yield|PLER")){
    
    plant_family = str_extract(model, "total|cereal|legume")
    metric = str_extract(model, "yield|PLER")
    title = paste0(str_to_title(plant_family), "'s ", metric,": fitted vs observed")
    
    
  } else {
    metric = str_extract(model, "BE|CE|SE|LER")
    title = paste0(metric,": fitted vs observed")
  }
  
  fitted_vs_obs <- plot_fitted_vs_observed(fitted_observed, summary_fitted_observed, my_title = title,lab_y = my_lab_y, lab_x = my_lab_x, size_text = 18)



  plot_importance_model <- plot_importance(mod, threshold = 10, y= y_model, size_text = 18, add_marginal_plots = FALSE)

  
  plot_combined <- fitted_vs_obs | plot_importance_model

  ggsave(plot = plot_combined, filename = paste0("figures/MERF/plot_", model, ".png"), dpi = "retina", height =18, width  = 18)
}


```


```{r, eval = FALSE}


list_models <- list.files("models/MERF", recursive = TRUE, full.names = TRUE)
list_models_environment <- str_remove_all(list_models, "models/MERF/wt_pea/|models/MERF/all_species/|models/MERF/wt_fababean/|.rds")
list_models_environment <- ls()[ls()%in% list_models_environment]
invisible(lapply(list_models_environment, function_plot_save_model))


```



```{r}


tibble_error_model <- function(model, list_metrics = c("RMSE", "RRMSE_SD", "RRMSE_IQR", "EF")){
  
   mod <-  get(model, envir = .GlobalEnv)
    y_model <- str_extract(model, "yield_cereal|yield_legume|yield_total|PLER_cereal|PLER_legume|LER|BE|CE|SE")
    species_mix <- str_extract(model, "wt_fababean|wt_pea|all_species") 
    
    fitted_observed <- fun_get_fitted_observed(mod, y= y_model)
    
    data_error <- fitted_observed %>%
      group_by(.imp) %>%
      nest %>%
      ungroup %>%  
      mutate(error.MERF = map(data, evaluate_error))%>% 
      unnest(error.MERF) %>% 
      summarise(across(any_of(list_metrics), 
                       .fns = list(mean = mean),
                       .names = "{.col}_{.fn}"), .groups = "drop") %>% 
      round(digits = 2)
    
    
    data_output <- bind_cols(tibble(species_mix = species_mix, y= y_model), data_error)
    
    return(data_output)
  
}


tibble_error_models <- bind_rows(lapply(list_models_environment, tibble_error_model) )


(plot_error_models <- tibble_error_models %>% 
  pivot_longer(where(is.numeric), names_to = "metric", values_to = "value")  %>% 
  ggplot(aes(x =y , y = value, group = species_mix, color = species_mix)) +
  geom_point() + 
  geom_line(alpha = .4) + facet_wrap(metric~., scales= "free" )+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
  facet_wrap(metric~., scales= "free" ))


ggsave(filename = "figures/MERF/error_models.png", plot =plot_error_models, height = 20, width = 25, unit = "cm")



yield_cereal_all_species$mod.MERF[[1]]$random_effects
yield_cereal_all_species$mod.MERF[[1]]$var_random_effects

# tibble_error_model("yield_cereal_all_species")

```


```{r}

# Test RE significance


# predict.longituRF_modified <- function(object, X,Z,id,time,...){
#   n <- length(unique(id))
#   id_btilde <- object$id_btilde
#   f <- predict(object$forest,X)
#   Time <- object$time
#   id_btilde <- object$id_btilde
#   Ypred <- rep(0,length(id))
#   id.app=object$id
#   if (object$sto=="none"){
#     for (i in 1:length(unique(id))){
#       w <- which(id==unique(id)[i])
#       k <- which(id_btilde==unique(id)[i])
#       Ypred[w] <- f[w] + Z[w,, drop=FALSE]%*%object$random_effects[k,]
#     }
#     return(Ypred)
#   }
# }
# 
# 
# covariates <- mod_test$data %>% select(-c(experiment_id, management, yield_cereal)) %>% colnames
# 
# 
# 
# mod_test <- yield_cereal_all_species$mod.MERF[[1]]
# mod_test$random_effects
# 
# 
# 
# fitted_all <- fun_fitted_MERF(mod_test, mod_test$data) %>% mutate(fitted_lonRF = predict.longituRF(mod_test, X = mod_test$data[,covariates], id = mod_test$data[['experiment_id']], Z = as.matrix(rep(1, nrow(mod_test$data)))))
# 
# bind_rows(evaluate_error(fitted_all, fitted = "fitted_lonRF"),evaluate_error(fitted_all)) %>% select(bias,RMSE, RRMSE, RRMSE_IQR, RRMSE_SD, MAE)
# 
# 
# 
# resid_all <- fitted_all$observed - fitted_all$fitted
# 
# 
# 
# data_lme <- tibble(resid =mod_test$data$yield_cereal -  mod_test$forest$predicted, experiment_id = as.factor(mod_test$data$experiment_id))
# 
# 
# ranef_mod.MERF <- tibble(experiment_id = mod_test$id_btilde, re = mod_test$random_effects[,1])
# 
# mod_lme <- lme4::lmer(resid ~(1|experiment_id), data = data_lme)
# 
# ranef_mod_lme <- tibble(experiment_id = rownames(ranef(mod_lme)$experiment_id), re_lme = ranef(mod_lme)$experiment_id$'(Intercept)')
# 
# ranef_mod.MERF %>% left_join(ranef_mod_lme)
# VarCorr(mod_lme)
# 
# 
# mod_test$random_effects
# mod_test$var_random_effects

```


# Model yield cereal

## Yield

```{r}


  
fitted_observed_yield_cereal_all_species <- fun_get_fitted_observed(yield_cereal_all_species, y= "yield_cereal")

summary_fitted_observed_yield_cereal_all_species <- fitted_observed_yield_cereal_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")


```


```{r}


(fitted_vs_obs_yield_cereal_all_species <- plot_fitted_vs_observed(fitted_observed_yield_cereal_all_species, summary_fitted_observed_yield_cereal_all_species, my_title = "Cereal's yield: fitted vs observed",lab_y = TeX("Fitted($t.ha^{-1}$)"), lab_x = TeX("Observed ($t.ha^{-1}$)"), size_text = 18))

variance_decomposition(fitted_observed_yield_cereal_all_species)


# get_error(yield_cereal_all_species, y = "yield_cereal")

evaluate_error(summary_fitted_observed_yield_cereal_all_species, fitted = "mean_fitted")


(plot_importance_yield_cereal_all_species <- plot_importance(yield_cereal_all_species, threshold = 10, y= "yield_cereal", size_text = 18, add_marginal_plots = FALSE))


library(patchwork)
plot_test <- fitted_vs_obs_yield_cereal_all_species | plot_importance_yield_cereal_all_species

ggsave(plot = plot_test, filename = "figures/MERF/plot_yield_cereal_all_species.png", dpi = "retina", height =18, width  = 18)
```

```{r, eval = FALSE}

ggsave(plot = fitted_vs_obs_yield_cereal_all_species,  filename = "figures/all_species/fitted_vs_obs_yield_cereal_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
ggsave(plot = plot_importance_yield_cereal_all_species,  filename = "figures/all_species/plot_importance_yield_cereal_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")
# ggsave(plot = plot_importance_yield_cereal_all_species,  filename = "figures/all_species/plot_importance_yield_cereal_all_species.png", dpi = 300, height = 490, width = 400,  unit = "px")


```

```{r}


function_plot_save_model("yield_cereal_all_species")
```

## PLER 

```{r}


  
fitted_observed_PLER_cereal_all_species <- fun_get_fitted_observed(PLER_cereal_all_species, y= "PLER_cereal")

summary_fitted_observed_PLER_cereal_all_species <- fitted_observed_PLER_cereal_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")


```


```{r}


(fitted_vs_obs_PLER_cereal_all_species <- plot_fitted_vs_observed(fitted_observed_PLER_cereal_all_species, summary_fitted_observed_PLER_cereal_all_species, my_title = "Cereal's PLER: fitted vs observed",lab_y = TeX("Fitted($t.ha^{-1}$)"), lab_x = TeX("Observed ($t.ha^{-1}$)"), size_text = 16))

variance_decomposition(fitted_observed_PLER_cereal_all_species)


get_error(PLER_cereal_all_species, y = "PLER_cereal")

evaluate_error(summary_fitted_observed_PLER_cereal_all_species, fitted = "mean_fitted")


(plot_importance_PLER_cereal_all_species <- plot_importance(PLER_cereal_all_species, threshold = 10, y= "PLER_cereal", size_text = 16, add_marginal_plots = FALSE))


```

```{r, eval = FALSE}

ggsave(plot = fitted_vs_obs_PLER_cereal_all_species,  filename = "figures/all_species/fitted_vs_obs_PLER_cereal_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
ggsave(plot = plot_importance_PLER_cereal_all_species,  filename = "figures/all_species/plot_importance_PLER_cereal_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")

```



# Model yield legume

## Yield

```{r}


yield_legume_all_species <- read_rds("models/all_species/yield_legume_all_species.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 200)

n_models <- length(unique(yield_legume_all_species$.imp))

fitted_observed_legume_all_species <- fun_get_fitted_observed(yield_legume_all_species, y= "yield_legume")

summary_fitted_observed_legume_all_species <- fitted_observed_legume_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")
```


```{r}


(fitted_vs_obs_yield_legume_all_species <- plot_fitted_vs_observed(fitted_observed_legume_all_species, summary_fitted_observed_legume_all_species, my_title = "Legume's yield: fitted vs observed",lab_y = TeX("Fitted($t.ha^{-1}$)"), lab_x = TeX("Observed ($t.ha^{-1}$)"), size_text = 16))

variance_decomposition(fitted_observed_legume_all_species)


get_error(yield_legume_all_species, y = "yield_legume")

evaluate_error(summary_fitted_observed_legume_all_species, fitted = "mean_fitted")


(plot_importance_yield_legume_all_species <- plot_importance(yield_legume_all_species, threshold = n_models, y= "yield_legume", size_text = 16))


```




```{r}

ggsave(plot = fitted_vs_obs_yield_legume_all_species,  filename = "figures/all_species/fitted_vs_obs_yield_legume_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
ggsave(plot = plot_importance_yield_legume_all_species,  filename = "figures/all_species/plot_importance_yield_legume_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")


```




## PLER 



```{r}

PLER_legume_all_species <- read_rds("models/all_species/PLER_legume_all_species.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 2000)

n_models <- length(unique(PLER_legume_all_species$.imp))


  
fitted_observed_legume_all_species <- fun_get_fitted_observed(PLER_legume_all_species, y= "PLER_legume")

summary_fitted_observed_legume_all_species <- fitted_observed_legume_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")


```


```{r}


(fitted_vs_obs_PLER_legume_all_species <- plot_fitted_vs_observed(fitted_observed_legume_all_species, summary_fitted_observed_legume_all_species, my_title = "legume's PLER: fitted vs observed",lab_y = TeX("Fitted"), lab_x = TeX("Observed"), size_text = 16))

variance_decomposition(fitted_observed_legume_all_species)
# 
# 
# get_error(PLER_legume_all_species, y = "PLER_legume")
# 
# # evaluate_error(summary_fitted_observed_legume_all_species, fitted = "mean_fitted")
# 
# 
(plot_importance_PLER_legume_all_species <- plot_importance(PLER_legume_all_species, threshold = n_models, y= "PLER_legume", size_text = 16))


```

```{r}
# 
# ggsave(plot = fitted_vs_obs_PLER_legume_all_species,  filename = "figures/all_species/fitted_vs_obs_PLER_legume_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
# ggsave(plot = plot_importance_PLER_legume_all_species,  filename = "figures/all_species/plot_importance_PLER_legume_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")

```



# Model yield total

## Yield

```{r}


yield_total_all_species <- read_rds("models/all_species/yield_total_all_species.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 200)

n_models <- length(unique(yield_total_all_species$.imp))

fitted_observed_total_all_species <- fun_get_fitted_observed(yield_total_all_species, y= "yield_total")

summary_fitted_observed_total_all_species <- fitted_observed_total_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")
```


```{r}


(fitted_vs_obs_yield_total_all_species <- plot_fitted_vs_observed(fitted_observed_total_all_species, summary_fitted_observed_total_all_species, my_title = "Total's yield: fitted vs observed",lab_y = TeX("Fitted($t.ha^{-1}$)"), lab_x = TeX("Observed ($t.ha^{-1}$)"), size_text = 16))

variance_decomposition(fitted_observed_total_all_species)


get_error(yield_total_all_species, y = "yield_total")

evaluate_error(summary_fitted_observed_total_all_species, fitted = "mean_fitted")


(plot_importance_yield_total_all_species <- plot_importance(yield_total_all_species, threshold = n_models, y= "yield_total", size_text = 16))


```


```{r}

ggsave(plot = fitted_vs_obs_yield_total_all_species,  filename = "figures/all_species/fitted_vs_obs_yield_total_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
ggsave(plot = plot_importance_yield_total_all_species,  filename = "figures/all_species/plot_importance_yield_total_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")


```



## BE

```{r}


BE_all_species <- read_rds("models/all_species/BE_all_species.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 1000)

n_models <- length(unique(BE_all_species$.imp))

fitted_observed_total_all_species <- fun_get_fitted_observed(BE_all_species, y= "BE")

summary_fitted_observed_total_all_species <- fitted_observed_total_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")
```


```{r}

# 
# (fitted_vs_obs_BE_all_species <- plot_fitted_vs_observed(fitted_observed_total_all_species, summary_fitted_observed_total_all_species, my_title = "Total's yield: fitted vs observed",lab_y = TeX("Fitted($t.ha^{-1}$)"), lab_x = TeX("Observed ($t.ha^{-1}$)"), size_text = 16))
# 
# variance_decomposition(fitted_observed_total_all_species)
# 
# 
# get_error(BE_all_species, y = "BE")
# 
# evaluate_error(summary_fitted_observed_total_all_species, fitted = "mean_fitted")
# 
# 
# (plot_importance_BE_all_species <- plot_importance(BE_all_species, threshold = n_models, y= "BE", size_text = 16))


```

```{r}
# 
# ggsave(plot = fitted_vs_obs_BE_all_species,  filename = "figures/all_species/fitted_vs_obs_BE_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
# ggsave(plot = plot_importance_BE_all_species,  filename = "figures/all_species/plot_importance_BE_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")


```





## CE

```{r}


CE_all_species <- read_rds("models/all_species/CE_all_species.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 1000)

n_models <- length(unique(CE_all_species$.imp))

fitted_observed_total_all_species <- fun_get_fitted_observed(CE_all_species, y= "CE")

summary_fitted_observed_total_all_species <- fitted_observed_total_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")
```


```{r}

# 
# (fitted_vs_obs_CE_all_species <- plot_fitted_vs_observed(fitted_observed_total_all_species, summary_fitted_observed_total_all_species, my_title = "Total's yield: fitted vs observed",lab_y = TeX("Fitted($t.ha^{-1}$)"), lab_x = TeX("Observed ($t.ha^{-1}$)"), size_text = 16))
# 
# variance_decomposition(fitted_observed_total_all_species)
# 
# 
# get_error(CE_all_species, y = "CE")
# 
# evaluate_error(summary_fitted_observed_total_all_species, fitted = "mean_fitted")
# 
# 
# (plot_importance_CE_all_species <- plot_importance(CE_all_species, threshold = n_models, y= "CE", size_text = 16))


```

```{r}
# 
# ggsave(plot = fitted_vs_obs_CE_all_species,  filename = "figures/all_species/fitted_vs_obs_CE_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
# ggsave(plot = plot_importance_CE_all_species,  filename = "figures/all_species/plot_importance_CE_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")


```



## SE

```{r}


SE_all_species <- read_rds("models/all_species/SE_all_species.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 2000)

n_models <- length(unique(SE_all_species$.imp))

fitted_observed_SE_all_species <- fun_get_fitted_observed(SE_all_species, y= "SE")

summary_fitted_observed_SE_all_species <- fitted_observed_SE_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")
```


```{r}

# 
(fitted_vs_obs_SE_all_species <- plot_fitted_vs_observed(fitted_observed_SE_all_species, summary_fitted_observed_SE_all_species, my_title = "SE's yield: fitted vs observed",lab_y = TeX("Fitted($t.ha^{-1}$)"), lab_x = TeX("Observed ($t.ha^{-1}$)"), size_text = 16))
# 
variance_decomposition(fitted_observed_SE_all_species)
# 
# 
# get_error(SE_all_species, y = "SE")
# 
# evaluate_error(summary_fitted_observed_SE_all_species, fitted = "mean_fitted")
# 
# 
# (plot_importanSE_SE_all_species <- plot_importanSE(SE_all_species, threshold = n_models, y= "SE", size_text = 16))


```

```{r}
# 
# ggsave(plot = fitted_vs_obs_SE_all_species,  filename = "figures/all_species/fitted_vs_obs_SE_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
# ggsave(plot = plot_importanSE_SE_all_species,  filename = "figures/all_species/plot_importanSE_SE_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")


```


# Copy figures to presentation folder

```{r}

folder_modeling <- "C:/Users/rmahmoud/Documents/INRA/These/R_projects_phD/paper_modeling_intercrop/figures"
folder_presentations <- "C:/Users/rmahmoud/Documents/INRA/These/Presentations/meeting_22_11_2022/presentation_figures"
list_of_files <- list.files(folder_modeling, ".png$",recursive = TRUE, full.names = TRUE) 

file.copy(file.path(list_of_files), folder_presentations, overwrite = TRUE)
```

