---
title: "Analysis models all species"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r, include = FALSE, message=F}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = F,
  warning = F,
  message = F
)

```

```{r}

library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)
library(forcats)

# Modeling
library(nlme)


library(latex2exp)

# theme_set(theme_bw())

theme_set(ggthemes::theme_solarized() + theme(title = element_text(color = "black"), legend.text = element_text(color = "black"), axis.text = element_text(color = "black")))

# ggthemr::ggthemr(palette = "dust")
# ggthemr::swatch()

# library(sjmisc)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")


```


```{r functions}
# Read all functions
list_functions <- list.files("R/scripts_functions", full.names = TRUE)
invisible(lapply(list_functions, source))


```


# Model yield cereal

## Yield

```{r}

yield_cereal_all_species <- read_rds("models/all_species/yield_cereal_all_species.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 200)

n_models <- length(unique(yield_cereal_all_species$.imp))


  
fitted_observed_cereal_all_species <- fun_get_fitted_observed(yield_cereal_all_species, y= "yield_cereal")

summary_fitted_observed_cereal_all_species <- fitted_observed_cereal_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")


```


```{r}


(fitted_vs_obs_yield_cereal_all_species <- plot_fitted_vs_observed(fitted_observed_cereal_all_species, summary_fitted_observed_cereal_all_species, my_title = "Cereal's yield: fitted vs observed",lab_y = TeX("Fitted($t.ha^{-1}$)"), lab_x = TeX("Observed ($t.ha^{-1}$)"), size_text = 16))

variance_decomposition(fitted_observed_cereal_all_species)


get_error(yield_cereal_all_species, y = "yield_cereal")

evaluate_error(summary_fitted_observed_cereal_all_species, fitted = "mean_fitted")


(plot_importance_yield_cereal_all_species <- plot_importance(yield_cereal_all_species, threshold = n_models, y= "yield_cereal", size_text = 16))


```

```{r}

ggsave(plot = fitted_vs_obs_yield_cereal_all_species,  filename = "figures/all_species/fitted_vs_obs_yield_cereal_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
ggsave(plot = plot_importance_yield_cereal_all_species,  filename = "figures/all_species/plot_importance_yield_cereal_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")
# ggsave(plot = plot_importance_yield_cereal_all_species,  filename = "figures/all_species/plot_importance_yield_cereal_all_species.png", dpi = 300, height = 490, width = 400,  unit = "px")


```


## PLER 



```{r}

PLER_cereal_all_species <- read_rds("models/all_species/PLER_cereal_all_species.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 1000)

n_models <- length(unique(PLER_cereal_all_species$.imp))


  
fitted_observed_cereal_all_species <- fun_get_fitted_observed(PLER_cereal_all_species, y= "PLER_cereal")

summary_fitted_observed_cereal_all_species <- fitted_observed_cereal_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")


```


```{r}


(fitted_vs_obs_PLER_cereal_all_species <- plot_fitted_vs_observed(fitted_observed_cereal_all_species, summary_fitted_observed_cereal_all_species, my_title = "Cereal's PLER: fitted vs observed",lab_y = TeX("Fitted"), lab_x = TeX("Observed"), size_text = 16))

variance_decomposition(fitted_observed_cereal_all_species)


get_error(PLER_cereal_all_species, y = "PLER_cereal")

# evaluate_error(summary_fitted_observed_cereal_all_species, fitted = "mean_fitted")


(plot_importance_PLER_cereal_all_species <- plot_importance(PLER_cereal_all_species, threshold = n_models, y= "PLER_cereal", size_text = 16))


```

```{r}

ggsave(plot = fitted_vs_obs_PLER_cereal_all_species,  filename = "figures/all_species/fitted_vs_obs_PLER_cereal_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
ggsave(plot = plot_importance_PLER_cereal_all_species,  filename = "figures/all_species/plot_importance_PLER_cereal_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")

```



# Model yield legume

## Yield

```{r}


yield_legume_all_species <- read_rds("models/all_species/yield_legume_all_species.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 200)

n_models <- length(unique(yield_legume_all_species$.imp))

fitted_observed_legume_all_species <- fun_get_fitted_observed(yield_legume_all_species, y= "yield_legume")

summary_fitted_observed_legume_all_species <- fitted_observed_legume_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")
```


```{r}


(fitted_vs_obs_yield_legume_all_species <- plot_fitted_vs_observed(fitted_observed_legume_all_species, summary_fitted_observed_legume_all_species, my_title = "Legume's yield: fitted vs observed",lab_y = TeX("Fitted($t.ha^{-1}$)"), lab_x = TeX("Observed ($t.ha^{-1}$)"), size_text = 16))

variance_decomposition(fitted_observed_legume_all_species)


get_error(yield_legume_all_species, y = "yield_legume")

evaluate_error(summary_fitted_observed_legume_all_species, fitted = "mean_fitted")


(plot_importance_yield_legume_all_species <- plot_importance(yield_legume_all_species, threshold = n_models, y= "yield_legume", size_text = 16))


```




```{r}

ggsave(plot = fitted_vs_obs_yield_legume_all_species,  filename = "figures/all_species/fitted_vs_obs_yield_legume_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
ggsave(plot = plot_importance_yield_legume_all_species,  filename = "figures/all_species/plot_importance_yield_legume_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")


```




## PLER 



```{r}

PLER_legume_all_species <- read_rds("models/all_species/PLER_legume_all_species.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 2000)

n_models <- length(unique(PLER_legume_all_species$.imp))


  
fitted_observed_legume_all_species <- fun_get_fitted_observed(PLER_legume_all_species, y= "PLER_legume")

summary_fitted_observed_legume_all_species <- fitted_observed_legume_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")


```


```{r}


(fitted_vs_obs_PLER_legume_all_species <- plot_fitted_vs_observed(fitted_observed_legume_all_species, summary_fitted_observed_legume_all_species, my_title = "legume's PLER: fitted vs observed",lab_y = TeX("Fitted"), lab_x = TeX("Observed"), size_text = 16))

variance_decomposition(fitted_observed_legume_all_species)
# 
# 
# get_error(PLER_legume_all_species, y = "PLER_legume")
# 
# # evaluate_error(summary_fitted_observed_legume_all_species, fitted = "mean_fitted")
# 
# 
(plot_importance_PLER_legume_all_species <- plot_importance(PLER_legume_all_species, threshold = n_models, y= "PLER_legume", size_text = 16))


```

```{r}
# 
# ggsave(plot = fitted_vs_obs_PLER_legume_all_species,  filename = "figures/all_species/fitted_vs_obs_PLER_legume_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
# ggsave(plot = plot_importance_PLER_legume_all_species,  filename = "figures/all_species/plot_importance_PLER_legume_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")

```



# Model yield total

## Yield

```{r}


yield_total_all_species <- read_rds("models/all_species/yield_total_all_species.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 200)

n_models <- length(unique(yield_total_all_species$.imp))

fitted_observed_total_all_species <- fun_get_fitted_observed(yield_total_all_species, y= "yield_total")

summary_fitted_observed_total_all_species <- fitted_observed_total_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")
```


```{r}


(fitted_vs_obs_yield_total_all_species <- plot_fitted_vs_observed(fitted_observed_total_all_species, summary_fitted_observed_total_all_species, my_title = "Total's yield: fitted vs observed",lab_y = TeX("Fitted($t.ha^{-1}$)"), lab_x = TeX("Observed ($t.ha^{-1}$)"), size_text = 16))

variance_decomposition(fitted_observed_total_all_species)


get_error(yield_total_all_species, y = "yield_total")

evaluate_error(summary_fitted_observed_total_all_species, fitted = "mean_fitted")


(plot_importance_yield_total_all_species <- plot_importance(yield_total_all_species, threshold = n_models, y= "yield_total", size_text = 16))


```


```{r}

ggsave(plot = fitted_vs_obs_yield_total_all_species,  filename = "figures/all_species/fitted_vs_obs_yield_total_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
ggsave(plot = plot_importance_yield_total_all_species,  filename = "figures/all_species/plot_importance_yield_total_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")


```



## BE

```{r}


BE_all_species <- read_rds("models/all_species/BE_all_species.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 1000)

n_models <- length(unique(BE_all_species$.imp))

fitted_observed_total_all_species <- fun_get_fitted_observed(BE_all_species, y= "BE")

summary_fitted_observed_total_all_species <- fitted_observed_total_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")
```


```{r}

# 
# (fitted_vs_obs_BE_all_species <- plot_fitted_vs_observed(fitted_observed_total_all_species, summary_fitted_observed_total_all_species, my_title = "Total's yield: fitted vs observed",lab_y = TeX("Fitted($t.ha^{-1}$)"), lab_x = TeX("Observed ($t.ha^{-1}$)"), size_text = 16))
# 
# variance_decomposition(fitted_observed_total_all_species)
# 
# 
# get_error(BE_all_species, y = "BE")
# 
# evaluate_error(summary_fitted_observed_total_all_species, fitted = "mean_fitted")
# 
# 
# (plot_importance_BE_all_species <- plot_importance(BE_all_species, threshold = n_models, y= "BE", size_text = 16))


```

```{r}
# 
# ggsave(plot = fitted_vs_obs_BE_all_species,  filename = "figures/all_species/fitted_vs_obs_BE_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
# ggsave(plot = plot_importance_BE_all_species,  filename = "figures/all_species/plot_importance_BE_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")


```





## CE

```{r}


CE_all_species <- read_rds("models/all_species/CE_all_species.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 1000)

n_models <- length(unique(CE_all_species$.imp))

fitted_observed_total_all_species <- fun_get_fitted_observed(CE_all_species, y= "CE")

summary_fitted_observed_total_all_species <- fitted_observed_total_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")
```


```{r}

# 
# (fitted_vs_obs_CE_all_species <- plot_fitted_vs_observed(fitted_observed_total_all_species, summary_fitted_observed_total_all_species, my_title = "Total's yield: fitted vs observed",lab_y = TeX("Fitted($t.ha^{-1}$)"), lab_x = TeX("Observed ($t.ha^{-1}$)"), size_text = 16))
# 
# variance_decomposition(fitted_observed_total_all_species)
# 
# 
# get_error(CE_all_species, y = "CE")
# 
# evaluate_error(summary_fitted_observed_total_all_species, fitted = "mean_fitted")
# 
# 
# (plot_importance_CE_all_species <- plot_importance(CE_all_species, threshold = n_models, y= "CE", size_text = 16))


```

```{r}
# 
# ggsave(plot = fitted_vs_obs_CE_all_species,  filename = "figures/all_species/fitted_vs_obs_CE_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
# ggsave(plot = plot_importance_CE_all_species,  filename = "figures/all_species/plot_importance_CE_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")


```



## SE

```{r}


SE_all_species <- read_rds("models/all_species/SE_all_species.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 2000)

n_models <- length(unique(SE_all_species$.imp))

fitted_observed_SE_all_species <- fun_get_fitted_observed(SE_all_species, y= "SE")

summary_fitted_observed_SE_all_species <- fitted_observed_SE_all_species %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")
```


```{r}

# 
(fitted_vs_obs_SE_all_species <- plot_fitted_vs_observed(fitted_observed_SE_all_species, summary_fitted_observed_SE_all_species, my_title = "SE's yield: fitted vs observed",lab_y = TeX("Fitted($t.ha^{-1}$)"), lab_x = TeX("Observed ($t.ha^{-1}$)"), size_text = 16))
# 
variance_decomposition(fitted_observed_SE_all_species)
# 
# 
# get_error(SE_all_species, y = "SE")
# 
# evaluate_error(summary_fitted_observed_SE_all_species, fitted = "mean_fitted")
# 
# 
# (plot_importanSE_SE_all_species <- plot_importanSE(SE_all_species, threshold = n_models, y= "SE", size_text = 16))


```

```{r}
# 
# ggsave(plot = fitted_vs_obs_SE_all_species,  filename = "figures/all_species/fitted_vs_obs_SE_all_species.png", dpi = 300, height = 18, width = 12,  unit = "cm")
# ggsave(plot = plot_importanSE_SE_all_species,  filename = "figures/all_species/plot_importanSE_SE_all_species.png", dpi = 300, height = 18, width = 16,  unit = "cm")


```


# Copy figures to presentation folder

```{r}

folder_modeling <- "C:/Users/rmahmoud/Documents/INRA/These/R_projects_phD/paper_modeling_intercrop/figures"
folder_presentations <- "C:/Users/rmahmoud/Documents/INRA/These/Presentations/meeting_22_11_2022/presentation_figures"
list_of_files <- list.files(folder_modeling, ".png$",recursive = TRUE, full.names = TRUE) 

file.copy(file.path(list_of_files), folder_presentations, overwrite = TRUE)
```

