---
title: "Plot models LongituRF"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r, include = FALSE, message=F}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = F,
  warning = F,
  message = F
)

```

```{r}

library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)
library(forcats)

library(LongituRF)


library(patchwork)
library(latex2exp)

# Modeling
library(nlme)


library(latex2exp)

# theme_set(theme_bw())

# theme_set(ggthemes::theme_solarized() + theme(title = element_text(color = "black"), legend.text = element_text(color = "black"), axis.text = element_text(color = "black")))



theme_set(theme_bw()+ 
   theme(axis.title = element_text(size = 16),
         legend.title = element_text(size = 12),
         axis.text = element_text(size=  14),
         legend.text = element_text(size=  12 ),
         strip.text = element_text(size= 12),
         legend.position = "bottom"))
# ggthemr::ggthemr(palette = "dust")
# ggthemr::swatch()

# library(sjmisc)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")


```


```{r functions}
# Read all functions
list_functions <- list.files("R/scripts_functions", full.names = TRUE)

# "R/scripts_functions/function_gmerf_modified.R",
list_functions <- c( "R/scripts_functions/functions_analysis_models_MERF.R", "R/scripts_functions/functions_evaluate_errors.R",
                    "R/scripts_functions/functions_LongituRF_modified.R", "R/scripts_functions/functions_tools.R")

invisible(lapply(list_functions, source))


```




```{r}
format_importance <- function(data_models, name_model = NULL){
  
  n_models <- length(unique(data_models$.imp))
  
  
  if(is.null(name_model)){name_model <-deparse(substitute(data_models))}
  
  data_output <-  get_importance(data_models) %>% 
    filter(n >= n_models) %>% 
    arrange(desc(mean_importance)) %>% 
    mutate(rank = 1:n(), model = name_model) %>% 
    distinct(variable, mean_importance, rank, sign_cor, model )  

  return(data_output)
}
```



```{r}
my_scale_y <- function(drop_val = FALSE){return(scale_y_discrete(labels=c('diff_slope_biomass'=parse(text = TeX('$\\Delta \\mu_{biom}$')),
                                   "diff_IC_SC_asymp_height_C" = parse(text = TeX("$\\Delta_{IC-SC, C, height}$")),
                                   "diff_IC_SC_asymp_height_L" = parse(text = TeX("$\\Delta_{IC-SC, L, height}$")),
                                   "diff_IC_SC_asymp_biomass_C" = parse(text = TeX("$\\Delta_{IC-SC, C, biomass}$")),
                                   "diff_IC_SC_asymp_biomass_L" = parse(text = TeX("$\\Delta_{IC-SC, L, biomass}$")),
                                   "diff_IC_SC_max_LAI_C" = parse(text = TeX("$\\Delta_{IC-SC, C, LAI}$")),
                                   "diff_IC_SC_max_LAI_L" = parse(text = TeX("$\\Delta_{IC-SC, L, LAI}$")),
                                   "diff_IC_SC_max_sla_GLT_C" = parse(text = TeX("$\\Delta_{IC-SC, C, SLA}$")),
                                   "diff_IC_SC_max_sla_GLT_L" = parse(text = TeX("$\\Delta_{IC-SC, L, SLA}$")),
                                   'diff_lambda_height'=parse(text = TeX('$\\Delta_{\\lambda, height}$')),
                                   'diff_lambda_biomass'=parse(text = TeX('$\\Delta_{\\lambda, biom}$')),
                                   'diff_max_LAI' = parse(text = TeX('$\\Delta_{max, LAI}$')), 
                                   'diff_max_sla_GLT' = parse(text = TeX('$\\Delta_{max, SLA}$')), 
                                   'diff_slope_height'=parse(text = TeX('$\\Delta_{\\mu, height}$')),
                                   'diff_asymp_height'=parse(text = TeX('$\\Delta_{max, height}$')),
                                   "diff_IC_SC_slope_height_L" = parse(text = TeX("$\\Delta_{IC-SC, \\mu, height, L}$")),
                                   "diff_IC_SC_slope_height_C" = parse(text = TeX("$\\Delta_{IC-SC, \\mu, height, C}$")),
                                   "diff_IC_SC_slope_biomass_L" = parse(text = TeX("$\\Delta_{IC-SC,\\mu, biom, L}$")),
                                   "diff_IC_SC_slope_biomass_C" = parse(text = TeX("$\\Delta_{IC-SC, biom, \\mu,  C}$")),
                                   "diff_IC_SC_lambda_height_L" = parse(text = TeX("$\\Delta_{IC-SC, \\lambda, height, L}$")),
                                   "diff_IC_SC_lambda_height_C" = parse(text = TeX("$\\Delta_{IC-SC, C, \\lambda, height}$")),
                                   "diff_IC_SC_lambda_biomass_L" = parse(text = TeX("$\\Delta_{IC-SC, L, \\lambda, biom}$")),
                                   "diff_IC_SC_lambda_biomass_C" = parse(text = TeX("$\\Delta_{IC-SC, C, \\lambda, biom}$")),
                                   'cover_before_800_normalized_tt' =  'cover',
                                   'cover_before_800_normalized_tt_SC_C' = parse(text = TeX("$\\Delta_{IC-SC, C, cover}$")),   
                                   'cover_before_800_normalized_tt_SC_L' = parse(text = TeX("$\\Delta_{IC-SC, L, cover}$")),      
                                   "density_factor" = "density"), drop = drop_val))}
```


```{r}


add_data_to_mod.MERF <- function(mod.MERF, data){
  mod.MERF$data = data
  return(mod.MERF)
}

read_and_assign <- function(path, name_to_assign_suffix = NULL, filter_iterations = TRUE) {
  model <- read_rds(path)  %>% 
    mutate(n_iterations = map_dbl(mod.MERF, ~length(.x$vraisemblance))) %>% 
    mutate(mod.MERF = map2(mod.MERF, data, add_data_to_mod.MERF))
  

  name_to_assign <- unlist(stringr::str_split(path, "\\."))[1]
  name_to_assign <- stringr::str_remove(name_to_assign, "models/N_seed/wt_pea/|models/N_seed/wt_fababean/|models/N_seed/all_species/" )
  
  
  
  if(filter_iterations){
    
    # model <- model
    
    any_not_converged <- max(model$n_iterations) %in% c(1000,3000)
    
      print(paste(name_to_assign, "max iterations" , max(model$n_iterations)))
      model <- model %>%
        mutate(any_not_converged = any_not_converged) %>% 
        filter( (n_iterations < max(n_iterations) & any_not_converged) | (!any_not_converged)) %>% 
        select(-any_not_converged)

  }
  
  
  if(!is.null(name_to_assign_suffix)){name_to_assign = paste(name_to_assign, name_to_assign_suffix, sep = "_")}
  if(nrow(model)>0){assign(x = name_to_assign,  value = model, envir = .GlobalEnv)}
}



function_read_all_model <- function(list_paths = list_models){
  
  invisible(lapply(list_paths, read_and_assign))
} 





list_models <-  grep(list.files("models/N_seed", recursive = TRUE, full.names = TRUE), pattern='models_train|BE|CE|SE', invert=TRUE, value=TRUE)
function_read_all_model(list_paths = list_models)



list_models_environment <- str_remove_all(list_models, "models/N_seed/wt_pea/|models/N_seed/all_species/|models/N_seed/wt_fababean/|.rds")
list_models_environment <- ls()[ls()%in% list_models_environment]
# 
# # lapply(list_models_environment, function(x) { print(x) ; print(nrow(get(x, envir = .GlobalEnv)))})
# 
# sapply(list_models_environment, function(x) tibble(model = x, n_models = nrow(get(x, envir = .GlobalEnv)))) %>% t %>% as_tibble %>% unnest(c(model, n_models)) %>% arrange(n_models) %>% print(n = length(list_models_environment))
# 
# 
# sapply(list_models_environment, function(x) tibble(model = x, n_models = colnames(get(x, envir = .GlobalEnv))[3])) %>% t %>% as_tibble %>% unnest(c(model, n_models)) %>% arrange(n_models) %>% print(n = length(list_models_environment))
```



```{r}

function_plot_save_model <- function(model){
  
  print(model)
  mod <- get(model, envir = .GlobalEnv)
  
  y_model = str_extract(model, "N_seed_cereal")
  
  fitted_observed <- fun_get_fitted_observed(mod, y= y_model)

  summary_fitted_observed <- fitted_observed %>%
    group_by(id_obs) %>% 
    summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")
  
  if(str_detect(model, "N_seed_cereal")){
    my_lab_x =  TeX("Observed ($mg.g^{-1}$)")
    my_lab_y =  TeX("Fitted ($mg.g^{-1}$)")
  }else{
    my_lab_x = "Observed"
    my_lab_y = "Fitted"}
  
  if(str_detect(model, "yield|PLER")){
    
    plant_family = str_extract(model, "total|cereal|legume")
    metric = str_extract(model, "yield|PLER")
    title = paste0(str_to_title(plant_family), "'s ", metric,": fitted vs observed")
    
    
  } else {
    metric = str_extract(model, "N_seed_cereal")
    title = paste0(metric,": fitted vs observed")
  }
  
  fitted_vs_obs <- plot_fitted_vs_observed(fitted_observed, summary_fitted_observed, my_title = title,lab_y = my_lab_y, lab_x = my_lab_x, size_text = 18)



  plot_importance_model <- plot_importance(mod, threshold = 10, y= y_model, size_text = 18, add_marginal_plots = FALSE)

  
  plot_combined <- fitted_vs_obs | plot_importance_model

  ggsave(plot = plot_combined, filename = paste0("figures/N_seed/plot_", model, ".png"), dpi = "retina", height =18, width  = 18)
}


```


```{r, eval = FALSE}


list_models_environment <- str_remove_all(list_models, "models/N_seed/wt_pea/|models/N_seed/all_species/|models/N_seed/wt_fababean/|.rds")
list_models_environment <- ls()[ls()%in% list_models_environment]


invisible(lapply(list_models_environment, function_plot_save_model))


```



```{r}


tibble_error_model <- function(model, list_metrics = c("RMSE", "RRMSE_SD", "RRMSE_IQR", "EF")){
  
   mod <-  get(model, envir = .GlobalEnv)
    y_model <- str_extract(model, "yield_cereal|yield_legume|yield_total|PLER_cereal|PLER_legume|LER|BE|CE|SE")
    species_mix <- str_extract(model, "wt_fababean|wt_pea|all_species") 
    
    fitted_observed <- fun_get_fitted_observed(mod, y= y_model)
    
    data_error <- fitted_observed %>%
      group_by(.imp) %>%
      nest %>%
      ungroup %>%  
      mutate(error.MERF = map(data, evaluate_error))%>% 
      unnest(error.MERF) %>% 
      summarise(across(any_of(list_metrics), 
                       .fns = list(mean = mean),
                       .names = "{.col}_{.fn}"), .groups = "drop") %>% 
      round(digits = 2)
    
    
    data_output <- bind_cols(tibble(species_mix = species_mix, y= y_model), data_error)
    
    return(data_output)
  
}


tibble_error_models <- bind_rows(lapply(list_models_environment, tibble_error_model) )


(plot_error_models <- tibble_error_models %>% 
  pivot_longer(where(is.numeric), names_to = "metric", values_to = "value")  %>% 
  ggplot(aes(x =y , y = value, group = species_mix, color = species_mix)) +
  geom_point() + 
  geom_line(alpha = .4) + facet_wrap(metric~., scales= "free" )+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
  facet_wrap(metric~., scales= "free" ))


ggsave(filename = "figures/MERF/error_models.png", plot =plot_error_models, height = 20, width = 25, unit = "cm")



yield_cereal_all_species$mod.MERF[[1]]$random_effects
yield_cereal_all_species$mod.MERF[[1]]$var_random_effects

# tibble_error_model("yield_cereal_all_species")

```


```{r}


fitted_obs_model <- function(model){
  
   mod <-  get(model, envir = .GlobalEnv)
    y_model <- str_extract(model, "N_seed_cereal")
    species_mix <- str_extract(model, "wt_fababean|wt_pea|all_species") 
    
    fitted_observed <- fun_get_fitted_observed(mod, y= y_model)
    
    
    data_output <- bind_cols(tibble(species_mix = species_mix, y= y_model), fitted_observed)
    
    return(data_output)
  
}


tibble_fitted_obs_models <- bind_rows(lapply(list_models_environment, fitted_obs_model) )%>% 
    mutate(species_mix = str_replace_all(species_mix, c("wt_fababean" = "Blé dur / Féverole", "wt_pea" = "Blé dur / Pois", "all_species" = "Blé dur / légumineuses"))) %>% 
  mutate(species_mix = fct_relevel(species_mix, "Blé dur / légumineuses", after= Inf)) %>% 
    mutate(y = str_replace_all(y, c("legume" = "lég", "cereal" = "blé dur", "yield" = "Rdt", "_" = " "))) 

summary_fitted_obs_models <- tibble_fitted_obs_models %>% group_by(id_obs, y, species_mix, observed) %>% 
  summarise(mean_fitted = mean(fitted), .groups = "drop")




# tibble_fitted_obs_models %>% 
#     ggplot(aes(x = observed, y= fitted)) + 
#     geom_point(alpha=.2) + 
#     geom_point(data= summary_fitted_obs_models, aes(y = mean_fitted), shape = 4, size=  4) + 
#     geom_y_x() + 
#     facet_wrap(y ~species_mix, scales = "free", ncol = 3) + 
#     labs(title = NULL, x = "Observed", y = "Fitted")+
#     theme(title = element_text(size = 18),
#           axis.text = element_text(size = 18 +2))

(plot_fitted_obs_all_models <- tibble_fitted_obs_models %>% 
    ggplot(aes(x = observed, y= fitted)) + 
    geom_point(alpha=.2) + 
    geom_point(data= summary_fitted_obs_models, aes(y = mean_fitted), shape = 4, size=  4, alpha =  .4) + 
    geom_y_x() + 
    ggh4x::facet_grid2( ~species_mix, independent = "all", scales = "free") + 
    labs(title = NULL, x = TeX("Teneur en N observées ($mg.g^{-1}$)"), y =  TeX("Teneur en N ajustées ($mg.g^{-1}$)"))+
    theme(title = element_text(size = 18),
          axis.title = element_text(size=  11),
          axis.text = element_text(size = 11))
)

ggsave(filename = "figures/N_seed/plot_fitted_obs_all_models.png", plot =plot_fitted_obs_all_models, height = 8, width = 20, unit = "cm")

file.copy("figures/N_seed/plot_fitted_obs_all_models.png", to  ="C:/Users/rmahmoud/Dropbox/Applications/Overleaf/Manuscrit thèse/chap4_modeling_IC/figures/plot_fitted_obs_N_seed_all_models.png", overwrite = TRUE)
```

