---
title: "Plot models LongituRF"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r, include = FALSE, message=F}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = F,
  warning = F,
  message = F
)

```

```{r}

library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)
library(forcats)

library(LongituRF)


library(patchwork)
library(latex2exp)

# Modeling
library(nlme)


library(latex2exp)

theme_set(theme_bw())

# theme_set(ggthemes::theme_solarized() + theme(title = element_text(color = "black"), legend.text = element_text(color = "black"), axis.text = element_text(color = "black")))

# ggthemr::ggthemr(palette = "dust")
# ggthemr::swatch()

# library(sjmisc)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")


```


```{r functions}
# Read all functions
list_functions <- list.files("R/scripts_functions", full.names = TRUE)

list_functions <- c("R/scripts_functions/function_gmerf_modified.R", "R/scripts_functions/functions_analysis_models_MERF.R", "R/scripts_functions/functions_evaluate_errors.R",
                    "R/scripts_functions/functions_LongituRF_modified.R", "R/scripts_functions/functions_tools.R")

invisible(lapply(list_functions, source))


```




```{r}
format_importance <- function(data_models, name_model = NULL){
  
  n_models <- length(unique(data_models$.imp))
  
  
  if(is.null(name_model)){name_model <-deparse(substitute(data_models))}
  
  data_output <-  get_importance(data_models) %>% 
    filter(n >= n_models) %>% 
    arrange(desc(mean_importance)) %>% 
    mutate(rank = 1:n(), model = name_model) %>% 
    distinct(variable, mean_importance, rank, sign_cor, model )  

  return(data_output)
}
```



```{r}


add_data_to_mod.MERF <- function(mod.MERF, data){
  mod.MERF$data = data
  return(mod.MERF)
}

# add_all_columns_data_test <- function(data_test, imp_number,  data_all_covariates = data_all_diff){
#   data_test_all_columns <- data_all_covariates %>% inner_join(data_test %>% mutate(.imp = imp_number) %>% distinct(.imp, management, experiment_id))
#   return(data_test_all_columns)
# }


read_and_assign <- function(path, name_to_assign_suffix = NULL, filter_iterations = TRUE) {
  model <- read_rds(path)  %>% 
    mutate(n_iterations = map_dbl(mod.MERF, ~length(.x$vraisemblance))) %>% 
    # mutate(data_test = map2(data_test, .imp, add_all_columns_data_test)) %>% 
    mutate(mod.MERF = map2(mod.MERF, data, add_data_to_mod.MERF))  
  

  name_to_assign <- unlist(stringr::str_split(path, "\\."))[1]
  name_to_assign <- stringr::str_remove(name_to_assign, "models/MERF/models_train/wt_pea/|models/MERF/models_train/wt_fababean/|models/MERF/models_train/all_species/" )
  
  
  
  if(filter_iterations){
    
    # model <- model
    
    any_not_converged <- max(model$n_iterations) %in% c(1000,3000, 5000)
    
      print(paste(name_to_assign, "max iterations" , max(model$n_iterations)))
      model <- model %>%
        mutate(any_not_converged = any_not_converged) %>% 
        filter( (n_iterations < max(n_iterations) & any_not_converged) | (!any_not_converged)) %>% 
        select(-any_not_converged)

  }
  
  
  if(!is.null(name_to_assign_suffix)){name_to_assign = paste(name_to_assign, name_to_assign_suffix, sep = "_")}
  if(nrow(model)>0){assign(x = name_to_assign,  value = model, envir = .GlobalEnv)}
}



function_read_all_model <- function(list_paths = list_models){
  
  invisible(lapply(list_paths, read_and_assign))
} 



data_all_diff <-  read_rds( "data/data_all_diff_with_imputations.rds") %>% shorten_exp_id()



list_models <-  grep(list.files("models/MERF", recursive = TRUE, full.names = TRUE), pattern='models_train', invert=FALSE, value=TRUE)
function_read_all_model(list_paths = list_models)



list_models_environment <- str_remove_all(list_models, "models/MERF/models_train/wt_pea/|models/MERF/models_train/all_species/|models/MERF/models_train/wt_fababean/|.rds")
list_models_environment <- ls()[ls()%in% list_models_environment]


# data_all_diff %>% inner_join(yield_legume_wt_pea$data_test[[1]] %>% mutate(.imp = 1) %>% distinct(.imp, management, experiment_id))

# 
# # lapply(list_models_environment, function(x) { print(x) ; print(nrow(get(x, envir = .GlobalEnv)))})
# 
sapply(list_models_environment, function(x) tibble(model = x, n_models = nrow(get(x, envir = .GlobalEnv)))) %>% t %>% as_tibble %>% unnest(c(model, n_models)) %>% arrange(n_models) %>% print(n = length(list_models_environment))

# 
# sapply(list_models_environment, function(x) tibble(model = x, n_models = colnames(get(x, envir = .GlobalEnv))[3])) %>% t %>% as_tibble %>% unnest(c(model, n_models)) %>% arrange(n_models) %>% print(n = length(list_models_environment))
```



```{r}
# 
function_plot_save_model <- function(model){

  print(model)
  mod <- get(model, envir = .GlobalEnv)

  y_model = str_extract(model, "yield_cereal|yield_legume|yield_total|PLER_cereal|PLER_legume|LER|BE|CE|SE")

  fitted_observed <- fun_get_fitted_observed_train_test(mod, y= y_model)

  summary_fitted_observed <- fitted_observed %>%
    group_by(id_obs, subset) %>%
    summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")

  if(str_detect(model, "yield|BE|CE|SE")){
    my_lab_x =  TeX("Observed ($t.ha^{-1}$)")
    my_lab_y =  TeX("Fitted ($t.ha^{-1}$)")
  }else{
    my_lab_x = "Observed"
    my_lab_y = "Fitted"}

  if(str_detect(model, "yield|PLER")){

    plant_family = str_extract(model, "total|cereal|legume")
    metric = str_extract(model, "yield|PLER")
    title = paste0(str_to_title(plant_family), "'s ", metric,": fitted vs observed")


  } else {
    metric = str_extract(model, "BE|CE|SE|LER")
    title = paste0(metric,": fitted vs observed")
  }

  fitted_vs_obs <- plot_fitted_vs_observed_train_test(fitted_observed, summary_fitted_observed, my_title = title,lab_y = my_lab_y, lab_x = my_lab_x, size_text = 18)



  plot_importance_model <- plot_importance(mod, threshold = 10, y= y_model, size_text = 18, add_marginal_plots = FALSE)


  plot_combined <- fitted_vs_obs | plot_importance_model

  ggsave(plot = plot_combined, filename = paste0("figures/MERF/models_train/plot_", model, "_train_test.png"), dpi = "retina", height =18, width  = 18)
}


```


```{r, eval = FALSE}


list_models <- list.files("models/MERF/models_train", recursive = TRUE, full.names = TRUE)
list_models_environment <- str_remove_all(list_models, "models/MERF/models_train/wt_pea/|models/MERF/models_train/all_species/|models/MERF/models_train/wt_fababean/|.rds")
list_models_environment <- ls()[ls()%in% list_models_environment]
invisible(lapply(list_models_environment, function_plot_save_model))


# plot_fitted_vs_observed_train_test(fitted_observed, summary_fitted_observed)
```



```{r}


tibble_error_model <- function(model, list_metrics = c("RMSE", "RRMSE_SD", "RRMSE_IQR", "EF")){
  
    # print(model)
   mod <-  get(model, envir = .GlobalEnv)
    y_model <- str_extract(model, "yield_cereal|yield_legume|yield_total|PLER_cereal|PLER_legume|LER|BE|CE|SE")
    species_mix <- str_extract(model, "wt_fababean|wt_pea|all_species") 
    
    fitted_observed <- fun_get_fitted_observed_train_test(mod, y= y_model)
    
    data_error <- fitted_observed %>%
      group_by(.imp, subset) %>%
      nest %>%
      ungroup %>%  
      mutate(error.MERF = map(data, evaluate_error))%>% 
      unnest(error.MERF) %>% 
      group_by(subset) %>% 
      summarise(across(any_of(list_metrics), 
                       # .fns = list(mean = mean),
                       .fns = list(mean = ~ round(mean(.x), digits = 2)),
                       .names = "{.col}_{.fn}"), .groups = "drop")
    
    data_output <- bind_cols(tibble(species_mix = species_mix, y= y_model), data_error)
    
    return(data_output)
  
}


tibble_error_models <- bind_rows(lapply(list_models_environment, tibble_error_model) )


# tibble_error_models%>% 
#   pivot_longer(where(is.numeric), names_to = "metric", values_to = "value")   %>% 
#   ggplot(aes(x = y, y = value)) + 
(
plot_error_models <- tibble_error_models %>% 
  pivot_longer(where(is.numeric), names_to = "metric", values_to = "value")  %>% 
  ggplot(aes(x =y , y = value, group = interaction(species_mix, subset), color = subset)) +
  geom_point(aes(shape = species_mix)) + 
  geom_line(alpha = .4) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
  facet_wrap(metric~., scales= "free" ))


ggsave(filename = "figures/MERF/models_train/error_models_train_test.png", plot =plot_error_models, height = 20, width = 25, unit = "cm")

yield_cereal_all_species$mod.MERF[[1]]$random_effects
yield_cereal_all_species$mod.MERF[[1]]$var_random_effects

# tibble_error_model("yield_cereal_all_species")

```


```{r}


# dats=rnorm(10000, 0, 1)
# dats=data.frame(index=1:1000, data=dats)
# ggplot()+geom_points(data=dats, aes(x=index, y=dats)) #intentional error line
# plot(dats$index, dats$data)
# summary(dats$data+1)
```

