---
title: "Partial plots LongituRF"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r, include = FALSE, message=F}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = F,
  warning = F,
  message = F
)

```

```{r}

library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)
library(forcats)

library(LongituRF)


library(patchwork)
library(latex2exp)

# Modeling
library(nlme)


library(latex2exp)

theme_set(theme_bw()+ 
   theme(axis.title = element_text(size = 16),
         legend.title = element_text(size = 12),
         axis.text = element_text(size=  14),
         legend.text = element_text(size=  12 ),
         strip.text = element_text(size= 12),
         legend.position = "bottom"))

# theme_set(ggthemes::theme_solarized() + theme(title = element_text(color = "black"), legend.text = element_text(color = "black"), axis.text = element_text(color = "black")))

# ggthemr::ggthemr(palette = "dust")
# ggthemr::swatch()

# library(sjmisc)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")


```


```{r functions}
# Read all functions
list_functions <- list.files("R/scripts_functions", full.names = TRUE)

list_functions <- c("R/scripts_functions/function_gmerf_modified.R", "R/scripts_functions/functions_analysis_models_MERF.R", "R/scripts_functions/functions_evaluate_errors.R",
                    "R/scripts_functions/functions_LongituRF_modified.R", "R/scripts_functions/functions_tools.R")

invisible(lapply(list_functions, source))


```




```{r}
format_importance <- function(data_models, name_model = NULL){
  
  n_models <- length(unique(data_models$.imp))
  
  
  if(is.null(name_model)){name_model <-deparse(substitute(data_models))}
  
  data_output <-  get_importance(data_models) %>% 
    filter(n >= n_models) %>% 
    arrange(desc(mean_importance)) %>% 
    mutate(rank = 1:n(), model = name_model) %>% 
    distinct(variable, mean_importance, rank, sign_cor, model )  

  return(data_output)
}
```



```{r}


format_string_predictors <- function(x){
  return(str_replace_all(x, fixed(c('diff_slope_biomass'='$\\Delta \\mu_{biom}$',
                                   "diff_IC_SC_asymp_height_C" = "$\\Delta_{IC-SC, C, height}$",
                                   "diff_IC_SC_asymp_height_L" = "$\\Delta_{IC-SC, L, height}$",
                                   "diff_IC_SC_max_LAI_C" = "$\\Delta_{IC-SC, C, LAI}$",
                                   "diff_IC_SC_max_sla_GLT_C" = "$\\Delta_{IC-SC, C, SLA}$",
                                   "diff_IC_SC_max_sla_GLT_L" = "$\\Delta_{IC-SC, L, SLA}$",
                                   "diff_IC_SC_max_LAI_L" = "$\\Delta_{IC-SC, L, LAI}$",
                                   'diff_lambda_height'='$\\Delta_{\\lambda}  height$',
                                   'diff_lambda_biomass'='$\\Delta_{\\lambda}  biom$',
                                   'diff_max_LAI' = '$\\Delta_{max, LAI}$',
                                   'diff_max_sla_GLT' = '$\\Delta_{max, SLA}$',
                                   'diff_slope_height'='$\\Delta_{\\mu, height}$',
                                   'diff_asymp_height'='$\\Delta_{max, height}$',
                                   "diff_IC_SC_slope_height_L" = "$\\Delta_{IC-SC, \\mu, height, L}$",
                                   "diff_IC_SC_slope_height_C" = "$\\Delta_{IC-SC} \\mu, height, C$",
                                   "diff_IC_SC_slope_biomass_L" = "$\\Delta_{IC-SC,\\mu, biom, L}$",
                                   "diff_IC_SC_slope_biomass_C" = "$\\Delta_{IC-SC, biom, \\mu,  C}$",
                                   "diff_IC_SC_lambda_height_L" = "$\\Delta_{IC-SC, L, \\lambda, height}$",
                                   "diff_IC_SC_lambda_height_C" = "$\\Delta_{IC-SC, C, \\lambda, height}$",
                                   "diff_IC_SC_lambda_biomass_L" = "$\\Delta_{IC-SC, L, \\lambda, biom}$",
                                   "diff_IC_SC_lambda_biomass_C" = "$\\Delta_{IC-SC, C, \\lambda, biom}$"))))
}


appender <- function(string) { TeX(string)  }
```


```{r}


add_data_to_mod.MERF <- function(mod.MERF, data){
  mod.MERF$data = data
  return(mod.MERF)
}

read_and_assign <- function(path, name_to_assign_suffix = NULL, filter_iterations = TRUE) {
  model <- read_rds(path)  %>% 
    mutate(n_iterations = map_dbl(mod.MERF, ~length(.x$vraisemblance))) %>% 
    mutate(mod.MERF = map2(mod.MERF, data, add_data_to_mod.MERF))
  

  name_to_assign <- unlist(stringr::str_split(path, "\\."))[1]
  name_to_assign <- stringr::str_remove(name_to_assign, "models/MERF/wt_pea/|models/MERF/wt_fababean/|models/MERF/all_species/" )
  
  
  
  if(filter_iterations){
    
    # model <- model
    
    any_not_converged <- max(model$n_iterations) %in% c(1000,3000)
    
      print(paste(name_to_assign, "max iterations" , max(model$n_iterations)))
      model <- model %>%
        mutate(any_not_converged = any_not_converged) %>% 
        filter( (n_iterations < max(n_iterations) & any_not_converged) | (!any_not_converged)) %>% 
        select(-any_not_converged)

  }
  
  
  if(!is.null(name_to_assign_suffix)){name_to_assign = paste(name_to_assign, name_to_assign_suffix, sep = "_")}
  if(nrow(model)>0){assign(x = name_to_assign,  value = model, envir = .GlobalEnv)}
}



function_read_all_model <- function(list_paths = list_models){
  
  invisible(lapply(list_paths, read_and_assign))
} 





list_models <-  grep(list.files("models/MERF", recursive = TRUE, full.names = TRUE), pattern='models_train', invert=TRUE, value=TRUE)
function_read_all_model(list_paths = list_models)



list_models_environment <- str_remove_all(list_models, "models/MERF/wt_pea/|models/MERF/all_species/|models/MERF/wt_fababean/|.rds")
list_models_environment <- ls()[ls()%in% list_models_environment]
# 
# # lapply(list_models_environment, function(x) { print(x) ; print(nrow(get(x, envir = .GlobalEnv)))})
# 
# sapply(list_models_environment, function(x) tibble(model = x, n_models = nrow(get(x, envir = .GlobalEnv)))) %>% t %>% as_tibble %>% unnest(c(model, n_models)) %>% arrange(n_models) %>% print(n = length(list_models_environment))
# 
# 
# sapply(list_models_environment, function(x) tibble(model = x, n_models = colnames(get(x, envir = .GlobalEnv))[3])) %>% t %>% as_tibble %>% unnest(c(model, n_models)) %>% arrange(n_models) %>% print(n = length(list_models_environment))
```



```{r read data }

data_all_diff <-  read_rds( "data/data_all_diff_with_imputations.rds")

data_BE_CE_SE <- read_rds("data/data_BE_CE_SE_LER.rds")

data_NNI <- read_rds("data/data_NNI.rds") %>%
  inner_join(data_all_diff %>% distinct(experiment_id, management)) %>% 
  shorten_exp_id() %>% 
  group_by(experiment_id, management) %>% 
  summarise(across(contains("NNI"), mean), .groups = "drop")
```


# Wheat turgidum / pea





```{r}


fun_save_plot_marginals_models <- function(model, n_variables = 4, alpha_points = .7, alpha_smooth_lm = 0.3){

  print(model)
  mod <- get(model, envir = .GlobalEnv)

  y_model = str_extract(model, "yield_cereal|yield_legume|yield_total|PLER_cereal|PLER_legume|LER|BE|CE|SE")
  
  y_model_formatted <- str_replace_all(y_model, c("_"=" ", "yield"= "Rendement", "cereal"= "céréale", "legume" = "légumineuse"))
  

  data_importance <- get_importance(mod)
  
  
  if(n_variables < nrow(data_importance)){message(paste(model, "Discarding", as.character(nrow(data_importance) - n_variables), "variables available"))}
  if(n_variables > nrow(data_importance)){message(paste(model, "Taking the only", as.character(nrow(data_importance)), "variables available"))}
  
  
  
  
  n_var_most_important <- data_importance %>% slice_max(order_by = mean_importance,
                                             n = min(n_variables, nrow(data_importance))) 
  var_plots <-n_var_most_important %>% 
    pull(variable) %>% 
    as.character()
  
  
  numeric_variables <- which(!is.na(n_var_most_important$cor_kendal))
   
   # 
  character_variables <- which(is.na((data_importance %>% slice_max(order_by = mean_importance,
                                             n = min(n_variables, nrow(data_importance))))$cor_kendal))
  
  data_predictors <- mod %>% 
    unnest(data) %>%
    group_by(experiment_id, management) %>%
    summarise(across(where(is.numeric), mean), across(where(is.character), unique), across(where(is.factor), unique), .groups = "drop") %>%
    left_join(
      data.intercrop::index %>%
        shorten_exp_id() %>% distinct(experiment_id, management, N_amount)) %>% 
    rename_with(.cols = !matches("yield_cereal|yield_legume|PLER_cereal|PLER_legume"), .fn = ~str_replace_all(.x, c("cereal" = "C","legume" =  "L")))
  
  
  if(length(numeric_variables) > 0){
    data_numeric <- data_predictors %>% 
      select(experiment_id, management, any_of(var_plots), {{y_model}}, any_of(c("cult_C", "cult_L", "L")), N_amount) %>%
      pivot_longer(cols = matches(var_plots) & where(is.numeric)) %>% 
      left_join(n_var_most_important %>% distinct(name = variable, mean_importance)) %>% 
      mutate(name = fct_reorder(name, mean_importance, .desc = TRUE )) %>% 
    mutate(name_formatted = format_string_predictors(name))
  
  }
  
  
  
  if(length(character_variables) > 0){
  data_character <- data_predictors %>% 
    select(experiment_id, management, any_of(var_plots), {{y_model}}, any_of(c("cult_C", "cult_L")), N_amount) %>%
    distinct() %>%
    pivot_longer(cols = matches(var_plots) & where(~is.character(.x)|is.factor(.x))) %>% 
    select(- where(is.numeric), N_amount, {{y_model}}) %>% 
    left_join(n_var_most_important %>% distinct(name = variable, mean_importance)) %>% 
    mutate(name = fct_reorder(name, mean_importance, .desc = TRUE )) %>% 
    mutate(value =  tidytext::reorder_within(value, !!sym(y_model), name, fun = median)) %>% 
    mutate(name_formatted = format_string_predictors(name))
  }
  
  
  
  if(str_detect(model, "yield|BE|CE|SE")){
    # my_lab_x =  TeX("Observed ($t.ha^{-1}$)")
    
    
    my_lab_y =   TeX(paste0(y_model_formatted," ($t.ha^{-1}$)"))
  }else{
    # my_lab_x = "Observed"
    my_lab_y = y_model_formatted}

  # if(str_detect(model, "yield|PLER")){
  # 
  #   plant_family = str_extract(model, "total|cereal|legume")
  #   metric = str_extract(model, "yield|PLER")
  #   title = paste0(str_to_title(plant_family), "'s ", metric,": fitted vs observed")
  # 
  # 
  # } else {
  #   metric = str_extract(model, "BE|CE|SE|LER")
  #   title = paste0(metric,": fitted vs observed")
  # }


  if(length(character_variables) > 0){
    
    plot_quali <- data_character%>%
      ggplot(aes(x = value, y=.data[[y_model]]))  +
      geom_boxplot(outlier.size= 0, alpha=  0) +
      geom_point(aes(color = experiment_id, size =N_amount), position = position_jitter(width = .1), alpha=  alpha_points ) + 
      scale_size_continuous(range = c(2,5)) + 
      tidytext::scale_x_reordered() +
      labs(x = NULL, y = my_lab_y) +
      facet_wrap(name~., scales= "free", 
               labeller = as_labeller(appender, 
                            default = label_parsed))+
      theme(axis.text.x = element_text(angle = 45) ) +     
      guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2)) 
  
  ggsave(plot = plot_quali, filename = paste0("figures/MERF/marginal_plots/marg_plot_predictors_quali_", model, ".png"), dpi = "retina", height =15, width  = 16)
  }
  
  if(length(numeric_variables) > 0){
    
    if(str_detect(model, "all_species")){ shape_var = "L"} else if(str_detect(model, "legume")) {shape_var = "cult_L"} else {shape_var = "cult_C"}
    
    
    plot_numeric <- data_numeric %>% 
      ggplot(aes(x = value, y= .data[[y_model]]))  +
      geom_point(aes(color = experiment_id, shape = .data[[shape_var]], size =N_amount), alpha = alpha_points ) + 
      scale_size_continuous(range = c(3,7)) + 
      labs(x = NULL, y = my_lab_y, color = "Expérimentation", size = "N (kg/ha)")  + 
      # facet_wrap(name~., scales= "free") +
      facet_wrap(name_formatted~., scales= "free", 
               labeller = as_labeller(appender, 
                            default = label_parsed)) +
      geom_line(stat = "smooth", 
                method = "lm", 
                aes(group = experiment_id, color = experiment_id),
                se = FALSE, alpha=  alpha_smooth_lm, size = 2)  +
      guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2), shape = guide_legend(nrow = 2) ) 
    # geom_ribbon(stat='smooth', method = "lm", se=TRUE, alpha=0.1, 
    #             aes(color = NULL, group = experiment_id)) +
      # stat_smooth(method = "lm", aes(group = experiment_id, color = experiment_id), se = FALSE) )

  ggsave(plot = plot_numeric, filename = paste0("figures/MERF/marginal_plots/marg_plot_predictors_numeric_", model, ".png"), dpi = "retina", height =15, width  = 16)

  }
  # plot_combined <- fitted_vs_obs | plot_importance_model

  # ggsave(plot = plot_combined, filename = paste0("figures/MERF/models_train/plot_", model, "_train_test.png"), dpi = "retina", height =18, width  = 18)
}


    



```


```{r}

# fun_save_plot_marginals_models("yield_cereal_all_species")
# invisible(lapply(list_models_environment[1], fun_save_plot_marginals_models))

invisible(lapply(list_models_environment, fun_save_plot_marginals_models))
# 
# 
# for(i in 1:10){
#   print(fun_compute_importance_MERF(BE_wt_pea$mod.MERF[[i]]))
#   }

```
# Transfer plots



```{r, eval = FALSE}

data.qualitative::legumes %>% filter(species == "fababean") %>% distinct(species, cultivar,  height, crop_height)

data.qualitative::legumes %>% filter(species == "fababean", !is.na(height), cultivar != "columbo") %>% distinct(species, cultivar,  height, crop_height)


data.qualitative::cereals %>% filter(species == "durum_wheat", cultivar %in% c("L1823", "acalou", "nefer", "neodur","orjaune", "sculptur"
))

```



```{r}

```

