---
title: "Plot models LongituRF"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r, include = FALSE, message=F}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = F,
  warning = F,
  message = F
)

```

```{r}

library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)
library(forcats)

library(LongituRF)


library(patchwork)
library(latex2exp)

# Modeling
library(nlme)


library(latex2exp)

theme_set(theme_bw())

# theme_set(ggthemes::theme_solarized() + theme(title = element_text(color = "black"), legend.text = element_text(color = "black"), axis.text = element_text(color = "black")))

# ggthemr::ggthemr(palette = "dust")
# ggthemr::swatch()

# library(sjmisc)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")


```


```{r functions}
# Read all functions
# list_functions <- list.files("R/scripts_functions", full.names = TRUE)

list_functions <- c("R/scripts_functions/functions_analysis_models_MERF.R", "R/scripts_functions/functions_evaluate_errors.R",
                    "R/scripts_functions/functions_LongituRF_modified.R", "R/scripts_functions/functions_tools.R")

invisible(lapply(list_functions, source))


```







```{r}


add_data_to_mod.MERF <- function(mod.MERF, data){
  mod.MERF$data = data
  return(mod.MERF)
}

# add_all_columns_data_test <- function(data_test, imp_number,  data_all_covariates = data_all_diff){
#   data_test_all_columns <- data_all_covariates %>% inner_join(data_test %>% mutate(.imp = imp_number) %>% distinct(.imp, management, experiment_id))
#   return(data_test_all_columns)
# }



read_and_assign <- function(path, name_to_assign_suffix = NULL, filter_iterations = TRUE) {
  model <- read_rds(path)  %>% 
    mutate(n_iterations = map_dbl(mod.MERF, ~length(.x$vraisemblance))) %>% 
    mutate(mod.MERF = map2(mod.MERF, data, add_data_to_mod.MERF))
  

  name_to_assign <- unlist(stringr::str_split(path, "\\."))[1]
  name_to_assign <- stringr::str_remove(name_to_assign, "models/MERF/wt_pea/|models/MERF/wt_fababean/|models/MERF/all_species/" )
  
  
  
  if(filter_iterations){
    
    # model <- model
    
    any_not_converged <- max(model$n_iterations) %in% c(1000,3000)
    
      print(paste(name_to_assign, "max iterations" , max(model$n_iterations)))
      model <- model %>%
        mutate(any_not_converged = any_not_converged) %>% 
        filter( (n_iterations < max(n_iterations) & any_not_converged) | (!any_not_converged)) %>% 
        select(-any_not_converged)

  }
  
  
  if(!is.null(name_to_assign_suffix)){name_to_assign = paste(name_to_assign, name_to_assign_suffix, sep = "_")}
  if(nrow(model)>0){assign(x = name_to_assign,  value = model, envir = .GlobalEnv)}
}


read_and_assign_cross_validation <- function(path, name_to_assign_suffix = NULL, filter_iterations = TRUE) {
  model <- read_rds(path)  %>% 
    mutate(n_iterations = map_dbl(mod.MERF, ~length(.x$vraisemblance))) %>% 
    # mutate(data_test = map2(data_test, .imp, add_all_columns_data_test)) %>% 
    mutate(mod.MERF = map2(mod.MERF, data, add_data_to_mod.MERF))  
  

  name_to_assign <- unlist(stringr::str_split(path, "\\."))[1]
  name_to_assign <- stringr::str_remove(name_to_assign, "models/MERF/models_train_test_cv/wt_pea/|models/MERF/models_train_test_cv/wt_fababean/|models/MERF/models_train_test_cv/all_species/" )
  
  
  
  if(filter_iterations){
    
    # model <- model
    
    any_not_converged <- max(model$n_iterations) %in% c(1000,3000, 5000)
    
      print(paste(name_to_assign, "max iterations" , max(model$n_iterations)))
      model <- model %>%
        mutate(any_not_converged = any_not_converged) %>% 
        filter( (n_iterations < max(n_iterations) & any_not_converged) | (!any_not_converged)) %>% 
        select(-any_not_converged)

  }
  
  
  if(!is.null(name_to_assign_suffix)){name_to_assign = paste(name_to_assign, name_to_assign_suffix, sep = "_")}
  if(nrow(model)>0){assign(x = name_to_assign,  value = model, envir = .GlobalEnv)}
}



function_read_all_model <- function(list_paths = list_models, fun = read_and_assign, suffix = "cv"){
  
  invisible(lapply(list_paths, fun, suffix))
} 





```


```{r}


list_models_cv <-  grep(list.files("models/MERF", recursive = TRUE, full.names = TRUE), pattern='models_train_test_cv', invert=FALSE, value=TRUE)

# function_read_all_model(list_models[2])
function_read_all_model(list_paths = list_models_cv, fun = read_and_assign_cross_validation)

list_models <-  grep(list.files("models/MERF", recursive = TRUE, full.names = TRUE), pattern='models_train.*|BE|CE|SE', invert=TRUE, value=TRUE)

function_read_all_model(list_paths = list_models, fun = read_and_assign, suffix = NULL)


list_models_environment <- ls()[str_detect(ls(), "yield|PLER|LER")]

```





```{r}


tibble_error_model <- function(model, list_metrics = c("RMSE","bias", "RRMSE", "RRMSE_SD")){
  
    # print(model)
   mod <-  get(model, envir = .GlobalEnv)
    y_model <- str_extract(model, "yield_cereal|yield_legume|yield_total|PLER_cereal|PLER_legume|LER|BE|CE|SE")
    species_mix <- str_extract(model, "wt_fababean|wt_pea|all_species") 
    
    if(str_detect(model, "cv")){
      fitted_observed <- fun_get_fitted_observed_cross_validation(mod, y= y_model)
      
      data_error <- fitted_observed %>%
        group_by(.imp, subset) %>%
        nest %>%
        ungroup %>%  
        mutate(error.MERF = map(data, evaluate_error))%>% 
        unnest(error.MERF) %>% 
        group_by(subset) %>% 
        summarise(across(any_of(list_metrics), 
                         # .fns = list(mean = mean),
                         .fns = list(mean = ~ round(mean(.x), digits = 2)),
                         .names = "{.col}_{.fn}"), .groups = "drop")
      
      data_output <- bind_cols(tibble(species_mix = species_mix, y= y_model), data_error)
      
      return(data_output)
    } else {
      fitted_observed <- fun_get_fitted_observed(mod, y= y_model)
      
      data_error <- fitted_observed %>%
        mutate(subset = "all") %>% 
        group_by(.imp, subset) %>%
        nest %>%
        ungroup %>%  
        mutate(error.MERF = map(data, evaluate_error))%>% 
        unnest(error.MERF) %>% 
        group_by(subset) %>% 
        summarise(across(any_of(list_metrics), 
                         # .fns = list(mean = mean),
                         .fns = list(mean = ~ round(mean(.x), digits = 2))),
                          .groups = "drop")
      
      data_output <- bind_cols(tibble(species_mix = species_mix, y= y_model), data_error)
      
      return(data_output)
    }
    
  
}

list_models_plot_train_cv_error <- list_models_environment[!str_detect(list_models_environment, "^LER|yield_total")]
tibble_error_models <- bind_rows(lapply(list_models_plot_train_cv_error, tibble_error_model) )

tibble_error_models_plot <- tibble_error_models %>% 
  mutate(species_mix = str_replace_all(species_mix, c( "wt_pea"  = "Blé dur / pois", "wt_fababean" = "Blé dur / féverole", "all_species" = "Blé dur / légumineuses")) ) %>% 
  mutate(y = str_replace_all(y, c("_"= " ", "cereal" = "blé", "legume" = "lég", "yield" = "Rdt", "PLER" = "pLER" ))) %>% 
  mutate(subset = str_replace_all(subset, c("all" ="Toutes les données", "test" = "Ensemble d'évaluation"))) %>% 
  rename("Mélanges" = "species_mix", "Données" = "subset")
(
  plot_error_models <- tibble_error_models_plot %>% 
    select(Mélanges:Données, RMSE_mean, RRMSE_mean) %>% 
    pivot_longer(where(is.numeric), names_to = "metric", values_to = "value")  %>% 
    mutate(metric = str_replace_all(metric, c( "RRMSE" = "nRMSE","bias"= "Biais"))) %>% 
    mutate(metric = str_remove(metric, "_mean")) %>%
    arrange(metric) %>% 
    mutate(metric = fct_relevel(metric, c("Biais", "RMSE", "nRMSE", "nRMSE_SD"))) %>% 
    ggplot(aes(x =y , y = value, group = interaction(Mélanges, Données), color = Données)) +
    geom_point(aes(shape = Mélanges)) + 
    geom_line(alpha = .4) +
    guides(color=guide_legend(nrow=2,byrow=TRUE), shape = guide_legend(nrow=2,byrow=TRUE) ) +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5), axis.title = element_blank(), legend.position = "bottom", legend.title = element_text(size = 10)) +
    facet_wrap(metric~., scales= "free" ))


ggsave(filename = "figures/MERF/error_models_cv_all.png", plot =plot_error_models, dpi = "retina", height = 8, width = 17, unit = "cm")

file.copy("figures/MERF/error_models_cv_all.png", to  ="C:/Users/rmahmoud/Dropbox/Applications/Overleaf/Manuscrit thèse/chap4_modeling_IC/figures/error_models_cv_all.png", overwrite = TRUE)

```


```{r variance decomposition}


# variance_decomposition(fun_get_fitted_observed(yield_cereal_wt_fababean, y = "yield_cereal"))

get_prop_var_imputation <- function(model){
  mod <-  get(model, envir = .GlobalEnv)
  y_model <- str_extract(model, "yield_cereal|yield_legume|yield_total|PLER_cereal|PLER_legume|LER|BE|CE|SE")
  species_mix <- str_extract(model, "wt_fababean|wt_pea|all_species") 

  fitted_observed <- fun_get_fitted_observed(mod, y_model)
  
  return(tibble(species_mix = species_mix, y= y_model, variance_imputation = variance_decomposition(fitted_observed)$prop_var_imputation))
}

list_models_manuscript <- list_models_environment[!str_detect(list_models_environment, "^LER|yield_total|cv")]
tibble_var_imputation <- bind_rows(lapply(list_models_manuscript, get_prop_var_imputation) )


tibble_var_imputation_models_plot <- tibble_var_imputation %>% 
  mutate(species_mix = str_replace_all(species_mix, c( "wt_pea"  = "Blé dur / pois", "wt_fababean" = "Blé dur / féverole", "all_species" = "Blé dur / légumineuses")) ) %>% 
  mutate(y = str_replace_all(y, c("_"= " ", "cereal" = "blé", "legume" = "lég", "yield" = "Rdt", "PLER" = "pLER" ))) %>% 
  rename("Mélanges" = "species_mix") 
# (
#   plot_var_imputation_models <- tibble_var_imputation_models_plot %>% 
#     arrange((y)) %>% 
#     mutate(y = fct_inorder(y)) %>% 
#     ggplot(aes(x =y , y = variance_imputation, group = interaction(Espèces), color = Espèces)) +
#     geom_point(aes(shape = Espèces)) + 
#     # geom_line(alpha = .4) +
#     labs(y = "Variance due à\nl'imputation") + 
#     scale_y_continuous(labels = scales::label_percent()) +
#     # guides(color=guide_legend(nrow=2,byrow=TRUE), shape = guide_legend(nrow=2,byrow=TRUE) ) +
#     theme(axis.text.x = element_text(angle = 45, vjust = 0.5, size= 8), axis.text.y = element_text(size= 8), axis.title = element_blank(), legend.position = "bottom", legend.title = element_text(size = 9), legend.text = element_text(size = 8)) )
# 
# 
# ggsave(filename = "figures/MERF/var_imputation_models.png", plot =plot_var_imputation_models, dpi = "retina", height = 6, width = 10, unit = "cm")
# 
# file.copy("figures/MERF/var_imputation_models.png", to  ="C:/Users/rmahmoud/Dropbox/Applications/Overleaf/Manuscrit thèse/chap4_modeling_IC/figures/var_imputation_models.png", overwrite = TRUE)


table_variance_imputation <- tibble_var_imputation_models_plot %>% 
  mutate(variance_imputation = paste0(round(100*variance_imputation, digits = 1), "%")) %>% 
  pivot_wider(names_from = y, values_from = variance_imputation)


library(kableExtra)


sink("doc/table_variance_imputation.tex")
kable(table_variance_imputation, booktabs = TRUE,  escape = TRUE, format = "latex", longtable = F, label = "table_variance_imputation", caption = "Part de la variance due aux imputations") %>% 
  # add_header_above(c(" ", "colLabel1"=2, "colLabel2"=2)) %>% 
  kable_styling(latex_options = "hold_position", font_size = 9) %>%
  column_spec(1, width = "3cm") %>%
  column_spec(2:4, width = "1.5cm")
sink()

file.copy( from = "doc/table_variance_imputation.tex", to  ="C:/Users/rmahmoud/Dropbox/Applications/Overleaf/Manuscrit thèse/chap4_modeling_IC/tables/table_variance_imputation.tex", overwrite = TRUE)


```

