---
title: "Analysis models wheat turgidum pea"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r, include = FALSE, message=F}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = F,
  warning = F,
  message = F
)

```

```{r}

library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)
library(forcats)


library(latex2exp)

# theme_set(theme_bw())

theme_set(ggthemes::theme_solarized() + theme(title = element_text(color = "black"), legend.text = element_text(color = "black"), axis.text = element_text(color = "black")))

# library(sjmisc)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")


```


```{r functions}
# Read all functions
list_functions <- list.files("R/scripts_functions", full.names = TRUE)
invisible(lapply(list_functions, source))


```


# Read models

## Yield


```{r}
format_importance <- function(data_models, name_model = NULL){
  
  n_models <- length(unique(data_models$.imp))
  
  
  if(is.null(name_model)){name_model <-deparse(substitute(data_models))}
  
  data_output <-  get_importance(data_models) %>% 
    filter(n >= n_models) %>% 
    arrange(desc(mean_importance)) %>% 
    mutate(rank = 1:n(), model = name_model) %>% 
    distinct(variable, mean_importance, rank, sign_cor, model )  

  return(data_output)
}
```



```{r}
my_scale_y <- function(drop_val = FALSE){return(scale_y_discrete(labels=c('diff_slope_biomass'=parse(text = TeX('$\\Delta \\mu_{biom}$')),
                                   "diff_IC_SC_asymp_height_C" = parse(text = TeX("$\\Delta_{IC-SC, C, height}$")),
                                   "diff_IC_SC_asymp_height_L" = parse(text = TeX("$\\Delta_{IC-SC, L, height}$")),
                                   "diff_IC_SC_asymp_biomass_C" = parse(text = TeX("$\\Delta_{IC-SC, C, biomass}$")),
                                   "diff_IC_SC_asymp_biomass_L" = parse(text = TeX("$\\Delta_{IC-SC, L, biomass}$")),
                                   "diff_IC_SC_max_LAI_C" = parse(text = TeX("$\\Delta_{IC-SC, C, LAI}$")),
                                   "diff_IC_SC_max_LAI_L" = parse(text = TeX("$\\Delta_{IC-SC, L, LAI}$")),
                                   "diff_IC_SC_max_sla_GLT_C" = parse(text = TeX("$\\Delta_{IC-SC, C, SLA}$")),
                                   "diff_IC_SC_max_sla_GLT_L" = parse(text = TeX("$\\Delta_{IC-SC, L, SLA}$")),
                                   'diff_lambda_height'=parse(text = TeX('$\\Delta_{\\lambda, height}$')),
                                   'diff_lambda_biomass'=parse(text = TeX('$\\Delta_{\\lambda, biom}$')),
                                   'diff_max_LAI' = parse(text = TeX('$\\Delta_{max, LAI}$')), 
                                   'diff_max_sla_GLT' = parse(text = TeX('$\\Delta_{max, SLA}$')), 
                                   'diff_slope_height'=parse(text = TeX('$\\Delta_{\\mu, height}$')),
                                   'diff_asymp_height'=parse(text = TeX('$\\Delta_{max, height}$')),
                                   "diff_IC_SC_slope_height_L" = parse(text = TeX("$\\Delta_{IC-SC, \\mu, height, L}$")),
                                   "diff_IC_SC_slope_height_C" = parse(text = TeX("$\\Delta_{IC-SC, \\mu, height, C}$")),
                                   "diff_IC_SC_slope_biomass_L" = parse(text = TeX("$\\Delta_{IC-SC,\\mu, biom, L}$")),
                                   "diff_IC_SC_slope_biomass_C" = parse(text = TeX("$\\Delta_{IC-SC, biom, \\mu,  C}$")),
                                   "diff_IC_SC_lambda_height_L" = parse(text = TeX("$\\Delta_{IC-SC, L, \\lambda, height}$")),
                                   "diff_IC_SC_lambda_height_C" = parse(text = TeX("$\\Delta_{IC-SC, C, \\lambda, height}$")),
                                   "diff_IC_SC_lambda_biomass_L" = parse(text = TeX("$\\Delta_{IC-SC, L, \\lambda, biom}$")),
                                   "diff_IC_SC_lambda_biomass_C" = parse(text = TeX("$\\Delta_{IC-SC, C, \\lambda, biom}$")),
                                   'cover_before_800_normalized_tt' =  'cover',
                                   'cover_before_800_normalized_tt_SC_C' = parse(text = TeX("$\\Delta_{IC-SC, C, cover}$")),   
                                   'cover_before_800_normalized_tt_SC_L' = parse(text = TeX("$\\Delta_{IC-SC, L, cover}$")),      
                                   "density_factor" = "density"), drop = drop_val))}
```


```{r}


library(purrr)
library(readr)




read_and_assign <- function(path, name_to_assign_suffix = NULL, filter_iterations = TRUE) {
  model <- read_rds(path) %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration))
  

  name_to_assign <- unlist(stringr::str_split(path, "\\."))[1]
  name_to_assign <- stringr::str_remove(name_to_assign, "models/wt_pea/|models/wt_fababean/|models/all_species/" )
  
  
  
  if(filter_iterations){
    
    any_not_converged <- max(model$n_iterations) %in% c(200,1000,2000)
    
      print(paste(name_to_assign, "max iterations" , max(model$n_iterations)))
      model <- model %>%
        mutate(any_not_converged = any_not_converged) %>% 
        filter( (n_iterations < max(n_iterations) & any_not_converged) | (!any_not_converged)) %>% 
        select(-any_not_converged)

  }
  
  
  if(!is.null(name_to_assign_suffix)){name_to_assign = paste(name_to_assign, name_to_assign_suffix, sep = "_")}
  if(nrow(model)>0){assign(x = name_to_assign,  value = model, envir = .GlobalEnv)}
}



function_read_all_model <- function(list_paths = list_models){
  
  invisible(lapply(list_paths, read_and_assign))
} 




list_models <- list.files("models", recursive = TRUE, full.names = TRUE)
function_read_all_model(list_paths = list_models)



list_models_environment <- str_remove_all(list_models, "models/wt_pea/|models/all_species/|models/wt_fababean/|.rds")
list_models_environment <- ls()[ls()%in% list_models_environment]

# lapply(list_models_environment, function(x) { print(x) ; print(nrow(get(x, envir = .GlobalEnv)))})

sapply(list_models_environment, function(x) tibble(model = x, n_models = nrow(get(x, envir = .GlobalEnv)))) %>% t %>% as_tibble %>% unnest(c(model, n_models)) %>% arrange(n_models) %>% print(n = length(list_models_environment))
```


```{r}

all_predictors <- c(read_rds("data/data_all_diff_with_imputations.rds") %>% select(matches("diff|cover|cult|NNI")) %>% colnames,
                    "NNI_legume", "NNI_cereal", "cult_C", "cult_L", "legume")


plot_importance_all_models <- function(list_models, vec_predictors = all_predictors, remove_unused_predictors = FALSE){
  
  data_importance <- tibble()
  for(model in list_models){
    
    print(model)
    name_model <- model
    
    model <- get(model, envir = .GlobalEnv)
    
    name_model = paste(name_model, nrow(model), sep = " - ")
    
    data_importance <- bind_rows(data_importance, format_importance(model, name_model = name_model))
    
    
  }
  
  data_all_predictors <-   tibble(variable = as.factor(all_predictors)) %>% 
  # as_tibble() %>%
    mutate(variable = stringr::str_replace(variable, "cereal" , "C")) %>%  
    mutate(variable = stringr::str_replace(variable, "legume" , "L"))%>% 
    full_join(data_importance) %>% 
    filter(variable != "diff_asymp_biomass") %>% 
    mutate(variable = as.factor(variable)) %>% 
    mutate(sign_cor = fct_recode(sign_cor, "+" = "POS","-" = "NEG")) %>% 
    mutate(label_cor = paste( rank, sign_cor,sep = " ; ")) %>% 
    mutate(type = str_extract(variable, "NNI|height|LAI|sla|biom|cover|cult")) %>% 
    arrange(type, variable) %>% 
    mutate(variable = fct_inorder(variable))


  plot_output <- data_all_predictors %>% 
    filter(!is.na(model)) %>% 
    ggplot(aes(x = model, y = variable)) + 
    # geom_tile(aes(color = sign_cor, fill = rank), alpha = .4) +
    # geom_tile(aes(color = sign_cor, fill = rank), size = 2) + 
    geom_tile(aes(fill = rank), color = "black", alpha = .8) + 
    # geom_label(aes(label = rank)) + 
    geom_label(aes(label = label_cor)) +
    my_scale_y(drop_val = remove_unused_predictors) +
    scale_fill_distiller(palette = "YlOrRd", direction = -1) + 
    # scale_fill_continuous(high = alpha("navy", 0.1), low = "red3") + 
    scale_alpha_continuous(range = c(0.1,0.8)) + 
    # my_scale_color_correlations() +
    scale_x_discrete(position = "top") +
    theme(axis.text.x = element_text(angle = 90), 
          panel.grid.major.x =  element_blank(),
          axis.text.y = element_text(size = 14),
          legend.background = element_rect(fill = as.character(theme_get()$panel.background$fill))) + 
    labs(x=NULL)
  
    return(plot_output)

}


```

```{r plot summary models, eval = FALSE}
plot_importance_all_models(list_models_environment[1:3])
plot_importance_all_models(list_models_environment)
```

# Figures summary WT / Fababean 

```{r}

models_yield_LER_wt_fababean <- list_models_environment[str_detect(list_models_environment, "(LER|yield).*(cereal|legume).*wt_fababean")]
plot_importance_all_models(models_yield_LER_wt_fababean)

models_yield_wt_fababean <- list_models_environment[str_detect(list_models_environment, "(yield).*(cereal|legume).*wt_fababean")]

options(theme_set(theme_bw() + theme( plot.background = element_rect(colour ="#fdf6e3", fill = "#fdf6e3"), panel.background = element_rect(colour ="#fdf6e3", fill = "#fdf6e3")) ))

(plot_rank_predictors_yield_wt_fababean <- plot_importance_all_models(models_yield_wt_fababean, vec_predictors = all_predictors[!str_detect(all_predictors, "species|")], remove_unused_predictors = TRUE) + theme(axis.text = element_text(size=  12)) + scale_x_discrete(labels = c("yield_cereal_wt_fababean - 8" = "Wheat's yield", "yield_legume_wt_fababean - 10" = "Faba bean's yield"), position = "top"))

(plot_rank_all_predictors_yield_wt_fababean <- plot_importance_all_models(models_yield_wt_fababean, vec_predictors = all_predictors[!str_detect(all_predictors, "species|")], remove_unused_predictors = FALSE) + theme(axis.text = element_text(size=  12)) + scale_x_discrete(labels = c("yield_cereal_wt_fababean - 8" = "Wheat's yield", "yield_legume_wt_fababean - 10" = "Faba bean's yield"), position = "top"))


models_PLER_wt_fababean <- list_models_environment[str_detect(list_models_environment, "(PLER).*(cereal|legume).*wt_fababean")]

(plot_rank_predictors_PLER_wt_fababean <- plot_importance_all_models(models_PLER_wt_fababean, vec_predictors = all_predictors[!str_detect(all_predictors, "species|")], remove_unused_predictors = TRUE) + theme(axis.text = element_text(size=  12)) + scale_x_discrete(labels = c("PLER_cereal_wt_fababean - 9" = "Wheat's PLER", "PLER_legume_wt_fababean - 1" = "Faba bean's PLER"), position = "top"))

(plot_rank_all_predictors_PLER_wt_fababean <- plot_importance_all_models(models_PLER_wt_fababean, vec_predictors = all_predictors[!str_detect(all_predictors, "species|")], remove_unused_predictors = FALSE) + theme(axis.text = element_text(size=  12)) + scale_x_discrete(labels = c("PLER_cereal_wt_fababean - 9" = "Wheat's PLER", "PLER_legume_wt_fababean - 1" = "Faba bean's PLER"), position = "top"))

```


```{r}

ggsave(filename = "figures/wt_fababean/plot_rank_predictors_yield_wt_fababean.png", plot = plot_rank_predictors_yield_wt_fababean,  dpi = 300, height = 18, width = 14, unit = "cm")
ggsave(filename = "figures/wt_fababean/plot_rank_all_predictors_yield_wt_fababean.png", plot = plot_rank_all_predictors_yield_wt_fababean,  dpi = 300, height = 18, width = 14, unit = "cm")

ggsave(filename = "figures/wt_fababean/plot_rank_predictors_PLER_wt_fababean.png", plot = plot_rank_predictors_PLER_wt_fababean,  dpi = 300, height = 18, width = 14, unit = "cm")
ggsave(filename = "figures/wt_fababean/plot_rank_all_predictors_PLER_wt_fababean.png", plot = plot_rank_all_predictors_PLER_wt_fababean,  dpi = 300, height = 18, width = 14, unit = "cm")

```




# Figures summary WT / Pea 


```{r}

models_yield_LER_wt_pea <- list_models_environment[str_detect(list_models_environment, "(LER|yield).*(cereal|legume).*wt_pea")]
plot_importance_all_models(models_yield_LER_wt_pea)

models_yield_wt_pea <- list_models_environment[str_detect(list_models_environment, "(yield).*(cereal|legume).*wt_pea")]


(plot_rank_predictors_yield_wt_pea <- plot_importance_all_models(models_yield_wt_pea, vec_predictors = all_predictors[!str_detect(all_predictors, "species|")], remove_unused_predictors = TRUE) + theme(axis.text = element_text(size=  12)) + scale_x_discrete(labels = c("yield_cereal_wt_pea - 10" = "Wheat's yield", "yield_legume_wt_pea - 9" = "Faba bean's yield"), position = "top"))

(plot_rank_all_predictors_yield_wt_pea <- plot_importance_all_models(models_yield_wt_pea, vec_predictors = all_predictors[!str_detect(all_predictors, "species|")], remove_unused_predictors = FALSE) + theme(axis.text = element_text(size=  12)) + scale_x_discrete(labels = c("yield_cereal_wt_pea - 10" = "Wheat's yield", "yield_legume_wt_pea - 9" = "Faba bean's yield"), position = "top"))


models_PLER_wt_pea <- list_models_environment[str_detect(list_models_environment, "(PLER).*(cereal|legume).*wt_pea")]

(plot_rank_predictors_PLER_wt_pea <- plot_importance_all_models(models_PLER_wt_pea, vec_predictors = all_predictors[!str_detect(all_predictors, "species|")], remove_unused_predictors = TRUE) + theme(axis.text = element_text(size=  12)) + scale_x_discrete(labels = c("PLER_cereal_wt_pea - 6" = "Wheat's PLER", "PLER_legume_wt_pea - 4" = "Pea's PLER"), position = "top"))

(plot_rank_all_predictors_PLER_wt_pea <- plot_importance_all_models(models_PLER_wt_pea, vec_predictors = all_predictors[!str_detect(all_predictors, "species|")], remove_unused_predictors = FALSE) + theme(axis.text = element_text(size=  12)) + scale_x_discrete(labels = c("PLER_cereal_wt_pea - 6" = "Wheat's PLER", "PLER_legume_wt_pea - 4" = "Pea's PLER"), position = "top"))

```



```{r}

ggsave(filename = "figures/wt_pea/plot_rank_predictors_yield_wt_pea.png", plot = plot_rank_predictors_yield_wt_pea,  dpi = 300, height = 18, width = 14, unit = "cm")
ggsave(filename = "figures/wt_pea/plot_rank_all_predictors_yield_wt_pea.png", plot = plot_rank_all_predictors_yield_wt_pea,  dpi = 300, height = 18, width = 14, unit = "cm")

ggsave(filename = "figures/wt_pea/plot_rank_predictors_PLER_wt_pea.png", plot = plot_rank_predictors_PLER_wt_pea,  dpi = 300, height = 18, width = 14, unit = "cm")
ggsave(filename = "figures/wt_pea/plot_rank_all_predictors_PLER_wt_pea.png", plot = plot_rank_all_predictors_PLER_wt_pea,  dpi = 300, height = 18, width = 14, unit = "cm")

```










```{r copy to presentation folder}

folder_modeling <- "C:/Users/rmahmoud/Documents/INRA/These/R_projects_phD/paper_modeling_intercrop/figures"
folder_presentations <- "C:/Users/rmahmoud/Documents/INRA/These/Presentations/meeting_22_11_2022/presentation_figures"
list_of_files <- list.files(folder_modeling, ".png$",recursive = TRUE, full.names = TRUE) 

file.copy(file.path(list_of_files), folder_presentations, overwrite = TRUE)
```


