---
title: "Marginal plots covariates"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r, include = FALSE, message=F}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = F,
  warning = F,
  message = F
)

```

```{r}

library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)
library(latex2exp)
library(forcats)


library(latex2exp)

# theme_set(theme_bw())

theme_set(ggthemes::theme_solarized() + theme(title = element_text(color = "black"),
                                              legend.text = element_text(color = "black"), axis.text = element_text(color = "black"))+ 
   theme(axis.title = element_text(size = 16),
         legend.title = element_text(size = 12),
         axis.text = element_text(size=  14),
         legend.text = element_text(size=  12 ),
         strip.text = element_text(size= 12),
         legend.position = "bottom"))

# ggthemr::ggthemr(palette = "dust")
# ggthemr::swatch()

# library(sjmisc)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")


```


```{r functions}
# Read all functions
list_functions <- list.files("R/scripts_functions", full.names = TRUE)
invisible(lapply(list_functions, source))


```


```{r read data }

data_all_diff <-  read_rds( "data/data_all_diff_with_imputations.rds")

data_BE_CE_SE <- read_rds("data/data_BE_CE_SE_LER.rds")

data_NNI <- read_rds("data/data_NNI.rds") %>%
  inner_join(data_all_diff %>% distinct(experiment_id, management)) %>% 
  shorten_exp_id() %>% 
  group_by(experiment_id, management) %>% 
  summarise(across(contains("NNI"), mean), .groups = "drop")
```


# Wheat turgidum / pea



```{r}



data_diff_wt_pea <- data_all_diff%>%
  left_join(data.intercrop::index %>% distinct(experiment_id, management, species_mix)) %>%
  filter(species_mix== "wheat_turgidum_pea") %>%
  shorten_exp_id()  %>% 
  group_by(experiment_id, management) %>% 
  summarise(across(where(is.numeric), mean), .groups = "drop")


index <- data.intercrop::index %>% 
  shorten_exp_id()%>%
  inner_join(data_diff_wt_pea %>% distinct(experiment_id, management) ) 



itk_wt_pea <- index %>% distinct(experiment_id, management, cultivar_mix, N_amount, mixing_pattern, mixture_design,  density_factor ) %>% 
  separate(cultivar_mix, into = c("cult_cereal", "cult_legume"), sep = "_")


```

## Yield cereal


```{r}
yield_cereal_wt_pea <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "cereal") %>%
  inner_join(data_diff_wt_pea %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_cereal = value)



data_plot_yield_cereal <- yield_cereal_wt_pea %>% 
  left_join(itk_wt_pea) %>% 
  left_join(data_diff_wt_pea) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, yield_cereal, colnames(itk_wt_pea),
         NNI_C = NNI_cereal, diff_max_LAI, cover = cover_before_800_normalized_tt, cover_before_800_normalized_tt_SC_cereal)


```

```{r, eval = FALSE}

# data_plot %>% 
#   ggplot(aes(x = NNI_C, y= yield_cereal))  +
#   geom_point(aes(color = cult_cereal), size =3 )

(plot_marginal_NNI_C_yield_cereal <- data_plot_yield_cereal %>% 
   ggplot(aes(x = NNI_C, y= yield_cereal))  +
   geom_point(aes(color = experiment_id, shape = cult_cereal, size =N_amount) ) + 
   scale_size_continuous(range = c(3,7)) + 
   labs(x = "NNI cereal", y = TeX("Yield cereal ($\\t.ha^{-1}$)")) + 
   # geom_ribbon(stat='smooth', method = "lm", se=TRUE, alpha=0.1, 
   #             aes(color = NULL, group = experiment_id)) +
   stat_smooth(method = "lm", aes(group = experiment_id, color = experiment_id), se = FALSE) )




ggsave(plot = plot_marginal_NNI_C_yield_cereal,  filename = "figures/wt_pea/marginal_plots/plot_marginal_NNI_C_yield_cereal.png", dpi = 300, height = 18, width = 12,  unit = "cm")

```



```{r, eval = FALSE}

# data_plot %>% 
#   ggplot(aes(x = NNI_C, y= yield_cereal))  +
#   geom_point(aes(color = cult_cereal), size =3 )

(plot_marginal_NNI_C_diff_max_LAI_yield_cereal <- data_plot_yield_cereal %>%
   pivot_longer(c(NNI_C, diff_max_LAI)) %>%
   mutate(name = fct_relevel(name, "diff_max_LAI", after = Inf)) %>% 
   ggplot(aes(x = value, y= yield_cereal))  +
   geom_point(aes(color = experiment_id, shape = cult_cereal, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("Yield cereal ($\\t.ha^{-1}$)"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   # geom_ribbon(stat='smooth', method = "lm", se=TRUE, alpha=0.1,
   #             aes(color = NULL, group = experiment_id)) +
   geom_line(stat = "smooth", 
             method = "lm", 
             aes(group = experiment_id, color = experiment_id),
             se = FALSE, alpha=  0.2, size = 2) +
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2)) )


ggsave(plot = plot_marginal_NNI_C_diff_max_LAI_yield_cereal,  filename = "figures/wt_pea/marginal_plots/plot_marginal_NNI_C_diff_max_LAI_yield_cereal.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```

```{r, eval = FALSE}

(plot_marginal_cover_yield_cereal <- data_plot_yield_cereal %>%
   rename(diff_IC_SC_cover = cover_before_800_normalized_tt_SC_cereal) %>% 
   pivot_longer(c(cover, diff_IC_SC_cover)) %>%
   mutate(name = fct_relevel(name, "cover", after = 0)) %>% 
   ggplot(aes(x = value, y= yield_cereal))  +
   geom_point(aes(color = experiment_id, shape = cult_cereal, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("Yield cereal ($\\t.ha^{-1}$)"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   # geom_ribbon(stat='smooth', method = "lm", se=TRUE, alpha=0.1,
   #             aes(color = NULL, group = experiment_id)) +
   # geom_line(stat = "smooth", 
   #           method = "lm", 
   #           aes(group = experiment_id, color = experiment_id),
   #           se = FALSE, alpha=  0.3, size = 2) +
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2)) )


ggsave(plot = plot_marginal_cover_yield_cereal,  filename = "figures/wt_pea/marginal_plots/plot_marginal_cover_yield_cereal.png", dpi = 300, height = 18, width = 28,  unit = "cm")
```






## PLER cereal


```{r}
PLER_cereal_wt_pea <- data_BE_CE_SE %>%
  shorten_exp_id() %>% 
  inner_join(data_diff_wt_pea %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, PLER_cereal)



data_plot_PLER_cereal <- PLER_cereal_wt_pea %>% 
  left_join(itk_wt_pea) %>% 
  left_join(data_diff_wt_pea) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, PLER_cereal, colnames(itk_wt_pea),
        diff_slope_height, diff_lambda_height, diff_asymp_height, diff_IC_SC_asymp_height_cereal)


```




```{r, eval = FALSE}

(plot_marginal_diff_asymp_height_PLER_cereal_wt_pea <- data_plot_PLER_cereal %>%
   pivot_longer(c(diff_IC_SC_asymp_height_cereal, diff_asymp_height)) %>%
   mutate(name = fct_relevel(name, "diff_IC_SC_asymp_height_cereal", after = 0)) %>%
   ggplot(aes(x = value, y= PLER_cereal))  +
   geom_point(aes(color = experiment_id, shape = cult_cereal, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("PLER cereal"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   geom_line(stat = "smooth", 
             method = "lm", 
             aes(),
             se = FALSE, alpha=  0.2, size = 2) +
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2)) )


ggsave(plot = plot_marginal_diff_asymp_height_PLER_cereal_wt_pea,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_asymp_height_PLER_cereal_wt_pea.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```





```{r, eval = FALSE}

(plot_marginal_diff_slope_height_diff_lambda_height_PLER_cereal_wt_pea <- data_plot_PLER_cereal %>%
   pivot_longer(c(diff_slope_height, diff_lambda_height)) %>%
   mutate(name = fct_relevel(name, "diff_slope_height", after = 0)) %>%
   ggplot(aes(x = value, y= PLER_cereal))  +
   geom_point(aes(color = experiment_id, shape = cult_cereal, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("PLER cereal"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   geom_line(stat = "smooth", 
             method = "lm", 
             aes(),
             se = FALSE, alpha=  0.2, size = 2) +
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2)) )


ggsave(plot = plot_marginal_diff_slope_height_diff_lambda_height_PLER_cereal_wt_pea,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_slope_height_diff_lambda_height_PLER_cereal_wt_pea.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```


## Yield legume




```{r}
yield_legume_wt_pea <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "legume") %>%
  inner_join(data_diff_wt_pea %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_legume = value) %>% 
  group_by(experiment_id, management) %>% 
  summarise(yield_legume = max(yield_legume), .groups = "drop")


data_diff_wt_pea %>% colnames


data_plot_yield_legume <- yield_legume_wt_pea %>% 
  left_join(itk_wt_pea) %>% 
  left_join(data_diff_wt_pea) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, yield_legume, colnames(itk_wt_pea),
         diff_IC_SC_slope_biomass_legume, diff_max_LAI, diff_slope_biomass, diff_IC_SC_cover = cover_before_800_normalized_tt_SC_legume,diff_IC_SC_lambda_biomass_legume, diff_asymp_height)


```



```{r, eval = FALSE}


(plot_marginal_diff_IC_SC_slope_biomass_diff_max_LAI_yield_legume <- data_plot_yield_legume %>%
   pivot_longer(c(diff_IC_SC_slope_biomass_legume, diff_max_LAI)) %>%
   mutate(name = fct_relevel(name, "diff_max_LAI", after = Inf)) %>% 
   ggplot(aes(x = value, y= yield_legume))  +
   geom_point(aes(color = experiment_id, shape = cult_legume, size =N_amount) ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("Yield legume ($\\t.ha^{-1}$)"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL, alpha = NULL) +
   # geom_ribbon(stat='smooth', method = "lm", se=TRUE, alpha=0.1,
   #             aes(color = NULL, group = experiment_id)) +
   geom_line(stat = "smooth", 
             method = "lm", 
             aes(group = experiment_id, color = experiment_id, alpha= name),
             se = FALSE,  size = 2) +
   # scale_alpha_discrete(values= c("diff_IC_SC_slope_biomass_legume" = 0, "diff_max_LAI" = .3)) +
   scale_alpha_discrete(range = c(0,0.3)) + 
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2), shape = guide_legend(nrow = 2), alpha = "none") )


ggsave(plot = plot_marginal_diff_IC_SC_slope_biomass_diff_max_LAI_yield_legume,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_IC_SC_slope_biomass_diff_max_LAI_yield_legume.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```


```{r, eval = FALSE}


(plot_marginal_diff_IC_SC_slope_biomass_diff_slope_biomass_yield_legume <- data_plot_yield_legume %>%
   pivot_longer(c(diff_IC_SC_slope_biomass_legume, diff_slope_biomass)) %>%
   mutate(name = fct_relevel(name, "diff_slope_biomass", after = Inf)) %>% 
   ggplot(aes(x = value, y= yield_legume))  +
   geom_point(aes(color = experiment_id, shape = cult_legume, size =N_amount) ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("Yield legume $  ( \\t.ha^{-1})$"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL, alpha = NULL) +
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2), shape = guide_legend(nrow = 2), alpha = "none") )


ggsave(plot = plot_marginal_diff_IC_SC_slope_biomass_diff_max_LAI_yield_legume,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_IC_SC_slope_biomass_diff_slope_biomass_yield_legume.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```





```{r, eval = FALSE}


(plot_marginal_diff_max_LAI_diff_IC_SC_cover_yield_legume <- data_plot_yield_legume %>%
   pivot_longer(c(diff_max_LAI, diff_IC_SC_cover)) %>%
   mutate(name = fct_relevel(name, "diff_IC_SC_cover", after = Inf)) %>% 
   ggplot(aes(x = value, y= yield_legume))  +
   geom_point(aes(color = experiment_id, shape = cult_legume, size =N_amount) ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("Yield legume $  ( \\t.ha^{-1})$"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL, alpha = NULL) +
   geom_line(stat = "smooth",
             method = "lm",
             aes(group = experiment_id, color = experiment_id, alpha= name),
             se = FALSE,  size = 2) +
   scale_alpha_discrete(range = c(0.3,0)) +
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2), shape = guide_legend(nrow = 2), alpha = "none") )


ggsave(plot = plot_marginal_diff_max_LAI_diff_IC_SC_cover_yield_legume,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_max_LAI_diff_IC_SC_cover_yield_legume.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```






## PLER legume


```{r}
PLER_legume_wt_pea <- data_BE_CE_SE %>%
  shorten_exp_id() %>% 
  inner_join(data_diff_wt_pea %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, PLER_legume)



data_plot_PLER_legume <- PLER_legume_wt_pea %>% 
  left_join(itk_wt_pea) %>% 
  left_join(data_diff_wt_pea) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, PLER_legume, colnames(itk_wt_pea),
         diff_IC_SC_slope_biomass_legume, diff_max_LAI, diff_slope_biomass, diff_IC_SC_cover = cover_before_800_normalized_tt_SC_legume,diff_IC_SC_lambda_biomass_legume, diff_asymp_height)



```




```{r, eval = FALSE}

(plot_marginal_diff_slope_biomass_PLER_legume_wt_pea <- data_plot_PLER_legume %>%
   pivot_longer(c(diff_IC_SC_slope_biomass_legume, diff_slope_biomass)) %>%
   mutate(name = fct_relevel(name, "diff_IC_SC_slope_biomass_legume", after = 0)) %>%
   ggplot(aes(x = value, y= PLER_legume))  +
   geom_point(aes(color = experiment_id, shape = cult_legume, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("PLER legume"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   geom_line(stat = "smooth",
             method = "lm",
             aes(group = experiment_id, color = experiment_id),
             se = FALSE, alpha=  0.2, size = 2) +
    geom_line(stat = "smooth",
             method = "lm",
             aes(),
             se = FALSE, alpha=  0.05, size = 2) +
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2), shape = guide_legend(nrow = 2)) )


ggsave(plot = plot_marginal_diff_slope_biomass_PLER_legume_wt_pea,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_slope_biomass_PLER_legume_wt_pea.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```


```{r, eval = FALSE}

(plot_marginal_diff_max_LAI_diff_asymp_height_PLER_legume_wt_pea <- data_plot_PLER_legume %>%
   pivot_longer(c(diff_max_LAI, diff_asymp_height)) %>%
   mutate(name = fct_relevel(name, "diff_max_LAI", after = 0)) %>%
   ggplot(aes(x = value, y= PLER_legume))  +
   geom_point(aes(color = experiment_id, shape = cult_legume, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("PLER legume"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   geom_line(stat = "smooth",
             method = "lm",
             aes(group = experiment_id, color = experiment_id),
             se = FALSE, alpha=  0.2, size = 2) +
    geom_line(stat = "smooth",
             method = "lm",
             aes(),
             se = FALSE, alpha=  0.05, size = 2) +
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2), shape = guide_legend(nrow = 2)) )


ggsave(plot = plot_marginal_diff_max_LAI_diff_asymp_height_PLER_legume_wt_pea,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_max_LAI_diff_asymp_height_PLER_legume_wt_pea.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```



```{r, eval = FALSE}

(plot_marginal_diff_slope_height_diff_lambda_height_PLER_legume_wt_pea <- data_plot_PLER_legume %>%
   pivot_longer(c(diff_slope_height, diff_lambda_height)) %>%
   mutate(name = fct_relevel(name, "diff_slope_height", after = 0)) %>%
   ggplot(aes(x = value, y= PLER_legume))  +
   geom_point(aes(color = experiment_id, shape = cult_legume, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("PLER legume"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   geom_line(stat = "smooth", 
             method = "lm", 
             aes(),
             se = FALSE, alpha=  0.2, size = 2) +
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2)) )


ggsave(plot = plot_marginal_diff_slope_height_diff_lambda_height_PLER_legume_wt_pea,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_slope_height_diff_lambda_height_PLER_legume_wt_pea.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```

# Wheat turgidum / faba bean



```{r}



data_diff_wt_fababean <- data_all_diff%>%
  left_join(data.intercrop::index %>% distinct(experiment_id, management, species_mix)) %>%
  filter(species_mix== "wheat_turgidum_fababean") %>%
  shorten_exp_id()  %>% 
  group_by(experiment_id, management) %>% 
  summarise(across(where(is.numeric), mean), .groups = "drop")


index <- data.intercrop::index %>% 
  shorten_exp_id()%>%
  inner_join(data_diff_wt_fababean %>% distinct(experiment_id, management) ) 



itk_wt_fababean <- index %>% distinct(experiment_id, management, cultivar_mix, N_amount, mixing_pattern, mixture_design,  density_factor ) %>% 
  separate(cultivar_mix, into = c("cult_cereal", "cult_legume"), sep = "_")


```

## Yield cereal


```{r}
yield_cereal_wt_fababean <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "cereal") %>%
  inner_join(data_diff_wt_fababean %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_cereal = value)



data_plot_yield_cereal <- yield_cereal_wt_fababean %>% 
  left_join(itk_wt_fababean) %>% 
  left_join(data_diff_wt_fababean) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, yield_cereal, colnames(itk_wt_fababean),
        diff_slope_biomass,diff_lambda_biomass, diff_asymp_height, diff_max_LAI, cover = cover_before_800_normalized_tt, cover_before_800_normalized_tt_SC_cereal, cereal_asymp_height)


```




```{r, eval = FALSE}

(plot_marginal_diff_slope_biomass_diff_lambda_biomass_yield_cereal_wt_fababean <- data_plot_yield_cereal %>%
   pivot_longer(c(diff_slope_biomass, diff_lambda_biomass)) %>%
   mutate(name = fct_relevel(name, "diff_slope_biomass", after = 0)) %>%
   ggplot(aes(x = value, y= yield_cereal))  +
   geom_point(aes(color = experiment_id, shape = cult_cereal, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("Yield cereal ($\\t.ha^{-1}$)"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   geom_line(stat = "smooth", 
             method = "lm", 
             aes(group = experiment_id, color = experiment_id),
             se = FALSE, alpha=  0.2, size = 2) +
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2)) )


ggsave(plot = plot_marginal_diff_slope_biomass_diff_lambda_biomass_yield_cereal_wt_fababean,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_slope_biomass_diff_lambda_biomass_yield_cereal_wt_fababean.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```





```{r, eval = FALSE}

(plot_marginal_diff_asymp_height_diff_max_LAI_yield_cereal_wt_fababean <- data_plot_yield_cereal %>%
   pivot_longer(c(diff_asymp_height,  diff_max_LAI)) %>%
   mutate(name = fct_relevel(name, "diff_max_LAI", after = 0)) %>%
   ggplot(aes(x = value, y= yield_cereal))  +
   geom_point(aes(color = experiment_id, shape = cult_cereal, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("Yield cereal ($\\t.ha^{-1}$)"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   # geom_ribbon(stat='smooth', method = "lm", se=TRUE, alpha=0.1,
   #             aes(color = NULL, group = experiment_id)) +
   geom_line(stat = "smooth",
             method = "lm",
             aes(group = experiment_id, color = experiment_id),
             se = FALSE, alpha=  0.2, size = 2) +
   geom_line(stat = "smooth",
             method = "lm",
             aes(),
             se = FALSE, alpha=  0.1, size = 2) +
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2))) 


ggsave(plot = plot_marginal_diff_asymp_height_diff_max_LAI_yield_cereal_wt_fababean,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_asymp_height_diff_max_LAI_yield_cereal_wt_fababean.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```




## PLER cereal


```{r}
PLER_cereal_wt_fababean <- data_BE_CE_SE %>%
  shorten_exp_id() %>% 
  inner_join(data_diff_wt_fababean %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, PLER_cereal)



data_plot_PLER_cereal <- PLER_cereal_wt_fababean %>% 
  left_join(itk_wt_fababean) %>% 
  left_join(data_diff_wt_fababean) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, PLER_cereal, colnames(itk_wt_fababean),
        diff_slope_biomass,NNI_C = NNI_cereal, diff_asymp_height, diff_max_LAI)


```




```{r, eval = FALSE}

(plot_marginal_diff_slope_biomass_NNI_C_PLER_cereal_wt_fababean <- data_plot_PLER_cereal %>%
   pivot_longer(c(diff_slope_biomass, NNI_C)) %>%
   mutate(name = fct_relevel(name, "diff_slope_biomass", after = 0)) %>%
   ggplot(aes(x = value, y= PLER_cereal))  +
   geom_point(aes(color = experiment_id, shape = cult_cereal, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("PLER cereal"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   # geom_ribbon(stat='smooth', method = "lm", se=TRUE, alpha=0.1,
   #             aes(color = NULL, group = experiment_id)) +
   geom_line(stat = "smooth", 
             method = "lm", 
             aes(group = experiment_id, color = experiment_id),
             se = FALSE, alpha=  0.2, size = 2) +
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2)) )


ggsave(plot = plot_marginal_diff_slope_biomass_NNI_C_PLER_cereal_wt_fababean,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_slope_biomass_NNI_C_PLER_cereal_wt_fababean.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```




```{r, eval = FALSE}

(plot_marginal_diff_asymp_height_diff_max_LAI_PLER_cereal_wt_fababean <- data_plot_PLER_cereal %>%
   pivot_longer(c(diff_asymp_height, diff_max_LAI)) %>%
   mutate(name = fct_relevel(name, "diff_asymp_height", after = 0)) %>%
   ggplot(aes(x = value, y= PLER_cereal))  +
   geom_point(aes(color = experiment_id, shape = cult_cereal, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("PLER cereal"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   # geom_ribbon(stat='smooth', method = "lm", se=TRUE, alpha=0.1,
   #             aes(color = NULL, group = experiment_id)) +
   geom_line(stat = "smooth", 
             method = "lm", 
             aes(),
             se = FALSE, alpha=  0.2, size = 2) +
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2)) )


ggsave(plot = plot_marginal_diff_asymp_height_diff_max_LAI_PLER_cereal_wt_fababean,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_asymp_height_diff_max_LAI_PLER_cereal_wt_fababean.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```





## Yield legume


```{r}
yield_legume_wt_fababean <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "legume") %>%
  inner_join(data_diff_wt_fababean %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_legume = value)



data_plot_yield_legume <- yield_legume_wt_fababean %>% 
  left_join(itk_wt_fababean) %>% 
  left_join(data_diff_wt_fababean) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, yield_legume, colnames(itk_wt_fababean),
        diff_slope_biomass,diff_lambda_biomass, diff_asymp_height, diff_max_LAI, diff_slope_height, cover_before_800_normalized_tt_SC_legume)


```




```{r, eval = FALSE}

(plot_marginal_diff_slope_biomass_diff_max_LAI_yield_legume_wt_fababean <- data_plot_yield_legume %>%
   pivot_longer(c(diff_slope_biomass, diff_max_LAI)) %>%
   mutate(name = fct_relevel(name, "diff_max_LAI", after = Inf)) %>%
   ggplot(aes(x = value, y= yield_legume))  +
   geom_point(aes(color = experiment_id, shape = cult_legume, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("Yield legume ($\\t.ha^{-1}$)"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   # geom_ribbon(stat='smooth', method = "lm", se=TRUE, alpha=0.1,
   #             aes(color = NULL, group = experiment_id)) +
   geom_line(stat = "smooth", 
             method = "lm", 
             aes(group = experiment_id, color = experiment_id),
             se = FALSE, alpha=  0.2, size = 2) +
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2), shape = guide_legend(nrow = 2)) )


ggsave(plot = plot_marginal_diff_slope_biomass_diff_max_LAI_yield_legume_wt_fababean,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_slope_biomass_diff_max_LAI_yield_legume_wt_fababean.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```





```{r, eval = FALSE}


(plot_marginal_diff_asymp_height_diff_slope_height_yield_legume_wt_fababean <- data_plot_yield_legume %>%
   pivot_longer(c(diff_asymp_height,  diff_slope_height)) %>%
   mutate(name = fct_relevel(name, "diff_asymp_height", after = 0)) %>%
   ggplot(aes(x = value, y= yield_legume))  +
   geom_point(aes(color = experiment_id, shape = cult_legume, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("Yield legume ($\\t.ha^{-1}$)"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   # geom_ribbon(stat='smooth', method = "lm", se=TRUE, alpha=0.1,
   #             aes(color = NULL, group = experiment_id)) +
   geom_line(stat = "smooth",
             method = "lm",
             aes(group = experiment_id, color = experiment_id),
             se = FALSE, alpha=  0.2, size = 2) +
   geom_line(stat = "smooth",
             method = "lm",
             aes(),
             se = FALSE, alpha=  0.1, size = 2) +
   facet_wrap(name~., scales = "free", ncol = 2) +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2), shape = guide_legend(nrow = 2))) 


ggsave(plot = plot_marginal_diff_asymp_height_diff_slope_height_yield_legume_wt_fababean,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_asymp_height_diff_slope_height_yield_legume_wt_fababean.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```





# All legumes



```{r}



data_diff_all_species <- data_all_diff%>%
  left_join(data.intercrop::index %>% distinct(experiment_id, management, species_mix)) %>%
  shorten_exp_id()  %>% 
  group_by(experiment_id, management) %>% 
  summarise(across(where(is.numeric), mean), .groups = "drop")


index <- data.intercrop::index %>% 
  shorten_exp_id()%>%
  inner_join(data_diff_all_species %>% distinct(experiment_id, management) ) 



itk_all_species <- index %>% distinct(experiment_id, management, cultivar_mix, N_amount, mixing_pattern, mixture_design,  density_factor, species_mix ) %>% 
  separate(cultivar_mix, into = c("cult_cereal", "cult_legume"), sep = "_")


```

## Yield cereal


```{r}
yield_cereal_all_species <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "cereal") %>%
  inner_join(data_diff_all_species %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_cereal = value)



data_plot_yield_cereal <- yield_cereal_all_species %>% 
  left_join(itk_all_species) %>% 
  left_join(data_diff_all_species) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, yield_cereal, colnames(itk_all_species),
        NNI_C = NNI_cereal, diff_max_LAI, cover = cover_before_800_normalized_tt, diff_IC_SC_cover_C = cover_before_800_normalized_tt_SC_cereal, diff_slope_biomass) %>% 
  mutate(species_mix = fct_recode(species_mix, "Blé dur / Féverole" = "wheat_turgidum_fababean", "Blé dur / Pois" = "wheat_turgidum_pea"))


```



```{r, eval = FALSE}

(plot_marginal_NNI_C_diff_max_LAI_yield_cereal_all_species <- data_plot_yield_cereal %>%
   pivot_longer(c(NNI_C, diff_max_LAI)) %>%
   mutate(name = fct_relevel(name, "NNI_C", after = 0)) %>%
   ggplot(aes(x = value, y= yield_cereal))  +
   geom_point(aes(color = experiment_id, shape = cult_cereal, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("Yield cereal ($\\t.ha^{-1}$)"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   geom_line(stat = "smooth", 
             method = "lm", 
             aes(group = experiment_id, color = experiment_id),
             se = FALSE, alpha=  0.2, size = 2) +
   # facet_wrap(name~species_mix, scales = "free", ncol = 2) +
   facet_grid(species_mix~name, scales = "free") +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2)) )


ggsave(plot = plot_marginal_NNI_C_diff_max_LAI_yield_cereal_all_species,  filename = "figures/wt_pea/marginal_plots/plot_marginal_NNI_C_diff_max_LAI_yield_cereal_all_species.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```



```{r, eval = FALSE}

(plot_marginal_cover_yield_cereal_all_species <- data_plot_yield_cereal %>%
   pivot_longer(c(cover, diff_IC_SC_cover_C)) %>%
   mutate(name = fct_relevel(name, "cover", after = 0)) %>%
   ggplot(aes(x = value, y= yield_cereal))  +
   geom_point(aes(color = experiment_id, shape = cult_cereal, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("Yield cereal ($\\t.ha^{-1}$)"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   geom_line(stat = "smooth", 
             method = "lm", 
             aes(group = experiment_id, color = experiment_id),
             se = FALSE, alpha=  0.2, size = 2) +
   facet_grid(species_mix~name, scales = "free") +
   guides(colour = guide_legend(nrow = 2), size = guide_legend(nrow = 2)) )


# ggsave(plot = plot_marginal_NNI_C_diff_max_LAI_yield_cereal_all_species,  filename = "figures/wt_pea/marginal_plots/plot_marginal_NNI_C_diff_max_LAI_yield_cereal_all_species.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```



## Yield legume


```{r}
yield_legume_all_species <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "legume") %>%
  inner_join(data_diff_all_species %>% distinct(experiment_id, management)) %>% 
  group_by(experiment_id, management) %>% 
  summarise(value = max(value), .groups = "drop") %>% 
  distinct(experiment_id, management, yield_legume = value)



data_plot_yield_legume <- yield_legume_all_species %>% 
  left_join(itk_all_species) %>% 
  left_join(data_diff_all_species) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, yield_legume, colnames(itk_all_species),
        diff_asymp_height, diff_max_LAI, cover = cover_before_800_normalized_tt, diff_IC_SC_cover_L = cover_before_800_normalized_tt_SC_legume, diff_slope_biomass) %>% 
  mutate(species_mix = fct_recode(species_mix, "Blé dur / Féverole" = "wheat_turgidum_fababean", "Blé dur / Pois" = "wheat_turgidum_pea"))


```



```{r, eval = FALSE}

(plot_marginal_diff_slope_biomass_diff_max_LAI_yield_legume_all_species <- data_plot_yield_legume %>%
   pivot_longer(c(diff_slope_biomass, diff_max_LAI)) %>%
   mutate(name = fct_relevel(name, "diff_max_LAI", after = 0)) %>%
   ggplot(aes(x = value, y= yield_legume))  +
   geom_point(aes(color = experiment_id, shape = cult_legume, size =N_amount), alpha= .8 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("Yield legume ($\\t.ha^{-1}$)"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   geom_line(stat = "smooth", 
             method = "lm", 
             aes(group = experiment_id, color = experiment_id),
             se = FALSE, alpha=  0.2, size = 2) +
   scale_shape_manual(values=seq(0,8)) + 
   facet_grid(species_mix~name, scales = "free") +
   guides(colour = guide_legend(nrow = 3), size = guide_legend(nrow = 2), shape = guide_legend(nrow = 3)))


ggsave(plot = plot_marginal_diff_slope_biomass_diff_max_LAI_yield_legume_all_species,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_slope_biomass_diff_max_LAI_yield_legume_all_species.png", dpi = 300, height = 18, width = 28,  unit = "cm")

```


```{r, eval = FALSE}

(plot_marginal_diff_asymp_height_diff_cover_yield_legume_all_species <- data_plot_yield_legume %>%
   pivot_longer(c(diff_asymp_height, diff_IC_SC_cover_L)) %>%
   mutate(name = fct_relevel(name, "diff_asymp_height", after = 0)) %>%
   ggplot(aes(x = value, y= yield_legume))  +
   geom_point(aes(color = experiment_id, shape = cult_legume, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = NULL, y = TeX("Yield legume ($\\t.ha^{-1}$)"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   geom_line(stat = "smooth", 
             method = "lm", 
             aes(group = experiment_id, color = experiment_id),
             se = FALSE, alpha=  0.2, size = 2) +
   scale_shape_manual(values=seq(0,8)) + 
   facet_grid(species_mix~name, scales = "free") +
   # scale_shape_discrete(breaks=c('castel', 'irena', 'diver', 'nordica', ...) + 
   guides(colour = guide_legend(nrow = 3), size = guide_legend(nrow = 2), shape = guide_legend(nrow = 3)))


ggsave(plot = plot_marginal_diff_asymp_height_diff_cover_yield_legume_all_species,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_asymp_height_diff_cover_yield_legume_all_species.png", dpi = 300, height = 18, width = 28,  unit = "cm")

# , breaks = c("castel", "irena", "diver", "nordica", "lucy", "aoph10", "geronimo", 
# "isard", "kazar")

```


## Yield both



```{r}
yield_all_species <- yield_cereal_all_species %>% left_join(yield_legume_all_species)



data_plot_yield_all_species <- yield_all_species %>% 
  left_join(itk_all_species) %>% 
  left_join(data_diff_all_species) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, yield_cereal, yield_legume, colnames(itk_all_species),
        NNI_C = NNI_cereal, NNI_L = NNI_legume, diff_max_LAI, cover = cover_before_800_normalized_tt, diff_slope_biomass) %>%   mutate(species_mix = fct_recode(species_mix, "Blé dur / Féverole" = "wheat_turgidum_fababean", "Blé dur / Pois" = "wheat_turgidum_pea"))


```

```{r, eval = FALSE}

(plot_marginal_diff_max_LAI_yield_all_species <- data_plot_yield_all_species %>%
   pivot_longer(contains("yield")) %>%
   ggplot(aes(x = diff_max_LAI, y= value))  +
   geom_point(aes(color = experiment_id, shape = cult_legume, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = TeX("$\\Delta_{max}LAI$"), y = TeX("Yield ($\\t.ha^{-1}$)"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   geom_line(stat = "smooth", 
             method = "lm", 
             aes(group = experiment_id, color = experiment_id),
             se = FALSE, alpha=  0.2, size = 2) +
   scale_shape_manual(values=seq(0,8)) + 
   facet_grid(species_mix~name, scales = "free") +
   # scale_shape_discrete(breaks=c('castel', 'irena', 'diver', 'nordica', ...) + 
   guides(colour = guide_legend(nrow = 3), size = guide_legend(nrow = 2), shape = guide_legend(nrow = 3)))



(plot_marginal_diff_slope_biomass_yield_all_species <- data_plot_yield_all_species %>%
   pivot_longer(contains("yield")) %>%
   ggplot(aes(x = diff_slope_biomass, y= value))  +
   geom_point(aes(color = experiment_id, shape = cult_legume, size =N_amount), alpha= .6 ) +
   scale_size_continuous(range = c(3,7)) +
   labs(x = TeX("$\\Delta_{\\mu}biom$"), y = TeX("Yield ($\\t.ha^{-1}$)"), size = TeX("N ($\\kg.ha^{-1}$)"), shape = NULL, color = NULL) +
   geom_line(stat = "smooth", 
             method = "lm", 
             aes(group = experiment_id, color = experiment_id),
             se = FALSE, alpha=  0.2, size = 2) +
   scale_shape_manual(values=seq(0,8)) + 
   facet_grid(species_mix~name, scales = "free") +
   # scale_shape_discrete(breaks=c('castel', 'irena', 'diver', 'nordica', ...) + 
   guides(colour = guide_legend(nrow = 3), size = guide_legend(nrow = 2), shape = guide_legend(nrow = 3)))


ggsave(plot = plot_marginal_diff_max_LAI_yield_all_species,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_max_LAI_yield_all_species.png", dpi = 350, height = 16, width = 20,  unit = "cm")

ggsave(plot = plot_marginal_diff_slope_biomass_yield_all_species,  filename = "figures/wt_pea/marginal_plots/plot_marginal_diff_slope_biomass_yield_all_species.png", dpi = 300, height = 16, width = 20,  unit = "cm")
```




# Transfer plots



```{r}

folder_modeling <- "C:/Users/rmahmoud/Documents/INRA/These/R_projects_phD/paper_modeling_intercrop/figures"
folder_presentations <- "C:/Users/rmahmoud/Documents/INRA/These/Presentations/meeting_22_11_2022/presentation_figures"
list_of_files <- list.files(folder_modeling, "(.*)marginal(.*).png$",recursive = TRUE, full.names = TRUE) 

file.copy(file.path(list_of_files), folder_presentations, overwrite = TRUE)
```



```{r}

data.qualitative::legumes %>% filter(species == "fababean") %>% distinct(species, cultivar,  height, crop_height)

data.qualitative::legumes %>% filter(species == "fababean", !is.na(height), cultivar != "columbo") %>% distinct(species, cultivar,  height, crop_height)


data.qualitative::cereals %>% filter(species == "durum_wheat", cultivar %in% c("L1823", "acalou", "nefer", "neodur","orjaune", "sculptur"
))

```

