---
title: "Script 22 / 11"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r, include = FALSE, message=F}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = F,
  warning = F,
  message = F
)

```

```{r}

library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)
library(latex2exp)
library(forcats)
library(nlme)


library(latex2exp)

# theme_set(theme_bw())

theme_set(ggthemes::theme_solarized() + theme(title = element_text(color = "black"),
                                              legend.text = element_text(color = "black"), axis.text = element_text(color = "black"))+ 
   theme(axis.title = element_text(size = 16),
         legend.title = element_text(size = 12),
         axis.text = element_text(size=  14),
         legend.text = element_text(size=  12 ),
         strip.text = element_text(size= 12),
         legend.position = "bottom"))

# ggthemr::ggthemr(palette = "dust")
# ggthemr::swatch()

# library(sjmisc)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")


```


```{r functions}
# Read all functions
list_functions <- list.files("R/scripts_functions", full.names = TRUE)
invisible(lapply(list_functions, source))






get_variance_random_effect_nlme <- function(gm){
  
  vc <- VarCorr(gm$mixed.model)
  suppressWarnings(storage.mode(vc) <- "numeric")
  variance_random_effect <- (vc[1,"StdDev"])^2
 
  
}

get_random_effect_nlme <- function(gm, data_variance_random_effect){

  random_effects <- gm$mixed.model %>%
    ranef %>%
    as_tibble(rownames = "experiment_id") 
}



function_plot_random_effects <- function(data = data_random_effects, size_text = 24){
   plot_output <- data %>% 
     ggplot(aes(y= experiment_id, x = mean_intercept)) + 
     geom_point() + 
     theme(axis.text.y = element_text(angle = 45, hjust = 0.5), text = element_text(size = size_text)) + 
     labs(y = "Experiment (site x year)", x= TeX("Random intercept (mean $\\pm$ sd) "), title = "Random effects plot") + 
     geom_errorbar(aes(xmin = mean_intercept - sd_total, xmax =  mean_intercept + sd_total), width= 0) +
     geom_vline(xintercept = 0, linetype = "dashed", size=  0.5) 
   return(plot_output)
}




```




```{r read data }

data_all_diff <-  read_rds( "data/data_all_diff_with_imputations.rds")

data_BE_CE_SE <- read_rds("data/data_BE_CE_SE_LER.rds")

data_NNI <- read_rds("data/data_NNI.rds") %>%
  inner_join(data_all_diff %>% distinct(experiment_id, management)) %>% 
  shorten_exp_id() %>% 
  group_by(experiment_id, management) %>% 
  summarise(across(contains("NNI"), mean), .groups = "drop")
```


# Get models and plot analysis


```{r}


yield_cereal_wt_pea <- read_rds("models/wt_pea/yield_cereal_wt_pea.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 200)

n_models <- length(unique(yield_cereal_wt_pea$.imp))

fitted_observed_cereal_wt_pea <- fun_get_fitted_observed(yield_cereal_wt_pea, y= "yield_cereal")

summary_fitted_observed_cereal_wt_pea <- fitted_observed_cereal_wt_pea %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")



data_variance_random_effect <- yield_cereal_wt_pea %>% 
  mutate(variance_random_effect = map(mod.gmerf, get_variance_random_effect_nlme)) %>% 
  unnest(variance_random_effect) %>% 
  summarise(mean_variance_random_effect = mean(variance_random_effect),
            between_imputation_variance = (1/(n() -1 ))*sum((variance_random_effect - mean_variance_random_effect)^2),
            variance_due_to_finite_imputation = between_imputation_variance/n(),
            total_variance=  mean_variance_random_effect +  between_imputation_variance + variance_due_to_finite_imputation,
            sd_total = sqrt(total_variance), n = n()) %>% 
  mutate(across(c(mean_variance_random_effect, between_imputation_variance, variance_due_to_finite_imputation), ~.x/total_variance, .names = "{.col}_prop")) %>% 
  mutate(across(contains("_prop"), ~.x*sd_total, .names = "sd_approx_{.col}"))

data_variance_random_effect


data_random_effects <- yield_cereal_wt_pea %>% 
  mutate(random_effects = map(mod.gmerf, get_random_effect_nlme)) %>% 
  unnest(random_effects) %>% 
  left_join(data_variance_random_effect, by =character()) %>%
  mutate(experiment_id = stringr::str_replace_all(experiment_id, "marinette_1_|SGs_|TO_|ZN_|TE_","")) %>% 
  mutate(experiment_id = stringr::str_replace_all(experiment_id, "Auzeville","Auz")) %>% 
  group_by(experiment_id) %>%
  summarise(mean_intercept = mean(`(Intercept)` ), sd_total = unique(sd_total), .groups = "drop") %>%
     mutate(experiment_id = forcats::fct_reorder(experiment_id, mean_intercept))
 

(plot_random_effect <- function_plot_random_effects(size_text = 15))

```




```{r}


yield_legume_wt_fababean <- read_rds("models/wt_fababean/yield_legume_wt_fababean.rds") %>% 
  mutate(n_iterations = map_dbl(mod.gmerf, ~.x$n.iteration)) %>% 
  filter(n_iterations < 200)

n_models <- length(unique(yield_legume_wt_fababean$.imp))

fitted_observed_cereal_wt_fababean <- fun_get_fitted_observed(yield_legume_wt_fababean, y= "yield_cereal")

summary_fitted_observed_cereal_wt_fababean <- fitted_observed_cereal_wt_fababean %>%
  group_by(id_obs) %>% 
  summarise(mean_fitted = mean(fitted), observed = unique(observed), .groups = "drop")



data_variance_random_effect <- yield_legume_wt_fababean %>% 
  mutate(variance_random_effect = map(mod.gmerf, get_variance_random_effect_nlme)) %>% 
  unnest(variance_random_effect) %>% 
  summarise(mean_variance_random_effect = mean(variance_random_effect),
            between_imputation_variance = (1/(n() -1 ))*sum((variance_random_effect - mean_variance_random_effect)^2),
            variance_due_to_finite_imputation = between_imputation_variance/n(),
            total_variance=  mean_variance_random_effect +  between_imputation_variance + variance_due_to_finite_imputation,
            sd_total = sqrt(total_variance), n = n()) %>% 
  mutate(across(c(mean_variance_random_effect, between_imputation_variance, variance_due_to_finite_imputation), ~.x/total_variance, .names = "{.col}_prop")) %>% 
  mutate(across(contains("_prop"), ~.x*sd_total, .names = "sd_approx_{.col}"))

data_variance_random_effect


data_random_effects <- yield_legume_wt_fababean %>% 
  mutate(random_effects = map(mod.gmerf, get_random_effect_nlme)) %>% 
  unnest(random_effects) %>% 
  left_join(data_variance_random_effect, by =character()) %>%
  mutate(experiment_id = stringr::str_replace_all(experiment_id, "marinette_1_|SGs_|TO_|ZN_|TE_","")) %>% 
  mutate(experiment_id = stringr::str_replace_all(experiment_id, "Auzeville","Auz")) %>% 
  group_by(experiment_id) %>%
  summarise(mean_intercept = mean(`(Intercept)` ), sd_total = unique(sd_total), .groups = "drop") %>%
     mutate(experiment_id = forcats::fct_reorder(experiment_id, mean_intercept))
 

(plot_random_effect <- function_plot_random_effects(size_text = 15))

```



```{r}


(fitted_vs_obs_yield_legume_wt_fababean <- plot_fitted_vs_observed(fitted_observed_legume_wt_fababean, summary_fitted_observed_legume_wt_fababean, my_title = "Legume's yield: fitted vs observed",lab_y = TeX("Fitted($t.ha^{-1}$)"), lab_x = TeX("Observed ($t.ha^{-1}$)"), size_text = 16))

variance_decomposition(fitted_observed_legume_wt_fababean)


get_error(yield_legume_wt_fababean, y = "yield_legume")

evaluate_error(summary_fitted_observed_legume_wt_fababean, fitted = "mean_fitted")


(plot_importance_yield_legume_wt_fababean <- plot_importance(yield_legume_wt_fababean, threshold = n_models, y= "yield_legume", size_text = 16))


```



# Wheat turgidum / pea



```{r}



data_diff_wt_pea <- data_all_diff%>%
  left_join(data.intercrop::index %>% distinct(experiment_id, management, species_mix)) %>%
  filter(species_mix== "wheat_turgidum_pea") %>%
  shorten_exp_id()  %>% 
  group_by(experiment_id, management) %>% 
  summarise(across(where(is.numeric), mean), .groups = "drop")


index <- data.intercrop::index %>% 
  shorten_exp_id()%>%
  inner_join(data_diff_wt_pea %>% distinct(experiment_id, management) ) 



itk_wt_pea <- index %>% distinct(experiment_id, management, cultivar_mix, N_amount, mixing_pattern, mixture_design,  density_factor ) %>% 
  separate(cultivar_mix, into = c("cult_cereal", "cult_legume"), sep = "_")


```

## Yield cereal


```{r}
yield_cereal_wt_pea <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "cereal") %>%
  inner_join(data_diff_wt_pea %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_cereal = value)



data_plot_yield_cereal <- yield_cereal_wt_pea %>% 
  left_join(itk_wt_pea) %>% 
  left_join(data_diff_wt_pea) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, yield_cereal, colnames(itk_wt_pea),
         NNI_C = NNI_cereal, diff_max_LAI, cover = cover_before_800_normalized_tt, cover_before_800_normalized_tt_SC_cereal)


```



## PLER cereal


```{r}
PLER_cereal_wt_pea <- data_BE_CE_SE %>%
  shorten_exp_id() %>% 
  inner_join(data_diff_wt_pea %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, PLER_cereal)



data_plot_PLER_cereal <- PLER_cereal_wt_pea %>% 
  left_join(itk_wt_pea) %>% 
  left_join(data_diff_wt_pea) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, PLER_cereal, colnames(itk_wt_pea),
        diff_slope_height, diff_lambda_height, diff_asymp_height, diff_IC_SC_asymp_height_cereal)


```



## Yield legume




```{r}
yield_legume_wt_pea <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "legume") %>%
  inner_join(data_diff_wt_pea %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_legume = value) %>% 
  group_by(experiment_id, management) %>% 
  summarise(yield_legume = max(yield_legume), .groups = "drop")


data_diff_wt_pea %>% colnames


data_plot_yield_legume <- yield_legume_wt_pea %>% 
  left_join(itk_wt_pea) %>% 
  left_join(data_diff_wt_pea) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, yield_legume, colnames(itk_wt_pea),
         diff_IC_SC_slope_biomass_legume, diff_max_LAI, diff_slope_biomass, diff_IC_SC_cover = cover_before_800_normalized_tt_SC_legume,diff_IC_SC_lambda_biomass_legume, diff_asymp_height)


```




## PLER legume


```{r}
PLER_legume_wt_pea <- data_BE_CE_SE %>%
  shorten_exp_id() %>% 
  inner_join(data_diff_wt_pea %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, PLER_legume)



data_plot_PLER_legume <- PLER_legume_wt_pea %>% 
  left_join(itk_wt_pea) %>% 
  left_join(data_diff_wt_pea) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, PLER_legume, colnames(itk_wt_pea),
         diff_IC_SC_slope_biomass_legume, diff_max_LAI, diff_slope_biomass, diff_IC_SC_cover = cover_before_800_normalized_tt_SC_legume,diff_IC_SC_lambda_biomass_legume, diff_asymp_height)



```



# Wheat turgidum / faba bean



```{r}



data_diff_wt_fababean <- data_all_diff%>%
  left_join(data.intercrop::index %>% distinct(experiment_id, management, species_mix)) %>%
  filter(species_mix== "wheat_turgidum_fababean") %>%
  shorten_exp_id()  %>% 
  group_by(experiment_id, management) %>% 
  summarise(across(where(is.numeric), mean), .groups = "drop")


index <- data.intercrop::index %>% 
  shorten_exp_id()%>%
  inner_join(data_diff_wt_fababean %>% distinct(experiment_id, management) ) 



itk_wt_fababean <- index %>% distinct(experiment_id, management, cultivar_mix, N_amount, mixing_pattern, mixture_design,  density_factor ) %>% 
  separate(cultivar_mix, into = c("cult_cereal", "cult_legume"), sep = "_")


```

## Yield cereal


```{r}
yield_cereal_wt_fababean <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "cereal") %>%
  inner_join(data_diff_wt_fababean %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_cereal = value)



data_plot_yield_cereal <- yield_cereal_wt_fababean %>% 
  left_join(itk_wt_fababean) %>% 
  left_join(data_diff_wt_fababean) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, yield_cereal, colnames(itk_wt_fababean),
        diff_slope_biomass,diff_lambda_biomass, diff_asymp_height, diff_max_LAI, cover = cover_before_800_normalized_tt, cover_before_800_normalized_tt_SC_cereal, cereal_asymp_height)


```






## PLER cereal


```{r}
PLER_cereal_wt_fababean <- data_BE_CE_SE %>%
  shorten_exp_id() %>% 
  inner_join(data_diff_wt_fababean %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, PLER_cereal)



data_plot_PLER_cereal <- PLER_cereal_wt_fababean %>% 
  left_join(itk_wt_fababean) %>% 
  left_join(data_diff_wt_fababean) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, PLER_cereal, colnames(itk_wt_fababean),
        diff_slope_biomass,NNI_C = NNI_cereal, diff_asymp_height, diff_max_LAI)


```



## Yield legume


```{r}
yield_legume_wt_fababean <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "legume") %>%
  inner_join(data_diff_wt_fababean %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_legume = value)



data_plot_yield_legume <- yield_legume_wt_fababean %>% 
  left_join(itk_wt_fababean) %>% 
  left_join(data_diff_wt_fababean) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, yield_legume, colnames(itk_wt_fababean),
        diff_slope_biomass,diff_lambda_biomass, diff_asymp_height, diff_max_LAI, diff_slope_height, cover_before_800_normalized_tt_SC_legume)


```




# All legumes



```{r}



data_diff_all_species <- data_all_diff%>%
  left_join(data.intercrop::index %>% distinct(experiment_id, management, species_mix)) %>%
  shorten_exp_id()  %>% 
  group_by(experiment_id, management) %>% 
  summarise(across(where(is.numeric), mean), .groups = "drop")


index <- data.intercrop::index %>% 
  shorten_exp_id()%>%
  inner_join(data_diff_all_species %>% distinct(experiment_id, management) ) 



itk_all_species <- index %>% distinct(experiment_id, management, cultivar_mix, N_amount, mixing_pattern, mixture_design,  density_factor, species_mix ) %>% 
  separate(cultivar_mix, into = c("cult_cereal", "cult_legume"), sep = "_")


```

## Yield cereal


```{r}
yield_cereal_all_species <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "cereal") %>%
  inner_join(data_diff_all_species %>% distinct(experiment_id, management)) %>% 
  distinct(experiment_id, management, yield_cereal = value)



data_plot_yield_cereal <- yield_cereal_all_species %>% 
  left_join(itk_all_species) %>% 
  left_join(data_diff_all_species) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, yield_cereal, colnames(itk_all_species),
        NNI_C = NNI_cereal, diff_max_LAI, cover = cover_before_800_normalized_tt, diff_IC_SC_cover_C = cover_before_800_normalized_tt_SC_cereal, diff_slope_biomass) %>% 
  mutate(species_mix = fct_recode(species_mix, "Blé dur / Féverole" = "wheat_turgidum_fababean", "Blé dur / Pois" = "wheat_turgidum_pea"))


```




## Yield legume


```{r}
yield_legume_all_species <- data.intercrop::traits_mean %>%
  shorten_exp_id() %>% 
  filter(variable == "biomass_seed", plant_family == "legume") %>%
  inner_join(data_diff_all_species %>% distinct(experiment_id, management)) %>% 
  group_by(experiment_id, management) %>% 
  summarise(value = max(value), .groups = "drop") %>% 
  distinct(experiment_id, management, yield_legume = value)



data_plot_yield_legume <- yield_legume_all_species %>% 
  left_join(itk_all_species) %>% 
  left_join(data_diff_all_species) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, yield_legume, colnames(itk_all_species),
        diff_asymp_height, diff_max_LAI, cover = cover_before_800_normalized_tt, diff_IC_SC_cover_L = cover_before_800_normalized_tt_SC_legume, diff_slope_biomass) %>% 
  mutate(species_mix = fct_recode(species_mix, "Blé dur / Féverole" = "wheat_turgidum_fababean", "Blé dur / Pois" = "wheat_turgidum_pea"))


```


## Yield both



```{r}
yield_all_species <- yield_cereal_all_species %>% left_join(yield_legume_all_species)



data_plot_yield_all_species <- yield_all_species %>% 
  left_join(itk_all_species) %>% 
  left_join(data_diff_all_species) %>% 
  left_join(data_NNI) %>% 
  select(experiment_id, management, yield_cereal, yield_legume, colnames(itk_all_species),
        NNI_C = NNI_cereal, NNI_L = NNI_legume, diff_max_LAI, cover = cover_before_800_normalized_tt, diff_slope_biomass) %>%   mutate(species_mix = fct_recode(species_mix, "Blé dur / Féverole" = "wheat_turgidum_fababean", "Blé dur / Pois" = "wheat_turgidum_pea"))


```

# Transfer plots



```{r}

folder_modeling <- "C:/Users/rmahmoud/Documents/INRA/These/R_projects_phD/paper_modeling_intercrop/figures"
folder_presentations <- "C:/Users/rmahmoud/Documents/INRA/These/Presentations/meeting_22_11_2022/presentation_figures"
list_of_files <- list.files(folder_modeling, "(.*)marginal(.*).png$",recursive = TRUE, full.names = TRUE) 

file.copy(file.path(list_of_files), folder_presentations, overwrite = TRUE)
```



```{r}

data.qualitative::legumes %>% filter(species == "fababean") %>% distinct(species, cultivar,  height, crop_height)

data.qualitative::legumes %>% filter(species == "fababean", !is.na(height), cultivar != "columbo") %>% distinct(species, cultivar,  height, crop_height)


data.qualitative::cereals %>% filter(species == "durum_wheat", cultivar %in% c("L1823", "acalou", "nefer", "neodur","orjaune", "sculptur"
))

```

